### ISSUE TITLE
Support overlay2 storage driver

### ISSUE THREAD

**Issue by pulberg** [rancher/os#1075]
#928

**Comment by joshwget** [comment]
We're definitely interested in switching to overlay2. Unfortunately, it'll cause upgrade problems from RancherOS versions using the existing overlay driver. We might move to overlay2 for new installs and use overlay when upgrading from an earlier version.

**Comment by joshwget** [comment]
I think we'll wait on #1166 before we switch to overlay2 as the default. This refactoring will make it easier to handle upgrades and switching between Docker versions.

**Comment by SolidNerd** [comment]
Hey, 
i would like to know if it's possible to switch to overlay2 with the latest version (0.6.0). I tried it with the following command: 

```bash
sudo ros config set "[daemon, --log-opt, max-size=25m, --log-opt, max-file=2, -s, overlay2, -G, docker, -H, 'unix:///var/run/docker.sock']"
```
Start docker container after the set the config.

```bash
sudo system-docker start docker
```

For me it's not working.

**Comment by joshwget** [comment]
This will be easier to configure in v0.7.0.

```
#cloud-config
rancher:
  docker:
    storage_driver: overlay2
```

**Comment by Yajo** [comment]
I think it's worth pointing out that with this, I get a kernel panic:

```
#cloud-config
rancher:
  system_docker:
    storage_driver: overlay2
    selinux_enabled: false  # until kernel 4.9
```

Then, after install:
![captura de pantalla de 2016-11-04 12-58-23](https://cloud.githubusercontent.com/assets/973709/20004748/66995014-a28e-11e6-948a-5839372fe0fb.png)

**Comment by krisnod** [comment]
I also get a same kernel panic when trying to use overlay2 as an storage driver for system docker with rancher/os v1.0.3:

```
#cloud-config

rancher:
  system_docker:
    storage_driver: overlay2
```
