### ISSUE TITLE
won't obey udev rule?

### ISSUE THREAD

**Issue by rafaelsoaresbr** [rancher/os#1086]
**RancherOS Version: v5.0**

**Where are you running RancherOS? baremetal**

I've created a file "write_files.yml":

```
write_files:
  - path: /etc/udev/rules.d/99-lowbat.rules 
    permissions: "0755"
    owner: root
    content: |
      SUBSYSTEM=="power_supply", ATTR{status}=="Discharging", RUN+="/usr/sbin/poweroff"
```

and meged it with:

`sudo ros config merge -i write_files.yml`

Then I've unplugged the power cable and nothing happened.
