### ISSUE TITLE
network don't kick in after install to hard disk

### ISSUE THREAD

**Issue by mainiak** [rancher/os#1113]
**RancherOS Version: v0.5.0**

**Where are you running RancherOS? VMware ESX virtual machine**

I'm behind very restrictive firewall and without DHCP and even after I was
able to setup network manually on RancherOS Live ISO, I'm not able to do install to hard disk
and get network running. Without default password machine is dead and I had to delete VM, recreate VM and try to install it several times without success. What I'm doing wrong?

Note: IP addresses were changed for privacy reasons

### Steps to get network up manually

```bash
sudo -s
ifconfig eth0  192.168.100.20 netmask 255.255.255.128 up
route add default gw 192.168.100.1

# add nameserver 192.168.100.40 on first line
vi /etc/resolv.conf
```

### Cloud Config

```yaml
#cloud-config
hostname: 'my-rancher'
ssh_authorized_keys:
  - ssh-rsa abc...
  - ssh-rsa bcd...
rancher:
  network:
    interfaces:
      eth*:
        dhcp: false
      eth0:
       address: 192.168.100.20
       gateway: 192.168.100.1
       netmask: 255.255.255.128
    dns:
      nameservers:
        - 192.168.100.40
```

I SCP cloud-config.yml from my laptop to VM.

### Install

```
sudo -s
ros install -c cloud-config.yml -d /dev/sda
# reboot
```

### Troubleshooting

Thanks to issues bellow I was able to find kernel option to enforce rancher user password
and got into VM, but even after some fiddling with yaml files I didn't get it working.

* #662, #1034 - definitely got/burnt me
* #617 - this would help to validate before install, or even validation when using `ros config set`
* #796 - related?

Please, advice.
