### ISSUE TITLE
Loading btrfs on boot

### ISSUE THREAD

**Issue by nunofgs** [rancher/os#1126]
**RancherOS Version: (ros os version)**
0.5.0

**Where are you running RancherOS? (docker-machine, AWS, GCE, baremetal, etc.)**
Bare metal.

I have a USB drive with a _btrfs_ partition. When I plug it in, the drive is detected (shows up on `fdisk -l`) but _btrfs_ is not available.

~~I've tried to `modprobe btrfs` and then `partprobe /dev/sdb` which seems to work, but the partition never shows up on _/dev/sdbX_.~~

Nevermind, the above did work and I was able to mount my drive successfully. However, I still need to manually `modprobe btrfs` on every boot.

Is there are any way to load the module automatically on boot?

PS: Also, isn't `udev` supposed to automatically load the kernel module?

**Comment by rafaelsoaresbr** [comment]
Have you tried adding a config like this to your cloud-config file?
```
#cloud-config
write_files:
  - path: /etc/modules-load.d/btrfs.conf   #or /etc/modprob.d/btrfs.conf
    permissions: "0755"
    owner: root
    content: |
      # Load btrfs module
      btrfs
```

**Comment by joshwget** [comment]
There's a cloud-config key for loading modules:

```yaml
#cloud-config
rancher:
  modules: [btrfs]
```

I don't actually recall this feature being in our docs anywhere. This is definitely something we should add.
