### ISSUE TITLE
Improvement: automatic resizing of partition

### ISSUE THREAD

**Issue by giezi** [rancher/os#1131]
Hi there

As discussed already in the forum (https://forums.rancher.com/t/automatic-resizing-of-partition-vmware/3308) it would be very nice if there will be an "always-on" option for the resizing, like in CoreOS: If the disk will be extended on VM-Level, we just need to reboot the machine and the resize is be done fully automatically (https://coreos.com/os/docs/latest/adding-disk-space.html).

Sample:
# cloud-config

rancher:
  resize_device: /dev/sda
  resize_always: true

**RancherOS Version: (ros os version)**
0.5.0

**Where are you running RancherOS? (docker-machine, AWS, GCE, baremetal, etc.)**
VMware

Many thanks for considering this request. We really appreciate your great work on RancherOS!

Best regards
Reto

**Comment by EugenMayer** [comment]
Same issue here with a KVM based rancheros insallation:

```
rancher:
  resize_device: /dev/vda
  services_include:
    resize-fs: true
```

i could get it down manually by

```
growpart /dev/vda 1
probpart
resize2fs /dev/vda1
```

resizefs hints, that its a online-resize:

```
Filesystem at /dev/vda1 is mounted on /opt; on-line resizing required
```

But it all works out

update: found the issue https://github.com/rancher/os/issues/1131

**Comment by rockandska** [comment]
"resize-always" seems not to be implemented yet, so i added the config below inside my "cloud-config.yml" to enable the auto resizing at boot time.
````
#cloud-config
write_files:
  - path: /etc/rc.local
    permissions: "0755"
    owner: root
    content: |
      #!/bin/bash
      rm -rf /var/lib/rancher/resizefs.done
rancher:
  resize_device: /dev/sda
````
Tested on RancherOs v1.03
