### ISSUE TITLE
Use a map to configure Docker arguments

### ISSUE THREAD

**Issue by joshwget** [rancher/os#1166]
`rancher.docker.args` is currently a list, which can be difficult to extend. Making the arguments a map would make it easier to override individual arguments.

This would likely look like one of the following:

```yaml
rancher:
  docker:
    args:
      storage_driver: overlay2
```

```yaml
rancher:
  docker:
    storage_driver: overlay2
```
