### ISSUE TITLE
Booting with PXE - Cloud Init Step Doesn't Go Past Started

### ISSUE THREAD

**Issue by MattMencel** [rancher/os#1305]
**RancherOS Version: (ros os version)**
0.6.1 

**Where are you running RancherOS? (docker-machine, AWS, GCE, baremetal, etc.)**
VMware

I'm booting rancheros using ipxe.  If I don't pass a cloud-config file in my kernel rules it boots fine.  When I add the datasource for cloud-config like this...

`rancher.cloud_init.datasources=['url:http://somehost/rancheros/cloud-config.yaml']
`

When the boot gets to the cloud-init stage it seems to get stuck at step 14.  The IP is live and I can ping it, but I cannot ssh to it.

![screen shot 2016-10-10 at 5 07 16 pm](https://cloud.githubusercontent.com/assets/78883/19252754/26a0ca4a-8f0c-11e6-8d07-60fe00f2f175.png)

My cloud-config is pretty simple for the moment.

```
#cloud-config

ssh_authorized_keys:
  - ssh-rsa MYKEY

rancher:
  console: centos
  resize_device: /dev/sda
```

**Comment by joshwget** [comment]
You can add the `rancher.log` kernel parameter to see logs for each service in the console. It's likely that it's waiting until it can download the cloud-config file. It should eventually continue if it can't reach it.

**Comment by MattMencel** [comment]
Ah...so it's trying to reach out to the internet to grab a yaml file for the CentOS console stuff I think.  I'm behind a firewall and web proxy.  Is there a way to tell cloud-init to use a web proxy?

By the way, the timeout on this was over two hours.  I finally just went to bed and when I looked at it this morning it was done.  Not sure what is up with the timestamps.  They look like they go back in time for some reason.

![screen shot 2016-10-11 at 8 33 31 am](https://cloud.githubusercontent.com/assets/78883/19272348/e1a276fa-8f8d-11e6-847e-6906b5818e92.png)

**Comment by MattMencel** [comment]
I think I got it.  Setting the proxy for rancher.network and system_docker seems to have allowed it to work.  I'm not sure yet if I should set if for docker as well.

```
#cloud-config

ssh_authorized_keys:
  - ssh-rsa MYKEY
rancher:
  network:
    http_proxy: http://myproxy:8080
    https_proxy: http://myproxy:8080
    no_proxy: localhost,127.0.0.1,10.*
  resize_device: /dev/sda
  system_docker:
    environment: [http_proxy=http://myproxy:8080, https_proxy=http://myproxy:8080, no_proxy=localhost,127.0.0.1,10.*]
```
