### ISSUE TITLE
ros service compose format v2 support?

### ISSUE THREAD

**Issue by pwFoo** [rancher/os#1312]
**RancherOS Version: (ros os version)**
v0.7.0-rc4

**Where are you running RancherOS? (docker-machine, AWS, GCE, baremetal, etc.)**
notebook

Tried to add a service file with compose version v2

```
version: '2'
services:
  ...
```

Error message during sudo ros s build:
```
ERRO[0000] Could not parse config for project os : Unknown resolution for 'services' using <config.RawService Value> at line 1, column 18 
ERRO[0000] Failed to load /var/lib/rancher/conf/dengleros.yml: Unknown resolution for 'services' using <config.RawService Value> at line 1, column 18
```

So v2 isn't supported with RancherOS services? Need v2 because of compose tmpfs and group_add options.

Removed the first two lines and the service is created successful, but v2 tmpfs is missing.

**Comment by joshwget** [comment]
v2 format is currently only supported for external services. In that case the service files will look like standard Docker Compose files.

For cloud-config services I don't think we'll add the `version` key. Our current plan is to just detect the version for services based on the attributes used.

**Comment by joshwget** [comment]
I misread your original comment. It looks like you are loading the service externally. Can you post the full file and the command you used?

**Comment by pwFoo** [comment]
My current test files. enabled, build / create per local file 
```
sudo ros s enable /var/lib/rancher/conf/desktop.yml
...
```

*/var/lib/rancher/conf/desktop.yml*
```
#version: '2'
#services:
  xorg:
    image: "dengleros/xorg"
    container_name: xorg
    hostname: xorg
    privileged: true
    read_only: true
    restart: always
    environment:
    - DISPLAY=:0
    tmpfs:
    - /var/log
    volumes:
    - dengleros-tmp:/tmp
    # Workaround missing tmpfs
    - /var/log
    user: root

  dbus:
    image: "dengleros/dbus"
    container_name: dbus
    hostname: dbus
    read_only: true
    restart: always
    labels:                   
    - io.rancher.os.after=xorg
    volumes:
    - dengleros-varlibdbus:/var/lib/dbus
    - dengleros-varrundbus:/var/run/dbus
    - dengleros-homeuserdbus:/home/user/.dbus
    # xorg volume
    - dengleros-tmp:/tmp

  volumeicon:
    image: "dengleros/volumeicon"
    container_name: volumeicon
    hostname: volumeicon
    restart: always
    labels:
    - io.rancher.os.after=xorg
    environment:
    - DISPLAY=:0
    devices:
    - /dev/snd:/dev/snd
    volumes:
    - dengleros-volumeicon:/home/user/.config/volumeicon
    # Volume xorg
    - dengleros-tmp:/tmp 
```

**/var/lib/rancher/conf/fluxbox.yml**
```
#version: '2'
#services:
  fluxbox:                                   
    image: "dengleros/fluxbox"               
    container_name: fluxbox                  
    hostname: fluxbox                        
    restart: unless-stopped                  
    labels:                                  
    - io.rancher.os.after=xorg               
    - io.rancher.os.after=dbus               
    environment:                             
    - DISPLAY=:0                             
    volumes:                  
    - dengleros-homeuserfluxbox:/home/user/.fluxbox
    - /usr/bin/docker:/usr/bin/docker              
    - /var/run/docker.sock:/var/run/docker.sock    
    # Volumes xorg and dbus                        
    - dengleros-varlibdbus:/var/lib/dbus           
    - dengleros-varrundbus:/var/run/dbus           
    - dengleros-homeuserdbus:/home/user/.dbus      
    - dengleros-tmp:/tmp 
```

**/var/lib/rancher/conf/chromium.yml**
```
#version: '2'
#services:
  chromium:
    image: "dengleros/chromium"
    container_name: chromium
    hostname: chromium
    restart: on-failure
    labels:                   
    - io.rancher.os.after=xorg
    - io.rancher.os.after=dbus
    environment:
    - DISPLAY=:0
    group_add:
    - audio
    - video 
    volumes:               
    # Volumes xorg and dbus             
    - dengleros-varlibdbus:/var/lib/dbus
    - dengleros-varrundbus:/var/run/dbus     
    - dengleros-homeuserdbus:/home/user/.dbus
    - dengleros-tmp:/tmp
```

**Comment by joshwget** [comment]
Tested out a simple v2 file and I see the same error.

```
version: '2'
services:
  test:
    image: busybox
```

I guess our version of libcompose isn't new enough to support this yet. Once we update it then this should be supported for external services.
