### ISSUE TITLE
Mounting NFS in RancherOS now fails after upgrade to v0.6.1

### ISSUE THREAD

**Issue by 2devnull** [rancher/os#1314]
**RancherOS Version: (ros os version)** v0.6.1

**Where are you running RancherOS? (docker-machine, AWS, GCE, baremetal, etc.)** ESXi 6

This worked in v0.4.4, not now since I have just upgraded to v0.6.1 and it fails with the following error:

> mount.nfs: rpc.statd is not running but is required for remote locking.
> mount.nfs: Either use '-o nolock' to keep locks local, or start statd.
> mount.nfs: mounting 192.168.1.50:/share failed, reason given by server: No such file or directory

In /var/lib/rancher/conf/cloud-config.d/nfs.yml, I have:

```
#cloud-config
rancher:
  services_include:
    ubuntu-console: true

write_files:
  # /opt/rancher/bin/start.sh is executed on start before User Docker starts
  # /etc/rc.local is also executed on start but not guaranteed to be ran before User Docker
  - path: /opt/rancher/bin/start.sh
    permissions: "0755"
    owner: root
    content: |
      #!/bin/bash
      if ! dpkg -l | grep -q nfs-common; then
        apt-get update -qq && apt-get install -y nfs-common
      fi
      mkdir -p /share
      rpcbind
      # mount -t nfs 192.168.1.50:/share /share

```
