### ISSUE TITLE
supermicro with pxeboot kernel dumps on 0.5, 0.6 but not 0.4 and 0.7

### ISSUE THREAD

**Issue by SvenDowideit** [rancher/os#1348]
v odd.

we then attached a serial console, and it stopped kernel dumping, but we do notice that ros is failing to download the cloud-config - and then never gets past that - there doesn't seem to be a timeout for the yml?

I presume there's a conflation with some issue to do with the console handling and the cloud-init - poking further.

removing the yml file from the pxe cfg allows things to proceed normally (with serial console attached, and not attached.)

but without the serial console, we don't see the ros output telling us it can't get the yml file (i wonder if its only sending that to ttyS0 in either case.).

**Comment by SvenDowideit** [comment]
cloud-config is really simple:


```
#cloud-config
ssh_authorized_keys:
  - ssh-rsa A...X+FIPKcF96hrucXzcWyLbIbEgE98OHlnVYCzRdK8jlqm8tehUc9c9WhQ==
rancher:
  network:
    interfaces:
      eth0:
        dhcp: true
```
