### ISSUE TITLE
error: Cannot access cgroup for X containers

### ISSUE THREAD

**Issue by kuhnroyal** [rancher/os#1427]
RancherOS 0.7.1 running on baremetal.

I am adding https://github.com/uzyexe/dockerfile-newrelic as custom system service in order to have the newrelic system monitor running on startup.

```yaml
rancher:
  services:
    newrelic:
      image: uzyexe/newrelic
      restart: always
      net: host
      pid: host
      volumes:
        - /var/run/docker.sock:/var/run/docker.sock:ro,z
        - /sys/fs/cgroup/:/sys/fs/cgroup/:ro,z
        - /dev:/dev
      environment:
        NEW_RELIC_LICENSE_KEY: xxxx
```

This works and all the metrics display correctly on newrelic.

However, the docker integration of new relic is not working. Looking at the log of the newrelic container it prints a lot of errors like this:
```
2016-11-27 13:15:17.540 (1710) error: Cannot access cgroup for 1 containers
```

Looking inside the container the cgroups seem to be correctly mounted:
```
/sys/fs/cgroup/devices/docker # ls -la
total 0
drwxr-xr-x    3 root     root             0 Nov 27 13:10 .
drwxr-xr-x    3 root     root             0 Nov 27 13:10 ..
drwxr-xr-x    2 root     root             0 Nov 27 13:10 9186a0012bfe7e75b57b1af058b79745524ef96bb5092750e4f792a27a82730d
-rw-r--r--    1 root     root             0 Nov 27 13:20 cgroup.clone_children
-rw-r--r--    1 root     root             0 Nov 27 13:20 cgroup.procs
--w-------    1 root     root             0 Nov 27 13:20 devices.allow
--w-------    1 root     root             0 Nov 27 13:20 devices.deny
-r--r--r--    1 root     root             0 Nov 27 13:20 devices.list
-rw-r--r--    1 root     root             0 Nov 27 13:20 notify_on_release
-rw-r--r--    1 root     root             0 Nov 27 13:20 tasks
/sys/fs/cgroup/devices/docker # 
```

So I am at a lose, don't know where to look further.

**Comment by SvenDowideit** [comment]
I wonder if there's something unexpected happening because we have 2 docker daemons.

**Comment by kuhnroyal** [comment]
I managed to get it working like this:

```yaml
rancher:
  services:
    newrelic:
      image: uzyexe/newrelic
      restart: always
      net: host
      pid: host
      command: nrsysmond -c /etc/newrelic/nrsysmond.cfg -F
      volumes:
        - /etc/newrelic/nrsysmond.cfg:/etc/newrelic/nrsysmond.cfg:ro,z
        - /var/run/docker.sock:/var/run/docker.sock:ro,z
        - /sys/fs/cgroup/:/sys/fs/cgroup/:ro,z
        - /sys:/host/sys:ro,z
        - /proc:/host/proc:ro,z
        - /dev:/dev:ro,z

write_files:
  - path: /etc/newrelic/nrsysmond.cfg
    permissions: "0755"
    owner: root
    content: |
      license_key=xxxx
      loglevel=info
      logfile=/dev/stdout
      host_root=/host
      cgroup_root=/sys/fs/cgroup
```

I would like to add this as system service but that completely fails. Some of the volumes don't seem to exist for the system docker daemon.
