### ISSUE TITLE
multiple NIC two static IP addresses one address always fails

### ISSUE THREAD

**Issue by joshuacox** [rancher/os#1477]
**RancherOS Version: (ros os version)**
0.7.1

**Where are you running RancherOS? (docker-machine, AWS, GCE, baremetal, etc.)**
KVM host

When adding a second IP address the second interface is configured but I cannot contact the machine throught the second IP address.

```
# cloud-config
rancher:
  network:
    interfaces:
      eth0:
        address: 10.1.0.41/24
        gateway: 10.1.0.1
        mtu: 1500
        dhcp: false
      eth1:
        address: 10.31.168.85/24
        gateway: 10.31.168.1
        mtu: 1500
        dhcp: false
```

EDIT: this has been tried in a few different setups now including with an external IP address, I can delete the eth0 portion, reboot, and the eth1 will then work (while eth0 is inactive), but I have not seen both work at once

**Comment by joshuacox** [comment]
Is anyone else utilizing a rancherOS image that has a dual NIC setup?

**Comment by rfranke** [comment]
You might try to skip the gateway configuration in cloud-config. Our dual NIC setup with one static IP and one dhcp worked then.

**Comment by joshuacox** [comment]
I've tried both
```
rancher:
  network:
    interfaces:
      eth0:
        address: 192.168.1.35/24
        mtu: 1500
        dhcp: false
      eth1:
        address: 10.0.1.93/24
        mtu: 1500
        dhcp: false
```

and one where just the interior gateway is declared:

```
rancher:
  network:
    interfaces:
      eth0:
        address: 192.168.1.35/24
        gateway: 192.168.133.1
        mtu: 1500
        dhcp: false
      eth1:
        address: 10.0.1.93/24
        mtu: 1500
        dhcp: false
```

but always the only interface that actually works is `eth0`

**Comment by joshuacox** [comment]
for clarity your publicly accessible interface is the only one that is going to respond to external traffic as all outbound traffic will go through it(in my test setups at least), so all 'service net' type of stuff (NFS, etc) needs to be on the same network (in this case 192.168.122.0/24), e.g.

```
rancher:
  network:
    interfaces:
      eth0:
        address: 192.168.122.35/24
        mtu: 1500
        dhcp: false
      eth1:
        address: 1.1.111.93/24
        gateway: 1.1.111.65
        mtu: 1500
        dhcp: false
```

closing

**Comment by SvenDowideit** [comment]
I'm going to reopen this - while I use DHCP for my network config, I do have a few dual homed boxes I think this kind of cfg would be interesting for. (and I don't like arbitrary limitations)

**Comment by joshuacox** [comment]
Given a bit more testing with my configs the above has held true.

  I've had a cluster of rancherOS w/agents up for about a week now on a private network, and then one node (with traefik_lb=true)  on a public IP with its second interface, the first interface is on that same private net (in this case a virtual net created by virt-manager in KVM)  given that the second interface has the gateway all traffic aside from the exact subnet of the first interface goes through the gateway.  For other private networks, say another 10.1.2.0/24 next to your 192.168.122.0/24 you will have to setup routes.  

At the moment I'm just gathering all resources into a single private network and setting up VPNs into it.   Something I've found incredibly useful is [sshuttle](https://github.com/apenwarr/sshuttle) as it allows me to get into the private network remotely to poke around directly from my laptop.

Something to note is that rancher server is fine with being in the private net, and you can communicate just fine with shuttle, so long as all rancher agents you expect to talk to it are also on the same private net.

**Comment by joshuacox** [comment]
Just wondering about a few things, how does a container decide to contact another container in it's environment?  Given the dual NIC setup I've seen some traffic go out across the bridge just to talk to another container in another node on the same physical machine and actually be limited by the datacenters router (this one is a head scratcher when your looking at all your VMs in virt-manager).   This went largely unnoticed by me till recently when I noticed some stuff taking inordinate amounts of time to copy etc.

**Comment by SvenDowideit** [comment]
I need to test, but #1666 should impact this

**Comment by SvenDowideit** [comment]
I'm adding your initial example to the tests - and first problem is that `# cloud-config` (with a space) is not correct :(

its really hard atm to surface these issues - they're hidden in the log :(

**Comment by SvenDowideit** [comment]
and yup, in my tests, #1666 almost makes this work (atm, you get both your IP, and the dhcp one, but I'm working on it)

**Comment by SvenDowideit** [comment]
@joshuacox does 0.9.0 work for you? I think it should work, baring that its not removing the non-static dhcp address after bootstrapping - #1705

(if its good, please close this issue)

**Comment by joshuacox** [comment]
just upgraded upon your prompting.  It all looks good so far.  I'll paste my net config. @SvenDowideit  feel free to reopen if you need more info.  I'm pretty heavily invested in this method so I will do whatever I can to help out.

```
[root@rancher cloud-config.d]# pwd
/var/lib/rancher/conf/cloud-config.d
[root@rancher cloud-config.d]# cat user_config.yml
# cloud-config
rancher:
  network:
    interfaces:
      eth0:
        address: 192.168.7.50/24
        mtu: 1500
        dhcp: false
      eth1:
        address: x.x.x.85/24
        gateway: x.x.x.1
        mtu: 1500
        dhcp: false
```

**Comment by joshuacox** [comment]
@SvenDowideit I went ahead and tested dhcp out as well.  All good received and IP from the dhcp server just fine:

```
rancher:
  network:
    interfaces:
      eth0:
        dhcp: true
      eth1:
        address: x.x.x.87/24
        gateway: x.x.x.1
        mtu: 1500
        dhcp: false
```
