### ISSUE TITLE
Support changing Docker engines by pointing directly to binaries

### ISSUE THREAD

**Issue by joshwget** [rancher/os#1531]
The following should work.

`ros engine switch https://get.docker.com/builds/Linux/x86_64/docker-1.13.0.tgz`

```
#cloud-config
rancher:
  docker:
    engine: https://get.docker.com/builds/Linux/x86_64/docker-1.13.0.tgz
```
