### ISSUE TITLE
IP address on tagged VLAN interface

### ISSUE THREAD

**Issue by simwood-simon** [rancher/os#1551]
Hi there

**RancherOS Version: (ros os version)**
v0.7.1

**Where are you running RancherOS? (docker-machine, AWS, GCE, baremetal, etc.)**
Baremetal.

I have a config like:

```
    interfaces:
      "mac=00:25:90:xx:xx:xx:xx":
        dhcp: true
      "mac=00:1b:21:xx:xx:xx:xx":
        vlans: 234:infra,264:public
      infra:
        address: xxx.xxx.xxx.xxx/xx
      public:
        address: xxx.xxx.xxx.xxx/xx
```

Whilst the interfaces are created and brought up, the IP addresses are not assigned. `ros config export` shows that they are there but they do not show in ifconfig and are unresponsive from the switch side of things.

I couldn't find any known issues like this.

Thanks!
Simon
