### ISSUE TITLE
Cloud config mounts don't seem to support nfs

### ISSUE THREAD

**Issue by ryansch** [rancher/os#1620]
**RancherOS Version: (ros os version)**
v0.8.0

**Where are you running RancherOS? (docker-machine, AWS, GCE, baremetal, etc.)**
AWS

I've integrated AWS EFS into our docker cluster.  I tried adding the following to my cloud config:

```yaml
 mounts:
    - ["${efs_server}:/", "/mnt/efs", "nfs4", "nfsvers=4.1,rsize=1048576,wsize=1048576,hard,timeo=600,retrans=2"]
```

This had no effect.

My current workaround is to run it via a container:

```yaml
    nfs-client:
      image: outstand/nfs-client:latest
      restart: always
      labels:
        - io.rancher.os.remove=false
      volumes:
        - /mnt/efs:/mnt/efs:shared
      privileged: true
      net: host
      environment:
        SERVER: ${efs_server}
        SHARE: /
        MOUNTPOINT: /mnt/efs
        FSTYPE: nfs4
        MOUNT_OPTIONS: nfsvers=4.1,rsize=1048576,wsize=1048576,hard,timeo=600,retrans=2
```
