### ISSUE TITLE
RancherOS doesn't use available swap

### ISSUE THREAD

**Issue by huggla** [rancher/os#1670]
**RancherOS Version: (ros os version)**
v0.8.1
**Where are you running RancherOS? (docker-machine, AWS, GCE, baremetal, etc.)**
rancher.iso

I run the following script from /etc/rc.local:

```
#!/bin/sh
totalCpu=`cat /proc/cpuinfo | grep -ce "^processor"`
totalMem=`cat /proc/meminfo | grep -e "^MemTotal:" | sed -e 's/^MemTotal: *//' -e 's/  *.*//'`
zramFraction=75
ros service enable kernel-extras
ros service up -d kernel-extras 
modprobeArgs="num_devices=$totalCpu"
modprobe zram $modprobeArgs         
zMem=$(((totalMem * zramFraction / 100 / totalCpu) * 1024))
i=0                                                        
while [ $i -lt $totalCpu ]
do                        
echo $zMem > /sys/block/zram$i/disksize
mkswap /dev/zram$i                     
swapon -p 5 /dev/zram$i
i=$[$i+1]              
done
```
The script creates a number of zram swaps (how many and how large depends on available resources). The swaps shows up correctly when running swapon -s, free and cat /proc/meminfo. The problem is that RancherOS may run out of memory but never ever uses the available swap. In the example bellow you can see that out of the total 4048320 kB ram, 3036232 kB is used for the zram swap. Of the remaining 1750788 kB ram not much is remaining, but still no swap is used.

```
MemTotal:        4048320 kB
MemFree:         1750788 kB
MemAvailable:    1687056 kB
Buffers:             184 kB
Cached:          1837540 kB
SwapCached:            0 kB
Active:           963036 kB
Inactive:        1030276 kB
Active(anon):     962844 kB
Inactive(anon):  1030264 kB
Active(file):        192 kB
Inactive(file):       12 kB
Unevictable:           0 kB
Mlocked:               0 kB
SwapTotal:       3036232 kB
SwapFree:        3036232 kB
Dirty:                 0 kB
Writeback:             0 kB
AnonPages:        117256 kB
Mapped:           104068 kB
Shmem:           1837520 kB
Slab:             262968 kB
SReclaimable:     109528 kB
SUnreclaim:       153440 kB
KernelStack:        4848 kB
PageTables:         2872 kB
NFS_Unstable:          0 kB
Bounce:                0 kB
WritebackTmp:          0 kB
CommitLimit:     5060392 kB
Committed_AS:    3529660 kB
VmallocTotal:   34359738367 kB
VmallocUsed:           0 kB
VmallocChunk:          0 kB
HardwareCorrupted:     0 kB
AnonHugePages:     43008 kB
ShmemHugePages:        0 kB
ShmemPmdMapped:        0 kB
CmaTotal:              0 kB
CmaFree:               0 kB
HugePages_Total:       0
HugePages_Free:        0
HugePages_Rsvd:        0
HugePages_Surp:        0
Hugepagesize:       2048 kB
DirectMap4k:       55232 kB
DirectMap2M:     4139008 kB
```
A similar issue reported in the Rancher forums:
[https://forums.rancher.com/t/low-swap-usage-and-swappiness/4952](https://forums.rancher.com/t/low-swap-usage-and-swappiness/4952)

**Comment by huggla** [comment]
Still not working in v1.0.0.

**Comment by SvenDowideit** [comment]
I think this  has something to do with the way containers interact with swap, but its pretty strange.

If I set up

```
#cloud-config
rancher:
  state:
    formatzero: true
    fstype: auto
    dev: LABEL=RANCHER_STATE
    autoformat:
    - /dev/sda
    - /dev/vda
runcmd:
- sudo dd if=/dev/zero of=/swapfile bs=1k count=1M
- sudo chmod 600 /swapfile
- sudo mkswap /swapfile
- sudo swapon /swapfile
ssh_authorized_keys:
  - ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQC85w9stZyiLQp/DkVO6fqwiShYcj1ClKdtCqgHtf+PLpJkFReSFu8y21y+ev09gsSMRRrjF7yt0pUHV6zncQhVeqsZtgc5WbELY2DOYUGmRn/CCvPbXovoBrQjSorqlBmpuPwsStYLr92Xn+VVsMNSUIegHY22DphGbDKG85vrKB8HxUxGIDxFBds/uE8FhSy+xsoyT/jUZDK6pgq2HnGl6D81ViIlKecpOpWlW3B+fea99ADNyZNVvDzbHE5pcI3VRw8u59WmpWOUgT6qacNVACl8GqpBvQk8sw7O/X9DSZHCKafeD9G5k+GYbAUz92fKWrx/lOXfUXPS3+c8dRIF
```

and then (on a 2GB RAM vm, run `sh -c "MEMBLOB=\$(dd if=/dev/urandom bs=1MB count=$N) ; read"`, it does swap and not OOM:

```
[rancher@rancher-dev ~]$ free -m
             total       used       free     shared    buffers     cached
Mem:          2001       1932         68          0          1         20
-/+ buffers/cache:       1910         91
Swap:         1023        810        213
```

but as you say, its extremely reluctant - even setting `sysctl -w vm.swappiness=100` isn't changing that.
