### ISSUE TITLE
When custom services fail to start the error should be logged

### ISSUE THREAD

**Issue by janeczku** [rancher/os#1675]
**RancherOS Version: (ros os version)**
v0.7.1

**Steps to reproduce**

1. Add the following cloud-config.

```
#cloud-config
rancher:
  services:
    foo:
      command: bar
      image: foo/bar
      restart: never
```
Note that restart policy `never` is invalid.

2. Restart the server

**Actual result**

The service is not started. There is no error in the logs relating to the failed start.

**Expected result**

When a service fails to start, the error should be logged to `/var/log/messages` so the user can easily troubleshoot.

When starting the service manually the error is printed to stdout:

> $ sudo ros service up foo
ERRO[0000] Failed Starting rancher-agent-launch : invalid restart policy never
