### ISSUE TITLE
Network configuration broken after update 0.8.1 -> 0.9.0 

### ISSUE THREAD

**Issue by kuhnroyal** [rancher/os#1705]
**RancherOS Version: (ros os version)**
0.9.0

**Where are you running RancherOS? (docker-machine, AWS, GCE, baremetal, etc.)**
baremetal

```
rancher:
  console: ubuntu
  network:
    interfaces:
      eth0:
        address: 192.168.1.25/24
        gateway: 192.168.1.1
        dhcp: false
```

I did an upgrade on 2 machines with `sudo ros os upgrade`. Both are configured to have a static IP address for `eth0` and dhcp disabled. After the reboot they both have 2 IPs, the static one and one given via dhcp.

I can ping and ssh with both IP's but they use the dhcp IP for outgoing communication which breaks a lot of things in my network. `ifconfig` show the dhcp IP bound to `eth0`.

After a downgrade to `v0.8.1` it works normal again. 

**Edit**
After the downgrade the IP's are fixed but all my docker local volumes are gone...
