### ISSUE TITLE
Hardcoded option for logging drivers(really awful)

### ISSUE THREAD

**Issue by ket4yii** [rancher/os#1811]
**RancherOS Version: (ros os version)**
v.1.0.0

**Where are you running RancherOS? (docker-machine, AWS, GCE, baremetal, etc.)**

Parallels 6

With gelf driver max-file opt is passed that are not supported by gelf-driver. Now we can't use any log driver, instead of JSON-driver and standard driver, of course.

Part of my config:
```
rancher:
...
  docker:
    log_driver: gelf
    log_opts:
      gelf-address: "udp://logstash.service.x:12201"
```

Docker daemon log:

```
Command "daemon" is deprecated, and will be removed in Docker 1.16. Please run `dockerd` directly.
Failed to set log opts: unknown log opt "max-file" for gelf log driver
```

**Comment by ket4yii** [comment]
Fixed it with
```
docker:
    log_driver: gelf
    log_opts:
      max-file: ''
      max-size: ''
      gelf-address: "udp://logstash.service.x:12201"
```

that is, I think, is not the best way. I think, it should be in the docs about dockerd, because this behaviour is not expected at all.
