### ISSUE TITLE
assigning an ipv6 in cloud-config prevents assignment of link-local address

### ISSUE THREAD

**Issue by tercenya** [rancher/os#1820]
RancherOS Version: **v1.0.1-rc3**

Where are you running RancherOS? **baremetal**

**Problem**

given a cloud-config such as:
```
rancher:
  network:
    interfaces:
      eth0:
        address: fd00:af1c:0:0:20:0::30/64
        dhcp: false
```

the system assigns the requested address, but fails to assign the fe80::/64 link-local address.

```
# ifconfig eth0
eth0      Link encap:Ethernet  HWaddr 00:24:E8:52:9C:50
          inet6 addr: fd00:af1c::20:0:0:30/64 Scope:Global
          UP BROADCAST RUNNING MULTICAST  MTU:1500  Metric:1
          RX packets:4708 errors:0 dropped:5 overruns:0 frame:0
          TX packets:2728 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:1000
          RX bytes:496075 (484.4 KiB)  TX bytes:1857952 (1.7 MiB)
```
You get the same behvaior using `addressses:` instead of `address`.  Settings `dhcp: true` (and receiving an ipv4 lease) sets an ipv6 link-local address, as expected:

```
eth3      Link encap:Ethernet  HWaddr 00:24:E8:52:9C:56
          inet addr:128.194.118.232  Bcast:128.194.118.255  Mask:255.255.255.0
          inet6 addr: fe80::224:e8ff:fe52:9c56/64 Scope:Link
          UP BROADCAST RUNNING MULTICAST  MTU:1500  Metric:1
          RX packets:2384 errors:0 dropped:4 overruns:0 frame:0
          TX packets:380 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:1000
          RX bytes:293274 (286.4 KiB)  TX bytes:60310 (58.8 KiB)
```

**Expected behavior:**

The system should assign the EUI-64 link-local address even when other global IPV6 addresses have been specified.

**Comment by SvenDowideit** [comment]
I think if you want an ipv4ll, you need to add it explicitly?

```
rancher:
  network:
    interfaces:
      eth0:
        ip4ll: true
        address: fd00:af1c:0:0:20:0::30/64
        dhcp: false
```
