### ISSUE TITLE
awslogs driver not functioning as expected

### ISSUE THREAD

**Issue by a-h** [rancher/os#1850]
**RancherOS Version: (ros os version)**

v1.0.0

**Where are you running RancherOS? (docker-machine, AWS, GCE, baremetal, etc.)**

AWS EC2 instance

**Steps to reproduce**

Run an EC2 instance with a similar cloud-config to below as the userdata. Note the `logging` section.

```yaml
#cloud-config
rancher:
  services:
    servicename:
      environment:
       - ENV1=8080
      image: docker/container
      restart: always
      ports:
        - 8080:8080
      logging:
        driver: awslogs
        options:
          awslogs-region: eu-west-2
          awslogs-group: dev-servicename-logs
```

Ensure that the EC2 instance has an IAM role assigned to it which allows it to create log streams.

```json
{
  "Version": "2012-10-17",
  "Statement": [
    {
      "Effect": "Allow",
      "Action": [
        "cloudwatch:PutMetricData",
        "logs:CreateLogGroup",
        "logs:CreateLogStream",
        "logs:DescribeLogGroups",
        "logs:DescribeLogStreams",
        "logs:PutLogEvents"
      ],
      "Resource": [
        "*"
      ]
    }
  ]
}
```

SSH onto the box once it has started and check that the log configuration has been applied.

```
$ docker inspect -f '{{.HostConfig.LogConfig.Type}}' servicename
json-file
```

Expected to see: `awslogs`, but saw `json-file`.

`docker logs servicename` outputs log entries to the console, which should have been sent to CloudWatch, but the CloudWatch logs log group is empty.

*** Other ***

I tried to validate the configuration using the Go `github.com/rancher/os/config` package prior to raising the issue, but got error:

```
../netconf/bridge.go:41: cannot use bridge (type *netlink.Bridge) as type *netlink.Link in argument to netlink.LinkSetMaster:
	*netlink.Link is pointer to interface, not interface
```
