### ISSUE TITLE
Unable to compile module in container from kernel sources

### ISSUE THREAD

**Issue by janeczku** [rancher/os#1861]
**RancherOS Version: (ros os version)**
v1.0.1

The following steps worked fine on v1.0.0 but not on v1.0.1:

1. Enable and start `kernel-headers` service
2. Run a container in system-docker based off of the official sysdig-agent image that would compile the sysdig kernel module from the sources:

```
sudo system-docker run -it --name sysdig-agent --privileged --net host --pid host \
-e ACCESS_KEY=123-BOGUS -e COLLECTOR=example.com -e COLLECTOR_PORT=6443  \
-e CHECK_CERTIFICATE=false --restart on-failure:3   \
-v /var/run/docker.sock:/host/var/run/docker.sock -v /dev:/host/dev -v /proc:/host/proc:ro   \ 
-v /boot:/host/boot:ro -v /lib/modules:/host/lib/modules:ro -v /usr:/host/usr:ro   \
sysdig/agent
```

See official docs: https://support.sysdig.com/hc/en-us/articles/204498905-Sysdig-Install-Standard-Linux-Docker-CoreOS-

Result:

`Your kernel headers for kernel 4.9.24-rancher cannot be found at /lib/modules/4.9.24-rancher/build or /lib/modules/4.9.24-rancher/source.`

Log:
```
* Setting up /usr/src links from host
* Setting access key
* Setting tags
* Setting collector endpoint
* Setting collector port
* Setting SSL certificate check level
* Mounting memory cgroup fs
* Unloading sysdigcloud-probe, if present
rmmod: ERROR: Module sysdigcloud_probe is not currently loaded
* Running dkms autoinstall
Error! echo
Your kernel headers for kernel 4.9.24-rancher cannot be found at
/lib/modules/4.9.24-rancher/build or /lib/modules/4.9.24-rancher/source.
* Trying to load a system sysdigcloud-probe, if present
* Trying to load a dkms sysdigcloud-probe, if present
* Trying to find precompiled sysdigcloud-probe for 4.9.24-rancher
Found kernel config at /proc/config.gz
* Trying to download precompiled module from https://s3.amazonaws.com/download.draios.com/stable/sysdig-probe-binaries/sysdigcloud-probe-0.59.0-x86_64-4.9.24-rancher-f16bf9e01da858e50da98e2931c35f2b.ko
Download failed, consider compiling your own sysdigcloud-probe and loading it or getting in touch with the sysdig community

```

**Comment by SvenDowideit** [comment]
Seems to work for me on a fresh 1.0.1 Ec2 VM:

```
[root@sven101 rancher]# uname -a
Linux sven101 4.9.24-rancher #1 SMP Fri Apr 21 14:30:02 UTC 2017 x86_64 GNU/Linux
[root@sven101 rancher]# ros -v
ros version v1.0.1

[root@sven101 rancher]# ros service enable kernel-headers
Pulling kernel-headers (rancher/os-headers:4.9.24-rancher)...
4.9.24-rancher: Pulling from rancher/os-headers
709515475419: Pull complete
14188d06b91b: Pull complete
b3a32c5cb8b5: Pull complete
7e3565d7f755: Pull complete
Digest: sha256:205d68a04d3a6b699a48ecf1a341c520c4aa6e95105f4d7e26f1fc921da538cc
Status: Downloaded newer image for rancher/os-headers:4.9.24-rancher
[root@sven101 rancher]# ros service up kernel-headers
> INFO[0000] Project [os]: Starting project
> INFO[0000] [0/18] [kernel-headers]: Starting
> INFO[0002] [1/18] [kernel-headers]: Started
> INFO[0002] Project [os]: Project started
[root@sven101 rancher]# system-docker run --rm -it -v /:/host alpine sh
/ # ls -la //host/lib/
firmware/  modules/
/ # ls -la //host/lib/
firmware/  modules/
/ # ls -la //host/lib/modules/4.9.24-rancher/
.headers-done        kernel/              modules.alias.bin    modules.builtin.bin  modules.dep.bin      modules.order        modules.symbols      source
build/               modules.alias        modules.builtin      modules.dep          modules.devname      modules.softdep      modules.symbols.bin
/ # ls -la //host/lib/modules/4.9.24-rancher/
.headers-done        kernel/              modules.alias.bin    modules.builtin.bin  modules.dep.bin      modules.order        modules.symbols      source
build/               modules.alias        modules.builtin      modules.dep          modules.devname      modules.softdep      modules.symbols.bin
/ # ls -la //host/lib/modules/4.9.24-rancher/build/
Documentation/   Module.symvers   certs/           firmware/        init/            lib/             net/             security/        usr/
Kconfig          arch/            crypto/          fs/              ipc/             linux-firmware/  samples/         sound/           virt/
Makefile         block/           drivers/         include/         kernel/          mm/              scripts/         tools/
/ # ls -la //host/lib/modules/4.9.24-rancher/build/
total 1400
drwxr-xr-x   25 root     root          4096 May 17 21:55 .
drwxr-xr-x    4 root     root          4096 May 17 21:55 ..
drwxr-xr-x   11 root     root          4096 May 17 21:55 Documentation
-rw-rw-r--    1 root     root           252 Apr 21 07:31 Kconfig
-rw-rw-r--    1 root     root         59040 Apr 21 07:31 Makefile
-rw-r--r--    1 root     root       1263015 Apr 21 14:30 Module.symvers
drwxr-xr-x   33 root     root          4096 May 17 21:55 arch
drwxr-xr-x    3 root     root          4096 May 17 21:55 block
drwxr-xr-x    2 root     root          4096 May 17 21:55 certs
drwxr-xr-x    4 root     root          4096 May 17 21:55 crypto
drwxr-xr-x  128 root     root          4096 May 17 21:55 drivers
drwxr-xr-x    2 root     root          4096 May 17 21:55 firmware
drwxr-xr-x   75 root     root          4096 May 17 21:55 fs
drwxr-xr-x   30 root     root          4096 May 17 21:55 include
drwxr-xr-x    2 root     root          4096 May 17 21:55 init
drwxr-xr-x    2 root     root          4096 May 17 21:55 ipc
drwxr-xr-x   15 root     root          4096 May 17 21:55 kernel
drwxr-xr-x   12 root     root          4096 May 17 21:55 lib
drwxr-xr-x    9 root     root          4096 May 17 21:55 linux-firmware
drwxr-xr-x    3 root     root          4096 May 17 21:55 mm
drwxr-xr-x   64 root     root          4096 May 17 21:55 net
drwxr-xr-x   24 root     root          4096 May 17 21:55 samples
drwxr-xr-x   14 root     root          4096 May 17 21:55 scripts
drwxr-xr-x   10 root     root          4096 May 17 21:55 security
drwxr-xr-x   23 root     root          4096 May 17 21:55 sound
drwxr-xr-x   25 root     root          4096 May 17 21:55 tools
drwxr-xr-x    2 root     root          4096 May 17 21:55 usr
drwxr-xr-x    4 root     root          4096 May 17 21:55 virt
/ # [root@sven101 rancher]#
[root@sven101 rancher]#
[root@sven101 rancher]# sudo system-docker run -it --name sysdig-agent --privileged --net host --pid host \
> -e ACCESS_KEY=123-BOGUS -e COLLECTOR=example.com -e COLLECTOR_PORT=6443  \
> -e CHECK_CERTIFICATE=false --restart on-failure:3   \
> -v /var/run/docker.sock:/host/var/run/docker.sock -v /dev:/host/dev -v /proc:/host/proc:ro   \
system-docker: Error parsing reference: " " is not a valid repository/tag.
See 'system-docker run --help'.
[root@sven101 rancher]# -v /boot:/host/boot:ro -v /lib/modules:/host/lib/modules:ro -v /usr:/host/usr:ro   \
> sysdig/agent
bash: -v: command not found
<n/docker.sock -v /dev:/host/dev -v /proc:/host/proc:ro   -v /boot:/host/boot:ro -v /lib/modules:/host/lib/modules:ro -v /usr:/host/usr:ro   \                     
> sysdig/agent
Unable to find image 'sysdig/agent:latest' locally
latest: Pulling from sysdig/agent
2b776633ca15: Pull complete
bfa2c3fe67f0: Pull complete
2c8757baa688: Pull complete
f255c20e466e: Pull complete
70eb17187c26: Pull complete
97681619045e: Pull complete
2911dc58e096: Pull complete
58164e9de904: Pull complete
Digest: sha256:c515a0f8a598f761b1d95a99b2c39e41974102b816db9baf1456738bc395eb67
Status: Downloaded newer image for sysdig/agent:latest
* Setting up /usr/src links from host
* Setting access key
* Setting collector endpoint
* Setting collector port
* Setting SSL certificate check level
* Mounting memory cgroup fs
* Unloading sysdigcloud-probe, if present
rmmod: ERROR: Module sysdigcloud_probe is not currently loaded
* Running dkms autoinstall

Kernel preparation unnecessary for this kernel.  Skipping...

Building module:
cleaning build area...
make -j1 KERNELRELEASE=4.9.24-rancher -C /lib/modules/4.9.24-rancher/build M=/var/lib/dkms/draios-agent/0.60.0/build....
cleaning build area...
Kernel cleanup unnecessary for this kernel.  Skipping...

DKMS: build completed.

sysdigcloud-probe.ko:
Running module version sanity check.
 - Original module
   - No original module exists within this kernel
 - Installation
   - Installing to /lib/modules/4.9.24-rancher/kernel/extra/
mkdir: cannot create directory '/lib/modules/4.9.24-rancher/kernel/extra': Read-only file system
cp: cannot create regular file '/lib/modules/4.9.24-rancher/kernel/extra/sysdigcloud-probe.ko': No such file or directory

depmod...

DKMS: install completed.
* Trying to load a system sysdigcloud-probe, if present
* Trying to load a dkms sysdigcloud-probe, if present
sysdigcloud-probe found and loaded in dkms
statsite[2906]: Starting statsite.
statsite[2906]: Listening on stdin.
statsite[2906]: Listening on tcp '127.0.0.1:8125'
statsite[2906]: Listening on udp '127.0.0.1:8125'.
2017-05-17 21:58:05.908, 2904, Information, Agent starting (version 0.60.0)
2017-05-17 21:58:05.908, 2904, Information, System uptime: 399s
2017-05-17 21:58:05.908, 2904, Information, Kernel version: 4.9.24-rancher
2017-05-17 21:58:05.910, 2904, Information, Distribution: 9.0

2017-05-17 21:58:05.910, 2904, Information, machine id: 02:4e:35:ed:51:da
2017-05-17 21:58:05.910, 2904, Information, rootdir: /opt/draios
```

**Comment by SvenDowideit** [comment]
this isn't how I'd suggest doing it, but... its possible:

```
#cloud-config
rancher:
  services:
    kernel-headers-enabled:
      image: alpine
      command: ros service enable kernel-headers
      entrypoint: /usr/bin/ros entrypoint
      privileged: true
      labels:
        io.rancher.os.scope: system
        io.rancher.os.detach: "false"
      pid: host
      net: host
      volumes_from:
      - all-volumes
    kernel-headers-completed:
      image: alpine
      command: ros service up kernel-headers
      entrypoint: /usr/bin/ros entrypoint
      privileged: true
      labels:
        io.rancher.os.scope: system
        io.rancher.os.after: kernel-headers-enabled
        io.rancher.os.detach: "false"
      pid: host
      net: host
      volumes_from:
      - all-volumes
    start-sysdig:
      image: alpine
      command: ros service up sysdig-agent
      entrypoint: /usr/bin/ros entrypoint
      privileged: true
      labels:
        io.rancher.os.scope: system
        io.rancher.os.after: kernel-headers-completed
        io.rancher.os.detach: "false"
      pid: host
      net: host
      volumes_from:
      - all-volumes
    sysdig-agent:
      image: sysdig/agent
      privileged: true
      labels:
        io.rancher.os.scope: system
        io.rancher.os.after: kernel-headers
      pid: host
      net: host
      volumes:
      - /:/host
```
