### ISSUE TITLE
Can't change dockerd configuration

### ISSUE THREAD

**Issue by ketchoop** [rancher/os#1900]
**RancherOS Version: (ros os version)**
v1.0.1

**Where are you running RancherOS? (docker-machine, AWS, GCE, baremetal, etc.)**
Parallels VM

How can I do it? I changed log_driver and log_opt in cloud-config and reboot the hosts. But it was changed only on several machines. Docker sends logs from container to old address.

**Comment by SvenDowideit** [comment]
what do you mean by "it was changed only on several machines"?

**Comment by ket4yii** [comment]
@SvenDowideit I meant, that after reboot logs are sent to new location(that was changed by log_opts) only from two or three machines. Other machines send logs to old location.

**Comment by SvenDowideit** [comment]
@ket4yii can you please compare the output of `sudo ros config export` on a machine that it works on vs one that its not working? (atm, i have no ideas - need more debug info)

**Comment by ket4yii** [comment]
Something went right this night. Now it works, but I really have no idea why it didn't work yesterday(and I had downtime because of it), because and works now. Anyway, let me check it carefully, maybe I'll get this bug again(I hope won't)

**Comment by ket4yii** [comment]
Only one server suffered from this bug.

Server where I don't have a bug(gelf-address works fine):
```
EXTRA_CMDLINE: /init
hostname: node2
rancher:
  console: debian
  docker:
    engine: docker-17.04.0-ce
    log_driver: gelf
    log_opts:
      gelf-address: udp://x.x.30.2:12055
      max-file: ""
      max-size: ""
  environment:
    EXTRA_CMDLINE: /init
  network:
    dns:
      nameservers:
      - x.x.30.2
    interfaces:
      eth*:
        dhcp: false
      eth0:
        address: x.x.30.2/16
        gateway: x.x.0.1
  resize_device: /dev/sda
  services:
    consul-agent:
      command:
      - agent
      - -config-dir
      - /etc/consul.d
      environment:
        SERVICE_IGNORE: "true"
      image: consul:0.8.3
      net: host
      restart: unless-stopped
      volumes:
      - consul-data:/consul/data
      - /opt/config.d/consul:/etc/consul.d
    dnsmasq:
      cap_add:
      - NET_ADMIN
      environment:
        SERVICE_IGNORE: "true"
      image: andyshinn/dnsmasq
      net: host
      restart: unless-stopped
      volumes:
      - /opt/config.d/dnsmasq/dnsmasq.conf:/etc/dnsmasq.conf
    rancher-agent-bootstrap:
      command: http://rancher-server.service.x:8080/v1/scripts/565AEFA19D0621A99DB8:1483142400000:pDpeLtUYrUn1YYeK7aQy0e15U
      environment:
        CATTLE_HOST_LABELS: host=node2&role=node
      image: rancher/agent:v1.2.2
      privileged: true
      volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /var/lib/rancher:/var/lib/rancher
    registrator:
      command:
      - -internal
      - -useIpFromLabel=io.rancher.container.ip
      - -cleanup
      - consul://localhost:8500
      image: gliderlabs/registrator:master
      net: host
      restart: unless-stopped
      volumes:
      - /var/run/docker.sock:/tmp/docker.sock
  state:
    dev: LABEL=RANCHER_STATE
    wait: true
runcmd:
- - apt
  - update
- - apt
  - install
  - -y
  - python
- - ln
  - -sf
  - /usr/share/zoneinfo/Europe/Moscow
  - /etc/localtime
ssh_authorized_keys:
- xxx
- xxx
```

The server, where it doesn't work(gelf-address were changed, but it uses old addr):
```
EXTRA_CMDLINE: /init
hostname: gateway
rancher:
  console: debian
  docker:
    engine: docker-17.04.0-ce
    log_driver: gelf
    log_opts:
      gelf-address: udp://x.x.211.37:12055
      max-file: ""
      max-size: ""
  environment:
    EXTRA_CMDLINE: /init
  network:
    dns:
      nameservers:
      - x.x.211.37
    interfaces:
      eth*:
        dhcp: false
      eth0:
        address: x.x.211.37/24
        gateway: x.x.211.1
  resize_device: /dev/sda
  services:
    consul-agent:
      command:
      - agent
      - -config-dir
      - /etc/consul.d
      environment:
        SERVICE_IGNORE: "true"
      image: consul:0.8.3
      net: host
      restart: unless-stopped
      volumes:
      - consul-data:/consul/data
      - /opt/config.d/consul:/etc/consul.d
    dnsmasq:
      cap_add:
      - NET_ADMIN
      environment:
        SERVICE_IGNORE: "true"
      image: andyshinn/dnsmasq
      net: host
      restart: unless-stopped
      volumes:
      - /opt/config.d/dnsmasq/dnsmasq.conf:/etc/dnsmasq.conf
    rancher-agent-bootstrap:
      command: http://rancher-server.service.herzen:8080/v1/scripts/30CA2461049D36CCA99E:1483142400000:M1bGuanBVwQ14MAm61z9IHMkfLQ
      environment:
        CATTLE_HOST_LABELS: host=gateway
      image: rancher/agent:v1.2.2
      privileged: true
      volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /var/lib/rancher:/var/lib/rancher
    registrator:
      command:
      - consul://localhost:8500
      image: gliderlabs/registrator:master
      net: host
      restart: unless-stopped
      volumes:
      - /var/run/docker.sock:/tmp/docker.sock
  state:
    dev: LABEL=RANCHER_STATE
    wait: true
runcmd:
- - apt
  - update
- - apt
  - install
  - -y
  - python
- - ln
  - -sf
  - /usr/share/zoneinfo/Europe/Moscow
  - /etc/localtime
ssh_authorized_keys:
- xxx
- xxx
```
