### ISSUE TITLE
Can't upgrade when using proxy

### ISSUE THREAD

**Issue by rgruyters** [rancher/os#1914]
**RancherOS Version: (ros os version)**
```
$ sudo ros -v
ros version v1.0.2
```

**Where are you running RancherOS? (docker-machine, AWS, GCE, baremetal, etc.)**
VM

I have an issue when wanting to check if there is a newer version of the OS. Our systems are behind a proxy. I have configured the proxy settings under `rancher.network` (`http_proxy`, `https_proxy` and `no_proxy`) and works fine with Docker and system-docker, but not when I want to upgrade of listing the os with `ros os`.

```
> FATA[0015] Get https://releases.rancher.com/os/releases.yml?current=v1.0.2: dial tcp 104.24.17.51:443: i/o timeout
```

**Comment by SvenDowideit** [comment]
oh wow :(

I presume `ros os upgrade -i rancher/os:v1.0.2` works, but things like `ros os list` and `ros service list` or `ros engine list` don't?

**Comment by RockTheJib** [comment]
Hi,

I have the same problem
**RancherOS Version: (ros os version)**
```
sudo ros os version
v1.0.1
```

**Where are you running RancherOS? (docker-machine, AWS, GCE, baremetal, etc.)**
VM
```
sudo ros os upgrade
> FATA[0015] Get https://releases.rancher.com/os/releases.yml?current=v1.0.1: dial tcp 104.24.17.51:443: i/o timeout
```
my proxy config is as followed:
```
sudo ros config export
EXTRA_CMDLINE: /init
hostname: <hostname>
rancher:
  docker:
    extra_args:
    - --bip=<my_gateway/netmask>
  environment:
    EXTRA_CMDLINE: /init
  network:
    dns:
      nameservers:
      - <DNS1_ipaddress>
      - <DNS2_ipaddress>
      search:
      - <mydomain>
    http_proxy: <http://myproxy.mydomain:port>
    https_proxy: <https://myproxy.mydomain:port>
    interfaces:
      eth0:
        address: <ipaddress/netmask>
        dhcp: false
        gateway: <ipadress>
        mtu: 1500
    no_proxy: localhost,127.0.0.1,<mydomain>
```
It seems like system-docker would need http_proxy parameters
```
ps -ef|grep system-docker
    1 root     system-docker daemon --pidfile /var/run/system-docker.pid --log-opt max-file=2 --log-opt max-size=25m --graph /var/lib/system-docker --restart=false --storage-driver overlay --group root --host unix:///var/run/system-docker.sock --userland-proxy=false --config-file /etc/docker/system-docker.json --exec-root /var/run/system-docker
```
from http://rancher.com/docs/os/networking/proxy-settings/, it should work.

Thanks for your help
