### ISSUE TITLE
IPv6 default gateway not set, sometimes

### ISSUE THREAD

**Issue by robbertkl** [rancher/os#1975]
**RancherOS Version: (ros os version)**
v1.0.3

**Where are you running RancherOS? (docker-machine, AWS, GCE, baremetal, etc.)**
Cloud VPS (qemu)

I'm having a cloud-config like this:

```
rancher:
  network:
    interfaces:
      eth0:
        addresses:
          - xxx.xxx.xxx.xxx/24
          - xxxx:xxxx:xxxx:xxxx::xxxx/48
        gateway: xxx.xxx.xxx.xxx
        gateway_ipv6: xxxx:xxxx:xxxx:xxxx::xxxx
```

Unfortunately, the IPv6 default route is not always present after a reboot. Sometimes it is, sometimes it isn't.

Please note I just started running with kernel boot parameter `ipv6.autoconf=0`, which effectively turns off my link-local address on eth0, since I only want to use my manually set IPv6 address for outgoing traffic. I have to set this as a kernel boot parameter instead of `net.ipv6.conf...` sysctl, because RancherOS does not apply sysctls before initializing the network. However, this issue was already present before I started using `ipv6.autoconf=0`.
