### ISSUE TITLE
installing to disk and configuring with cloud-init is awkward.

### ISSUE THREAD

**Issue by rockandska** [rancher/os#2059]
**RancherOS Version: 1.1.0-rc3**

**Where are you running RancherOS? docker-machine + vsphere**

````
$ docker-machine --version
docker-machine version 0.12.2, build 9371605
````

With this cloud-config
````
#cloud-config
write_files:
  - path: /etc/rc.local
    permissions: "0755"
    owner: root
    content: |
      #!/bin/bash
      sudo rm -rf /var/lib/rancher/resizefs.done
rancher:
  resize_device: /dev/sda1
  sysctl:                                                                                                 
    net.ipv6.conf.all.disable_ipv6: 1
    net.ipv6.conf.default.disable_ipv6: 1
    net.ipv6.conf.lo.disable_ipv6: 1
    net.ipv4.ip_nonlocal_bind: 1
  bootstrap_docker:
    registry_mirror: "https://xxxx"
  docker:
    registry_mirror: "https://xxxx"
  system_docker:
    registry_mirror: "https://xxxx"
ssh_authorized_keys:
  - "ssh-rsa xxxx"
````
Everything is ok
````
$ docker-machine create --driver vmwarevsphere --vmwarevsphere-username=xxxx --vmwarevsphere-password=xxxx --vmwarevsphere-vcenter=xxxx --vmwarevsphere-hostsystem=xxxx --vmwarevsphere-disk-size="20000" --vmwarevsphere-cpu-count=6 --vmwarevsphere-memory-size=6144 --vmwarevsphere-datacenter="xxxx" --vmwarevsphere-network='xxxx' --vmwarevsphere-datastore='xxxx' --vmwarevsphere-cloudinit="https://xxxx/cloud-config.yml" --vmwarevsphere-boot2docker-url="https://github.com/rancher/os/releases/download/v1.1.0-rc3/rancheros.iso" tools-$(cat /proc/sys/kernel/random/uuid)
Running pre-create checks...
Creating machine...
(tools-0a89781f-d8bd-4404-b0e9-07714899ce74) Downloading /home/xxxx/.docker/machine/cache/boot2docker.iso from https://github.com/rancher/os/releases/download/v1.1.0-rc3/rancheros.iso...
(tools-0a89781f-d8bd-4404-b0e9-07714899ce74) 0%....10%....20%....30%....40%....50%....60%....70%....80%....90%....100%
(tools-0a89781f-d8bd-4404-b0e9-07714899ce74) Generating SSH Keypair...
(tools-0a89781f-d8bd-4404-b0e9-07714899ce74) Creating VM...
(tools-0a89781f-d8bd-4404-b0e9-07714899ce74) Uploading Boot2docker ISO ...
(tools-0a89781f-d8bd-4404-b0e9-07714899ce74) Reconfiguring VM...
(tools-0a89781f-d8bd-4404-b0e9-07714899ce74) setting guestinfo.cloud-init.data.url to https://xxxx/cloud-config.yml
(tools-0a89781f-d8bd-4404-b0e9-07714899ce74) 
(tools-0a89781f-d8bd-4404-b0e9-07714899ce74) Waiting for VMware Tools to come online...
(tools-0a89781f-d8bd-4404-b0e9-07714899ce74) Provisioning certs and ssh keys...
Waiting for machine to be running, this may take a few minutes...
Detecting operating system of created instance...
Waiting for SSH to be available...
Detecting the provisioner...
Provisioning with rancheros...
Copying certs to the local machine directory...
Copying certs to the remote machine...
Setting Docker configuration on the remote daemon...
Checking connection to Docker...
Docker is up and running!
To see how to connect your Docker Client to the Docker Engine running on this virtual machine, run: docker-machine env tools-0a89781f-d8bd-4404-b0e9-07714899ce74
````

But if we had the rancher-agent service....
````
#cloud-config
write_files:
  - path: /etc/rc.local
    permissions: "0755"
    owner: root
    content: |
      #!/bin/bash
      sudo rm -rf /var/lib/rancher/resizefs.done
rancher:
  services:
    rancher-agent1:
      image: rancher/agent:v1.2.2
      command: https://xxxx/v1/scripts/xxxx
      privileged: true
      volumes:
        - /var/run/docker.sock:/var/run/docker.sock
      environment:
        CATTLE_HOST_LABELS: type=tool
  resize_device: /dev/sda1
  sysctl:                                                                                                 
    net.ipv6.conf.all.disable_ipv6: 1
    net.ipv6.conf.default.disable_ipv6: 1
    net.ipv6.conf.lo.disable_ipv6: 1
    net.ipv4.ip_nonlocal_bind: 1
  bootstrap_docker:
    registry_mirror: "https://xxxx"
  docker:
    registry_mirror: "https://xxxx"
  system_docker:
    registry_mirror: "https://xxxx"
ssh_authorized_keys:
  - "ssh-rsa xxxx"
````
Strange things happen
````
$ docker-machine create --driver vmwarevsphere --vmwarevsphere-username=xxxx --vmwarevsphere-password=xxxx --vmwarevsphere-vcenter=xxxx --vmwarevsphere-hostsystem=xxxx --vmwarevsphere-disk-size="20000" --vmwarevsphere-cpu-count=6 --vmwarevsphere-memory-size=6144 --vmwarevsphere-datacenter="xxxx" --vmwarevsphere-network='xxxx' --vmwarevsphere-datastore='xxxx' --vmwarevsphere-cloudinit="https://xxxx/cloud-config.yml" --vmwarevsphere-boot2docker-url="https://github.com/rancher/os/releases/download/v1.1.0-rc3/rancheros.iso" tools-$(cat /proc/sys/kernel/random/uuid)
Running pre-create checks...
Creating machine...
(tools-f3f9ca4b-7d87-4420-97d6-4ac5f47b3c99) Downloading /home/xxxx/.docker/machine/cache/boot2docker.iso from https://github.com/rancher/os/releases/download/v1.1.0-rc3/rancheros.iso...
(tools-f3f9ca4b-7d87-4420-97d6-4ac5f47b3c99) 0%....10%....20%....30%....40%....50%....60%....70%....80%....90%....100%
(tools-f3f9ca4b-7d87-4420-97d6-4ac5f47b3c99) Generating SSH Keypair...
(tools-f3f9ca4b-7d87-4420-97d6-4ac5f47b3c99) Creating VM...
(tools-f3f9ca4b-7d87-4420-97d6-4ac5f47b3c99) Uploading Boot2docker ISO ...
(tools-f3f9ca4b-7d87-4420-97d6-4ac5f47b3c99) Reconfiguring VM...
(tools-f3f9ca4b-7d87-4420-97d6-4ac5f47b3c99) setting guestinfo.cloud-init.data.url to https://xxxx/cloud-config.yml
(tools-f3f9ca4b-7d87-4420-97d6-4ac5f47b3c99) 
(tools-f3f9ca4b-7d87-4420-97d6-4ac5f47b3c99) Waiting for VMware Tools to come online...
(tools-f3f9ca4b-7d87-4420-97d6-4ac5f47b3c99) Provisioning certs and ssh keys...
Waiting for machine to be running, this may take a few minutes...
Detecting operating system of created instance...
Waiting for SSH to be available...
Detecting the provisioner...
Provisioning with rancheros...
Error creating machine: Error running provisioning: ssh command error:
command : sed /127.0.1.1/d /etc/hosts > /tmp/hosts && cat /tmp/hosts | sudo tee /etc/hosts
err     : exit status 1
output  : sudo: tee: command not found

$ docker-machine ls
NAME                                         ACTIVE   DRIVER          STATE     URL                       SWARM   DOCKER        ERRORS
tools-0a89781f-d8bd-4404-b0e9-07714899ce74   -        vmwarevsphere   Running   tcp://172.16.24.70:2376           v17.03.1-ce   
tools-f3f9ca4b-7d87-4420-97d6-4ac5f47b3c99   -        vmwarevsphere   Running   tcp://172.16.28.70:2376           Unknown       Unable to query docker version: Cannot connect to the docker engine endpoint
````

Maybe related with #1750 
i didn't had this behaviour with the same cloud-config on v1.0.3 release and "sudo ros install -c cloud-config.yml -d /dev/sda" installation on disk
