### ISSUE TITLE
RancherOS 1.1 kernel panic - not syncing: Attempted to kill init

### ISSUE THREAD

**Issue by vchav73** [rancher/os#2116]
It will run fine once or twice then after a reboot I get kernel panics. I'm not able to recover. My provider is Profitbricks. I'm happy to try config changes if anyone has suggestions.

```
EXTRA_CMDLINE: /init
rancher:
  console: centos
  environment:
    EXTRA_CMDLINE: /init
  network:
    dns:
      nameservers:
      - 8.8.8.8
      - 8.8.4.4
    post_cmds:
    - ip route add default via 10.14.194.15
  services_include:
    kvm-vm-tools: true
  state:
    dev: LABEL=RANCHER_STATE
    wait: true
ssh_authorized_keys:
```

```
[root@analytics ~]# dmidecode -s system-product-name
Bochs
[root@analytics ~]# virt-what 
kvm
```

![image](https://user-images.githubusercontent.com/2886165/30671274-dc9a38ae-9e1a-11e7-8606-5ff810ea323e.png)
