### ISSUE TITLE
iPXE boot not always load cloud-init if there are more than one interace run dhcp

### ISSUE THREAD

**Issue by liyimeng** [rancher/os#2144]
**RancherOS Version: (ros os version)**
v.1.1.0
**Where are you running RancherOS? (docker-machine, AWS, GCE, baremetal, etc.)**

As suggested with Sven in https://github.com/rancher/os/issues/1790 I open this issue.

This happens If you have more than one interface on your machine. To reproduce, create a KVM VM with two interfaces, pxe boot from one of the interface. In case you also have another dhcp server running on another interface, it is almost 100% fails. 
I guess this is a timing issue, related to https://github.com/rancher/os/issues/2141

**Comment by strowi** [comment]
any news on this? Seems im running into the same problem..

**Comment by niusmallnan** [comment]
@strowi Can you show me your iPXE file? I'm working on this.

**Comment by strowi** [comment]
@niusmallnan here it is ;)

```
KERNEL boot/rancher-1.1.3-vmlinuz rancher.state.formatzero=true rancher.state.dev=LABEL=RANCHER_STATE rancher.state.autoformat=[/dev/sda] rancher.cloud_init.datasources=[url:http://10.10.0.10/rancher/cloud-config.yml] rancher.autologin=tty1 rancher.debug=true
INITRD boot/rancher-1.1.3-initrd
```

```
ssh_authorized_keys:
  - ssh-rsa ....

rancher:
  state:
    fstype: auto
    dev: LABEL=RANCHER_STATE
    autoformat:
    - /dev/sda
    formatzero: true

  sysctl:
    fs.inotify.max_user_watches: 16184
    net.ipv4.tcp_tw_reuse: 1

  console: ubuntu
```

But it might be related to a slow dhcp, the logfile dosn't show the dhcp-config, but the nameservers from google.
The request for the cloud-config.yml never reaches the webserver hosting it.
But after some time network is present.

**Comment by niusmallnan** [comment]
@strowi 
There is a workaround, if there are two NICs are open DHCP. There should be only one for IPXE boot. So can be configured like this.

IPXE file:
```
KERNEL boot/rancher-1.1.3-vmlinuz rancher.network.interfaces.eth0.dhcp=true rancher.state.formatzero=true rancher.state.dev=LABEL=RANCHER_STATE rancher.state.autoformat=[/dev/sda] rancher.cloud_init.datasources=[url:http://10.10.0.10/rancher/cloud-config.yml] rancher.autologin=tty1 rancher.debug=true
INITRD boot/rancher-1.1.3-initrd
```

Cloud-config:
```
ssh_authorized_keys:
  - ssh-rsa ....

rancher:
  state:
    fstype: auto
    dev: LABEL=RANCHER_STATE
    autoformat:
    - /dev/sda
    formatzero: true

  sysctl:
    fs.inotify.max_user_watches: 16184
    net.ipv4.tcp_tw_reuse: 1

  network:
    interfaces:
      eth0:
        dhcp: true
      eth1:
        dhcp: true

  console: ubuntu
```

It can work fine on my test setup.
