### ISSUE TITLE
Can't automount state disk

### ISSUE THREAD

**Issue by beatcracker** [rancher/os#2158]
* RancherOS Version: **v1.1.0**
* Where are you running RancherOS: **Hyper-V Gen1 VM**

### Target

To have a  Hyper-V VM with wich boots from official `rancheros.iso`, reads config from `config-2.iso` (`openstack\latest\user_data`) and automounts disk attached as `dev/sda`.

Autoformatting this disk would be great, but I can live with just automount.

### What I've tried:

All combinations of:

#### Pre-formatting state disk:

* `mkfs.ext4 -F -L RANCHER_STATE /dev/sda`
* `mkfs.ext4 -F -L B2D_STATE /dev/sda`
* `echo 'start=2048, type=83' | sudo sfdisk /dev/sda ; mkfs.ext4 -F -L RANCHER_STATE /dev/sda1`
* `echo 'start=2048, type=83' | sudo sfdisk /dev/sda ; mkfs.ext4 -F -L B2D_STATE /dev/sda1`

#### Cloud-config

* No `state` config

* `LABEL=RANCHER_STATE`

```yaml
rancher:
  state:
    fstype: auto
    dev: LABEL=RANCHER_STATE
```

* `LABEL=B2D_STATE`

```yaml
rancher:
  state:
    fstype: auto
    dev: LABEL=B2D_STATE
```

### Results

Disk is not mounted, no matter what I do.
