### ISSUE TITLE
rebooting ros from a priviledged container results in host lock up

### ISSUE THREAD

**Issue by aemneina** [rancher/os#2164]
**RancherOS Version: (ros os version)**
ROS 1.1

**Where are you running RancherOS? (docker-machine, AWS, GCE, baremetal, etc.)**
VM

container config launched using system-docker:

```
image: alpine:3.6 # or something alpine-like
volumes_from:
  - all-volumes
privileged: true
net: host
pid: host
uts: host
ipc: host
```

attempt to reboot using that container causes kernel panic.

**Comment by niusmallnan** [comment]
Add more details:

#### Add `alpine-test.yml` to `/var/lib/rancher/conf`:
```
cat /var/lib/rancher/conf/alpine-test.yml
alpine-test:
  image: alpine:3.6 # or something alpine-like
  command: /bin/sh
  volumes_from:
    - all-volumes
  privileged: true
  net: host
  pid: host
  uts: host
  ipc: host
  stdin_open: true
  tty: true
  labels:
    io.rancher.os.scope: system
    io.rancher.os.detach: "true"
```

#### Enable this system service:
```
ros service enable /var/lib/rancher/conf/alpine-test.yml
ros service up alpine-test
```

#### Check this service
```
system-docker ps
76ea4b3ca673        alpine:3.6                         "/bin/sh"                11 minutes ago      Up 14 hours                             alpine-test
6ef74c611212        rancher/os-console:dfb8a32         "/usr/bin/ros entrypo"   14 hours ago        Up 14 hours                             console
03bcfbfbc3ca        rancher/os-docker:17.06.2          "ros user-docker"        18 hours ago        Up 8 minutes                            docker
...
...
```

### Try to reboot in `alpine-test`:
```
system-docker exec -it alpine-test sh
/ # reboot
```
