### ISSUE TITLE
logrotate

### ISSUE THREAD

**Issue by daiyam** [rancher/os#2174]
**RancherOS Version: (ros os version)**
v1.1.0
**Where are you running RancherOS? (docker-machine, AWS, GCE, baremetal, etc.)**
docker-machine & vultr

Hello,

I would like to activate logrotate and I was wondering how...

Can I add the following config to `ros config`?

```
rancher:
  services:
    logrotate:
      image: os-logrotate:v1.1.0
      command: /usr/sbin/logrotate -v /etc/logrotate.conf
      labels:
        io.rancher.os.createonly: "true"
        io.rancher.os.scope: system
        io.rancher.os.before: system-cron
        cron.schedule: "@hourly"
      uts: host
      net: none
      privileged: true
      volumes_from:
      - command-volumes
      - system-volumes
```
(from `https://github.com/rancher/os/blob/master/os-config.tpl.yml`)

Thx
Daiyam

**Comment by niusmallnan** [comment]
Hi @daiyam ,
Maybe this link will be helpful: https://rancher.com/docs/os/v1.1/en/system-services/custom-system-services/#service-log-rotation

**Comment by daiyam** [comment]
Hi @niusmallnan,

From what I understand, that documentation is to include `logrotate` into an user container.

I'm trying to have `logrotate` working on the logs of rancheros's system container.

**Comment by daiyam** [comment]
I've tried `sudo ros config merge -i my_config.yml` with `my_config.yml` as
```
rancher:
  services:
    logrotate:
      image: os-logrotate:v1.1.0
      command: /usr/sbin/logrotate -v /etc/logrotate.conf
      labels:
        io.rancher.os.createonly: "true"
        io.rancher.os.scope: system
        io.rancher.os.before: system-cron
        cron.schedule: "@hourly"
      uts: host
      net: none
      privileged: true
      volumes_from:
      - command-volumes
      - system-volumes
```
or with `image: rancher/os-logrotate:v1.1.0`

I've also tried `sudo ros s enable https://gist.githubusercontent.com/daiyam/6e036becb9b60abb29a00e5a46c20770/raw/40a80e0dd748b243046f72c99466910aca416dec/logrotate.yml`.

None of my tests have worked :(
