### ISSUE TITLE
RancherOS not persisting user volume

### ISSUE THREAD

**Issue by zeppelinux** [rancher/os#2188]
**RancherOS Version: (ros os version)**
1.1.1
**Where are you running RancherOS? (docker-machine, AWS, GCE, baremetal, etc.)**
Baremetal

I reported the issue initially for rke:

https://github.com/rancher/rke/issues/178

But it seems like there is some issue with the RancherOS not persisting the user volumes i.e. 

$sudo ros config export
```
rancher:
  environment:
    EXTRA_CMDLINE: /init
  services:
    user-volumes:
      volumes:
      - /home:/home
      - /opt:/opt
      - /var/lib/kubelet:/var/lib/kubelet
      - /etc/kubernetes:/etc/kubernetes
```

$ ls -la /etc/kubernetes/
total 12
drwxr-xr-x    3 root     root          4096 Dec 21 23:54 .
drwxr-xr-x    1 root     root          4096 Dec 21 23:52 ..
drwxr-xr-x    2 root     root          4096 Dec 21 23:54 ssl
[rancher@kub2 ~]$ 

$sudo reboot

/etc/kubernetes is empty
