### ISSUE TITLE
docker ignore registry-mirror settings

### ISSUE THREAD

**Issue by hdep** [rancher/os#2195]
**RancherOS Version: (ros os version)**
v1.1.2
**Where are you running RancherOS? (docker-machine, AWS, GCE, baremetal, etc.)**
Vmware 

I have a nexus OSS registry proxy (with auth) for docker hub working fine in command line i.e : 
docker search docker-public.recette.local/debian

I want to use this proxy with rancheros so I use this cloud-config.yml : 
```
rancher:
  services_include:
    open-vm-tools: true
  docker:
    registry_mirror: "https://docker-public.recette.local"
  system_docker:
    registry_mirror: "https://docker-public.recette.local"
  registry_auths:
    https://docker-public.recette.local:
      auth: aaaa=="  
    https://docker-internal.recette.local:
      auth:  aaaa=="    
```
and  

```
write_files:
  - path: /etc/docker/certs.d/docker-public.recette.local/ca.crt
    permissions: "0644"
    owner: root
    content: |

 - path: /etc/docker/certs.d/docker-internal.recette.local/ca.crt
    permissions: "0644"
    owner: root
    content: |
```

After install docker isn't able to pull any image because it doesn't use my registry : 

```
$ sudo docker search debian
Error response from daemon: Get https://index.docker.io/v1/search?q=debian&n=25: dial tcp 54.236.81.192:443: i/o timeout

```

Docker daemon is loaded with the proper options  : 

```
rancher@ra-web-rancheros1 ~]$ ps aux | grep docker
    1 root     system-docker daemon --log-opt max-size=25m --log-opt max-file=2 --registry-mirror https://docker-public.recette.local --config-file /etc/docker/system-docker.json --restart=false --exec-root /var/run/system-docker --pidfile /var/run/system-docker.pid --storage-driver overlay --group root --host unix:///var/run/system-docker.sock --graph /var/lib/system-docker --userland-proxy=false
 1075 root     {ros} docker-runc exec -- 8e68a9d75876a364580b7804661aeb34d1e9181aa784823679f566c6ebfee55c env PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin HOSTNAME=ra-web-rancheros1 HOME=/ ros docker-init daemon --host unix:///var/run/docker.sock --storage-driver overlay --registry-mirror https://docker-public.recette.local --log-opt max-file=2 --log-opt max-size=25m --group docker
 1245 root     dockerd --host unix:///var/run/docker.sock --storage-driver overlay --registry-mirror https://docker-public.recette.local --log-opt max-file=2 --log-opt max-size=25m --group docker
 1267 root     docker-containerd -l unix:///var/run/docker/libcontainerd/docker-containerd.sock --metrics-interval=0 --start-timeout 2m --state-dir /var/run/docker/libcontainerd/containerd --shim docker-containerd-shim --runtime docker-runc
 1374 rancher  grep docker
```
