### ISSUE TITLE
Baremetal install error

### ISSUE THREAD

**Issue by benpye** [rancher/os#2221]
**RancherOS Version: (ros os version)**
`Installing from rancher/os:v1.1.3`

**Where are you running RancherOS? (docker-machine, AWS, GCE, baremetal, etc.)**
Bare metal on a Gen 8 HP Microserver.

I am attempting to install onto a USB drive connected to the microserver. I have an SSD for the state partition and 4 HDDs for a ZFS pool. When attempting to install I run into the following error:

```
[rancher@rancher ~]$ sudo ros install -c cloud-config.yml -d /dev/sdf -k --debug
INFO[0000] No install type specified...defaulting to generic /dev/sdf -k --debug
Installing from rancher/os:v1.1.3
Continue [y/N]: y
INFO[0001] start !isoinstallerloaded
DEBU[0002] mount (&exec.Cmd{Path:"/bin/mount", Args:[]string{"mount", "-t", "iso9660", "/dev/sr0", "/bootiso"}, Env:[]string(nil), Dir:"", Stdin:io.Reader(nil), Stdout:io.Writer(nil), Stderr:io.Writer(nil), ExtraFiles:[]*os.File(nil), SysProcAttr:(*syscall.SysProcAttr)(nil), Process:(*os.Process)(nil), ProcessState:(*os.ProcessState)(nil), ctx:context.Context(nil), lookPathErr:error(nil), finished:false, childFiles:[]*os.File(nil), closeAfterStart:[]io.Closer(nil), closeAfterWait:[]io.Closer(nil), goroutine:[]func() error(nil), errch:(chan error)(nil), waitDone:(chan struct {})(nil)})
DEBU[0002] Mounted /dev/sr0
INFO[0002] trying to load /bootiso/rancheros/installer.tar.gz
INFO[0009] Loaded images from /bootiso/rancheros/installer.tar.gz
INFO[0009] starting installer container for rancher/os-installer:latest (new)
DEBU[0009] Run(&{/bin/system-docker [system-docker run --rm --net=host --privileged -v /:/host --volumes-from=all-volumes rancher/os-installer:latest -t generic -d /dev/sdf -i rancher/os-installer:latest -f --no-reboot -c /opt/user_config.yml --isoinstallerloaded=1 --kexec --debug] []  <nil> <nil> <nil> [] <nil> <nil> <nil> <nil> <nil> false [] [] [] [] <nil> <nil>})
Installing from rancher/os-installer:latest
mount: /bootiso: WARNING: device write-protected, mounted read-only.
mke2fs 1.43.7 (16-Oct-2017)
Creating filesystem with 7545600 4k blocks and 7547232 inodes
Filesystem UUID: 793bed0e-6c41-43f2-b78d-9939b68c350f
Superblock backups stored on blocks:
        32768, 98304, 163840, 229376, 294912, 819200, 884736, 1605632, 2654208,
        4096000

Allocating group tables: done
Writing inode tables: done
Creating journal (32768 blocks): done
Writing superblocks and filesystem accounting information: done

time="2018-01-12T20:07:27Z" level=error msg="mountdevice exit status 1"
time="2018-01-12T20:07:27Z" level=error msg="formatAndMount exit status 1"
time="2018-01-12T20:07:27Z" level=error msg="error layDownOS exit status 1"
time="2018-01-12T20:07:27Z" level=fatal msg="Failed to run install" err="exit status 1"
FATA[0026] Failed to run install                         err="exit status 1"
```

My cloud-config.yml:
```
#cloud-config
ssh_authorized_keys:
  - ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDU7W3aX/Crbp4bKNRNZWRYaxgpH6tsjt88l6jspdlHToMz6Vvq4NU7CHwXNBijO0LTh7wxeKT3E5DZkPepE9gv7vRIrSX5NLHlLLAibC6iogF70SGqLeyEUXh70tMa+ZxU6wow5VcGxZ0RBXsuunKFhGqatveRaw6CbIYceLvnJvUBcsw0M3tr6EtyuTQ2p8BFoZNnYX+4Aj3HAz/uuwjUcgz3ri+Ot+yJKjkS2dV/aKCznQhvS3sX8Fio3eBI7XBm8oc5O1jI37y4Tckq/mnQORiTaKTvkbZmRojPgk7EdjACJJPVfk2mCnl/zcShQDyzOz5BhUOCvOObeJWseBp3 cardno:000604547692
rancher:
  state:
    fstype: auto
    dev: UUID="7dfd66de-df39-49f2-bbd6-dded3939e570"
```

I have also seen this error in the forum: https://forums.rancher.com/t/weird-bare-metal-install-error/6392
