### ISSUE TITLE
Autoformat hangs indefinitely

### ISSUE THREAD

**Issue by strowi** [rancher/os#2226]
**RancherOS Version: 1.1.3**

**Where are you running RancherOS? bare-metal **

Hi,

running pxe/baremetal/autoformat:

```
KERNEL boot/rancher-1.1.3-vmlinuz rancher.state.formatzero=true rancher.state.dev=LABEL=RANCHER_STATE rancher.state.autoformat=[/dev/sda] rancher.cloud_init.datasources=[url:http://10.10.0.10/rancher/cloud-config.yml] rancher.autologin=tty1 rancher.debug=true
INITRD boot/rancher-1.1.3-initrd
```

```
ssh_authorized_keys:
  - ssh-rsa ....

rancher:
  state:
    fstype: auto
    dev: LABEL=RANCHER_STATE
    autoformat:
    - /dev/sda
    formatzero: true

  sysctl:
    fs.inotify.max_user_watches: 16184
    net.ipv4.tcp_tw_reuse: 1

  console: ubuntu
```

it seemts autoformat hangs on boot with a 3TB/Megaraid/RAID5 setup.
Last lines via remote console show 
```
...
bootstrap_1 | ros-bootstrap:info: bootstrap_container: Autoformat([/dev/sda]) as ext4
```

But then seems to hang indefinitely.

regards,
Roman
