### ISSUE TITLE
VMware ESXi 6.5 - No Network During Boot

### ISSUE THREAD

**Issue by bt** [rancher/os#2261]
**RancherOS Version**
v1.2.0

**Where are you running RancherOS? (docker-machine, AWS, GCE, baremetal, etc.)**
VMware ESXi 6.5

I'm not sure if I'm configuring this incorrectly (first time using Rancher) but basically what I'm doing is this:

1. Downloaded the ISO for RancherOS from GitHub releases.
2. Uploaded into a datastore on my ESXi server.
3. Created VM in ESXi with 8 vCPU, 8GB RAM, 120GB Disk, CDROM set to load the ISO.
4. Booted into the Rancher ISO, created a `cloud-config.yml` file with the following contents:

```yaml
#cloud-config
ssh_authorized_keys:
    - ssh-rsa AAAAB3NzaC

rancher:
    network:
        interfaces:
            eth*:
                dhcp: false
            eth0:
                address: 10.10.10.20/24
                gateway: 10.10.10.254
        dns:
            nameservers:
                - 10.10.10.254
```
Note that at this point, there's DHCP on my network and the OS detects ESXi, causing it to pull `open-vm-tools` container down from `docker.io`.

5. Install the OS to disk using command `sudo ros install -c cloud-config.yml -d /dev/sda`.
6. Reboot, and on reboot, it fails to connect to `docker.io` to pull down `open-vm-tools`; it seems like there's no internet connectivity during the bootup. However, afterwards, I can SSH to the static IP `10.10.10.20` using my private key, `wget docker.io` works, `ping` works....

I can't seem to find any information on this issue. Is it something to do with my configuration?
