### ISSUE TITLE
write_files into rancher home dir changes permissions to root:root

### ISSUE THREAD

**Issue by ryansch** [rancher/os#2264]
**RancherOS Version: (ros os version)**
v1.2.0
**Where are you running RancherOS? (docker-machine, AWS, GCE, baremetal, etc.)**
AWS

- Follow the instructions here: http://rancher.com/docs/os/v1.2/en/configuration/private-registries/#docker-client-authentication
- Observe that /home/rancher is owned by root:root on boot

We didn't observe this behaviour with `write_files` on 1.1.x.

**Comment by niusmallnan** [comment]
You can change the `owner` you want
```
write_files:
  - path: /home/rancher/config.json
    permissions: "0755"
    owner: "rancher:rancher"
    content: |
      test
```
