### ISSUE TITLE
Extend Disk Size in RancherOS for AWS instances

### ISSUE THREAD

**Issue by bscott** [rancher/os#232]
Hello,

I started my RancherOS AMI's with 500GB Disk's but RancherOS only see's 7GB, how can I extend the disk?

**Comment by ibuildthecloud** [comment]
Try

    docker run --privileged --rm -it debian:jessie resize2fs /dev/xvda1

Change xvda1 to the right disk for your setup.  We should create a system service to do this automatically on boot in AWS

**Comment by hibooboo2** [comment]
+1

**Comment by bscott** [comment]
rancher@ip-172-30-0-54:~$ docker run --privileged --rm -it debian:jessie resize2fs /dev/xvda1
resize2fs 1.42.12 (29-Aug-2014)
The filesystem is already 2094474 (4k) blocks long.  Nothing to do!

**Comment by ibuildthecloud** [comment]
Hmmm.... Is the PV or HVM?

**Comment by bscott** [comment]
HVM

**Comment by kupo24z** [comment]
I'm having the same issue with a generic image on KVM/OpenStack, is it possible to mimic cloud-init's grow partition feature?

**Comment by dnegstad** [comment]
I had to rebuild the partition table and reboot (http://docs.aws.amazon.com/AWSEC2/latest/UserGuide/storage_expand_partition.html) to be able to run resize2fs properly. The /dev/xvda1 partition is set to 8GB out of the box. Easiest thing to do in the short term is probably launch a fresh instance of rancher os, do the necessary partition resizing, and then take a new snapshot to use instead of the community version.

**Comment by dnegstad** [comment]
[This forum post](https://forums.aws.amazon.com/thread.jspa?messageID=539484) is probably the best example of how to do the partition resize without needing to unmount your root partition.

**Comment by ibuildthecloud** [comment]
@bscott We need to fix this.  So if you run PV you can just do `docker run --rm --privileged -it debian resize2fs /dev/xvda1` but HVM has a real partition table so resizing requires you to resize the partition first and then reboot.

We will look at building this resize logic into RancherOS (or simple system service that can be loaded at boot).  CoreOS does a similar thing in that they always extend their root partition on boot.

**Comment by ibuildthecloud** [comment]
@bscott I got it working with no reboot needed.

@kupo24z Thanks for pointing me to cloud-init.  The following little script works.  We will try to make a more official one.

```bash
docker run --privileged -i --rm ubuntu bash << EOF
apt-get update
apt-get install -y cloud-guest-utils parted
growpart /dev/xvda 1
partprobe
resize2fs /dev/xvda1
EOF
```

**Comment by imikushin** [comment]
As of v0.4.1, RancherOS AWS instance disks are resized to full size on first boot. 

The implementation relies on a magic constant (start of the state partition) and is known to work on AWS. This concern is addressed by rancher/os-images#38

**Comment by 2devnull** [comment]
@imikushin - how can I get this to work on non AWS? Using ESXi.

**Comment by imikushin** [comment]
@2devnull Can you try putting the following into your cloud-config?
```
#cloud-config
rancher:
  environment:
    RESIZE_DEV: /dev/your-disk
  services_include:
    resize-fs: true
    amazon-ecs-agent: true
```
Replace `/dev/your-disk` with the device with RancherOS state partition you want to resize to the full disk capacity.

**Comment by 2devnull** [comment]
@imikushin - That didn't work. I used the: "ros c merge" command to add what you stated. After that, /var/lib/rancher/conf/cloud-config.yml looks like this:

```
rancher:
  environment:
    RESIZE_DEV: /dev/sda1
  services_include:
    resize-fs: true
    ubuntu-console: true
```

I then added 2 GB to the VM, but once rancherOS booted, the disk was not expanded. Unfortunately, I cannot scroll back in the ESXi console to see the messages when it was booting this VM. Is there somewhere where the boot messages are kept?

**Comment by imikushin** [comment]
@2devnull Shoot! This is for v0.4.2-dev. Can you try `https://raw.githubusercontent.com/rancher/os-services/v0.4.2-dev/r/resize-fs.yml` instead of `resize-fs`?

**Comment by imikushin** [comment]
@2devnull Just use the disk device in RESIZE_DEV: `/dev/sda`

So, on v0.4.1 your cloud-config should look like
```
rancher:
  environment:
    RESIZE_DEV: /dev/sda
  services_include:
    https://raw.githubusercontent.com/rancher/os-services/v0.4.2-dev/r/resize-fs.yml: true
    ubuntu-console: true
```
