### ISSUE TITLE
if config file is specified for ros install, need to validate it before proceeding with installation

### ISSUE THREAD

**Issue by leodotcloud** [rancher/os#2338]
Steps:
- Create VM
- Boot VM with rancheros.iso
- This brings up a shell with Rancher OS
- Create `/tmp/c.yaml` with the following content:
```rancher:
  password: rancher
  network:
    interfaces:
      eth0:
        address: 1.1.1.2/29
        gateway: 1.1.1.1
        dhcp: false```
- Then I run `sudo ros install -c /tmp/c.yaml -d /dev/sda`
- I see the install succeed after answering `y` for a couple of questions.
- Upon reboot, I got a login prompt and when I try to login with `rancher:rancher` or `root:rancher`, unable to login.

I see the following error message:
```Failed to parse config file /var/lib/rancher/config/cloud-config.d/user_config.yml: yaml: []mapping values are not allowed in this context at line 3, column 16.```

This is very difficult to debug and highly inconvenient for a new user trying out Rancher OS.

**Comment by wchao1241** [comment]
1. Please note the format of the yaml file
```
#cloud-config
rancher:
  network:
    interfaces:
      eth0:
        address: 1.1.1.2/29
        gateway: 1.1.1.1
        dhcp: false
ssh_authorized_keys: []
```
Also you can first verify the your config file by `ros config validate -i xx.yaml`

2. `rancher.password` is a kernel parameter, setting in config is not valid. You can set it using the `--append` parameter:
```
$ sudo ros install -c /tmp/c.yaml -d /dev/sda --append "rancher.password=rancher"
```
