### ISSUE TITLE
bond0 slave interface strangeness

### ISSUE THREAD

**Issue by tahoward** [rancher/os#2343]
**RancherOS Version: (ros os version)**
v1.3.0
**Where are you running RancherOS? (docker-machine, AWS, GCE, baremetal, etc.)**
baremetal

Can not deploy a working network configuration if primary interface is `bond0`:
```
rancher:
  network:
    dns:
      nameservers:
        - 192.168.0.1
    interfaces:
      "mac=0C:C4:7A:54:68:34":
        bond: bond0
      "mac=0C:C4:7A:54:68:35":
        bond: bond0
      "mac=00:1B:21:B9:3B:FC":
        address: 10.0.0.2/30
      bond0:
        dhcp: false
        address: 192.168.0.6/24
        gateway: 192.168.0.1
        bond_opts:
          lacp_rate: 1
          miimon: 100
          mode: 4
```

This results in the above configuration being deployed, however, `"mac=0C:C4:7A:54:68:34"` gets deployed as both a slave to `bond0` and as a primary interface with DHCP enabled; both under `eth0`. This leaves the host without a working network connection unless I go in via console and bring `eth0` down. Once `eth0` is down network is up but `bond0` gets only one active link.

To further add to the confusion both `eth0` and `eth1` are shown to be running under the same `0C:C4:7A:54:68:34` mac address from `ifconfig` output. However, `/proc/net/bonding/bond0` shows `eth1` mac address as `0C:C4:7A:54:68:35`.

**Comment by janeczku** [comment]
https://github.com/rancher/os/issues/1994

**Comment by niusmallnan** [comment]
During the bootup process, ROS needs to run cloud-init. It automatically detects the data sources of cloud-init, but some data sources require a network connection. So in cloud-init, we open `rancher.network.interfaces.eth*.dhcp=true` by default. 

When you use iPXE mode, you have disabled DHCP in cloud-config. Not sure your cloud-config is loaded by which data source, If it depends on the network, there will still default to DHCP during the initial phase of cloud-init. After the cloud-init is completed, the cloud-config is actually loaded.

A better way is to set up a NIC specifically for cloud-init connections, e.g. eth0.
```
KERNEL boot/rancher-xxx-vmlinuz  rancher.network.interfaces.eth0.dhcp=true
```
In this way, ROS will not open DHCP for all networks in cloud-init.

Or you can configure all your network information in the kernel parameters, this will be very unfriendly because you can't express it with YAML.

If you use`ros install` to install the cloud-config to the disk, and already contains the configuration of the NIC. I believe there will be no problem, because cloud-config is pre-written on the local disk, ROS will not enable DHCP for all NICs.

**Comment by niusmallnan** [comment]
@strowi Sorry to make a mistake, can you try my latest comment.

**Comment by strowi** [comment]
@niusmallnan: you mean adding 'rancher.network.interfaces.eth*.dhcp=false' to boot parameters? will do when i get back to testing. Just do be clear, those syslinux-paramters need to be added manually right (eg: there is no option in cloud-init?)

**Comment by strowi** [comment]
Seems i found a workaround.. The following will run normal dhcp on single interface, and then flush all eth* interfaces before bringing up the bond:

```
    interfaces:
      bond0:
        pre_up:
          - /usr/bin/deconfig_interfaces_eth.sh
        addresses:
          - 192.168.122.11/24
        gateway: 192.168.122.1

        bond_opts:
          downdelay: "200"
          # lacp_rate: "1"
          miimon: "100"
          mode: "2"
          updelay: "200"
          xmit_hash_policy: layer3+4
        # post_up:
        # - ip route add 10.0.0.0/8 via 10.88.23.128
      'eth1':
        dhcp: false
        bond: bond0
      'eth2':
        dhcp: false
        bond: bond0

write_files:
  - path: /usr/bin/deconfig_interfaces_eth.sh
    permissions: "0755"
    owner: root
    content: |
      #!/bin/bash

      for if in $(ls /sys/class/net); do
        [[ $if == eth* ]] && ip addr flush dev $if
      done
```
its a bit hacky, but it seems to work...
Thx again for your help!
