### ISSUE TITLE
Autoformat provided by vmware guestinfo cloud-init.config.data has no effect

### ISSUE THREAD

**Issue by stffabi** [rancher/os#2354]
**RancherOS Version: (ros os version)**
1.3.0

**Where are you running RancherOS? (docker-machine, AWS, GCE, baremetal, etc.)**

Using the iso on an ESXI server.

Currently it's impossible to provide the "autoformat" settings through a `cloud-init.config.data` as described [here](https://rancher.com/docs/os/v1.1/en/running-rancheros/cloud/vmware-esxi/).

Booting the ISO and providing the following cloud-init through the guestinfo has no effect and neither `sda`gets formatted nor mounted.

```
#cloud-config
rancher:
  state:
    fstype: auto
    dev: LABEL=RANCHER_STATE
    autoformat:
      - /dev/sda
```

The problem is that ["mount and bootstrap"](https://github.com/rancher/os/blob/5de9b00fc823c6c9e28826e4bf38db000d098389/init/init.go#L320) is called before the different cloud-init providers get evaluated and have the chance to retrieve the cloud-init configs.

PR #2353 should fix this problem.
