### ISSUE TITLE
Formatting disk

### ISSUE THREAD

**Issue by drpebcak** [rancher/os#2381]
**RancherOS Version: (ros os version)**
v1.4.0

**Where are you running RancherOS? (docker-machine, AWS, GCE, baremetal, etc.)**
AWS

I am attempting to use cloud-config to format and mount the ephemeral instance store in a new m5d instance:

```
#cloud-config
bootcmd:
  - [ mkfs.ext2, /dev/nvme1n1 ]
mounts:
  - [ /dev/nvme1n1, /storage, ext2, "" ]
rancher:
  docker:
    extra_args:
      - "-g"
      - /storage
```

When the instance starts up, `/storage` exists, and user-docker has put its state there. However, `nvme1n1` is not formatted, and there is no mount on `/storage`

Any ideas? I have been unable to find any logs or errors that show what is happening during the bootstrap.
