### ISSUE TITLE
Run service with custom docker image tag specified at boot

### ISSUE THREAD

**Issue by adrianharabula** [rancher/os#2400]
**RancherOS Version: (ros os version)**
1.4.0

**Where are you running RancherOS? (docker-machine, AWS, GCE, baremetal, etc.)**
baremetal

Consider the following cloud-init.yml:
```
#cloud-config
rancher:
  services: 
    gitlab:
      image: gitlab/gitlab-ee:latest
      restart: always
```
It is passed as a kernel parameter with `rancher.cloud_init.datasources=[url:http://some_ip/gitlab.yml]`

Is there a possibility to launch a specific gitlab version instance without modifiying cloud-config? Something like using a variable for `image`:
```
#cloud-config
rancher:
  services: 
    gitlab:
      image: gitlab/gitlab-ee:$CUSTOM_TAG_SPECIFIED_AT_BOOT_HERE
      restart: always
```

All I am thinking right now is to statically generate lots of cloud-init files with tags needed. But seems overkill.
