### ISSUE TITLE
built docker image fails

### ISSUE THREAD

**Issue by daozhu** [rancher/os#2430]
**RancherOS Version: (v1.4.0)**

**Where are you running RancherOS? (PI 3B)**

----
built the aarch64 version image fails

the detail is here [built docker image fails](https://github.com/gogs/gogs/issues/5360)

i have  no idea about that

**Comment by niusmallnan** [comment]
Did you try this?
https://rancher.com/docs/os/v1.x/en/installation/running-rancheros/server/raspberry-pi/

**Comment by daozhu** [comment]
yes, i did it

here is the **ros config**
```
mounts:
- - /dev/mmcblk0p3
  - /mnt/docker
  - ext4
  - ""
rancher:
  cloud_init:
    datasources:
    - configdrive:/media/config-2
  console: debian
  docker:
    extra_args:
    - -g
    - /mnt/docker
  environment:
    EXTRA_CMDLINE: /init
```
