### ISSUE TITLE
Remove /var/lib/kubelet from user-volumes

### ISSUE THREAD

**Issue by niusmallnan** [rancher/os#2444]
As we recommend using RKE to deploy K8s on RancherOS, the legacy volume `/var/lib/kubelet` is meaningless. I will remove it.
```
    user-volumes:
      image: {{.OS_REPO}}/os-base:{{.VERSION}}{{.SUFFIX}}
      command: echo
      labels:
        io.rancher.os.createonly: "true"
        io.rancher.os.scope: system
      log_driver: json-file
      net: none
      privileged: true
      read_only: true
      volumes:
      - /home:/home
      - /opt:/opt
      - /var/lib/kubelet:/var/lib/kubelet
```
