### ISSUE TITLE
Non-Unique iSCSI Initiator Names Causes Excessive Errors in /var/log/messages

### ISSUE THREAD

**Issue by eyespies** [rancher/os#2446]
**RancherOS Version: (ros os version)**
```
[root@kw01 ~]# ros os version
v1.4.0
```

**Where are you running RancherOS? (docker-machine, AWS, GCE, baremetal, etc.)**
KVM guest, running three instances, two on one KVM host and one on the second KVM host.

## TLDR;
I setup iSCSI and it seems to work but outputs a lot of errors in the logs on the Rancher OS hosts. The errors indicate that all of the Rancher OS nodes (I run three) are using the same iSCSI initiator name to connect to the iSCSI target. Is there a step I'm missing to configure the iSCSI initiator name so it is different on each Rancher OS host?

## Long Story:
After setting up iSCSI, the system works, mostly, but I have a large number of errors in `/var/log/messages`:

```
[root@kw01 ~]# !tail
tail /var/log/messages 
Aug 14 18:37:46 kw01 iscsid: Kernel reported iSCSI connection 1:0 error (1020 - ISCSI_ERR_TCP_CONN_CLOSE: TCP connection closed) state (3)
Aug 14 18:37:48 kw01 iscsid: connection1:0 is operational after recovery (1 attempts)
Aug 14 18:37:48 kw01 kernel: [  855.971272]  connection1:0: detected conn error (1020)
Aug 14 18:37:49 kw01 iscsid: Kernel reported iSCSI connection 1:0 error (1020 - ISCSI_ERR_TCP_CONN_CLOSE: TCP connection closed) state (3)
Aug 14 18:37:51 kw01 iscsid: connection1:0 is operational after recovery (1 attempts)
Aug 14 18:37:51 kw01 kernel: [  858.971658]  connection1:0: detected conn error (1020)
Aug 14 18:37:52 kw01 iscsid: Kernel reported iSCSI connection 1:0 error (1020 - ISCSI_ERR_TCP_CONN_CLOSE: TCP connection closed) state (3)
Aug 14 18:37:54 kw01 iscsid: connection1:0 is operational after recovery (1 attempts)
Aug 14 18:37:54 kw01 kernel: [  861.975916]  connection1:0: detected conn error (1020)
Aug 14 18:37:55 kw01 iscsid: Kernel reported iSCSI connection 1:0 error (1020 - ISCSI_ERR_TCP_CONN_CLOSE: TCP connection closed) state (3)
```

The cluster generally works, but as this is just being setup for a sandbox, there is not yet any load. I have noticed that running `fdisk -l` displays this output for the KVM attached disk quickly:

```
[root@kw01 ~]# fdisk -l
Disk /dev/vda: 40 GiB, 42949672960 bytes, 83886080 sectors
Units: sectors of 1 * 512 = 512 bytes
Sector size (logical/physical): 512 bytes / 512 bytes
I/O size (minimum/optimal): 512 bytes / 512 bytes
Disklabel type: dos
Disk identifier: 0xa0d02ac9

Device     Boot Start      End  Sectors Size Id Type
/dev/vda1  *     2048 83884031 83881984  40G 83 Linux
``` 

but then the system pauses for 2-3 seconds and resumes by outputting:
```


Disk /dev/sda: 5 GiB, 5368709120 bytes, 10485760 sectors
Units: sectors of 1 * 512 = 512 bytes
Sector size (logical/physical): 512 bytes / 512 bytes
I/O size (minimum/optimal): 512 bytes / 262144 bytes


Disk /dev/sdb: 5 GiB, 5368709120 bytes, 10485760 sectors
Units: sectors of 1 * 512 = 512 bytes
Sector size (logical/physical): 512 bytes / 512 bytes
I/O size (minimum/optimal): 512 bytes / 262144 bytes


Disk /dev/sdc: 34 GiB, 36507222016 bytes, 71303168 sectors
Units: sectors of 1 * 512 = 512 bytes
Sector size (logical/physical): 512 bytes / 512 bytes
I/O size (minimum/optimal): 512 bytes / 262144 bytes


Disk /dev/sdd: 5 GiB, 5368709120 bytes, 10485760 sectors
Units: sectors of 1 * 512 = 512 bytes
Sector size (logical/physical): 512 bytes / 512 bytes
I/O size (minimum/optimal): 512 bytes / 262144 bytes
```

So I can see the iSCSI disks, however the output is slow and more of the above errors are output in the logs.

Now, my initial iSCSI target setup is using demo mode so that I don't have to create all the iSCSI ACLs for each specific client. Here is the config:

```
/iscsi/iqn.20...:targetd/tpg1> get attribute 
ATTRIBUTE CONFIG GROUP
======================
authentication=0
----------------
If set to 1, enforce authentication for this TPG.

cache_dynamic_acls=1
--------------------
If set to 1 in demo mode, cache dynamically generated ACLs.

default_cmdsn_depth=64
----------------------
Default CmdSN (Command Sequence Number) depth.

default_erl=0
-------------
Default Error Recovery Level.

demo_mode_discovery=1
---------------------
If set to 1 in demo mode, enable discovery.

demo_mode_write_protect=0
-------------------------
If set to 1 in demo mode, prevent writes to LUNs.

fabric_prot_type=0
------------------
Fabric DIF protection type.

generate_node_acls=1
--------------------
If set to 1, allow all initiators to login (i.e. demo mode).

login_timeout=15
----------------
Login timeout value in seconds.

netif_timeout=2
---------------
NIC failure timeout in seconds.

prod_mode_write_protect=0
-------------------------
If set to 1, prevent writes to LUNs.

t10_pi=0
--------
If set to 1, enable T10 Protection Information.

tpg_enabled_sendtargets=1
-------------------------
If set to 1, the SendTargets discovery response advertises the TPG only if the TPG is enabled.
```

Despite using demo mode, as part of the setup of iSCSI, I did setup all the target ACLs for the hosts:
```
/iscsi/iqn.20...:targetd/tpg1> ls
o- tpg1 ........................................................................................................ [gen-acls, no-auth]
  o- acls ................................................................................................................ [ACLs: 5]
  | o- iqn.1988-12.com.oracle:614230c1a758 ........................................................................ [Mapped LUNs: 0]
  | o- iqn.2005-03.org.open-iscsi:123ab0f85a90 .................................................................... [Mapped LUNs: 4]
  | | o- mapped_lun0 ............................................ [lun0 block/vgext01:pvc-c94d3e5f-9fe2-11e8-8a9c-5254004dd200 (rw)]
  | | o- mapped_lun2 ............................................ [lun5 block/vgext01:pvc-c35141dc-9fe2-11e8-8a9c-5254004dd200 (rw)]
  | | o- mapped_lun3 ............................................ [lun3 block/vgext01:pvc-81fcf3d0-9fe1-11e8-b5fc-5254004dd202 (rw)]
  | | o- mapped_lun4 ............................................ [lun4 block/vgext01:pvc-8ee3888e-9fe1-11e8-8a9c-5254004dd200 (rw)]
  | o- iqn.2005-03.org.open-iscsi:6ee68d42f46f ..................................................................... [Mapped LUNs: 4]
  | | o- mapped_lun0 ............................................ [lun0 block/vgext01:pvc-c94d3e5f-9fe2-11e8-8a9c-5254004dd200 (rw)]
  | | o- mapped_lun2 ............................................ [lun5 block/vgext01:pvc-c35141dc-9fe2-11e8-8a9c-5254004dd200 (rw)]
  | | o- mapped_lun3 ............................................ [lun3 block/vgext01:pvc-81fcf3d0-9fe1-11e8-b5fc-5254004dd202 (rw)]
  | | o- mapped_lun4 ............................................ [lun4 block/vgext01:pvc-8ee3888e-9fe1-11e8-8a9c-5254004dd200 (rw)]
  | o- iqn.2005-03.org.open-iscsi:999951c77f9 ..................................................................... [Mapped LUNs: 4]
  | | o- mapped_lun0 ............................................ [lun0 block/vgext01:pvc-c94d3e5f-9fe2-11e8-8a9c-5254004dd200 (rw)]
  | | o- mapped_lun2 ............................................ [lun5 block/vgext01:pvc-c35141dc-9fe2-11e8-8a9c-5254004dd200 (rw)]
  | | o- mapped_lun3 ............................................ [lun3 block/vgext01:pvc-81fcf3d0-9fe1-11e8-b5fc-5254004dd202 (rw)]
  | | o- mapped_lun4 ............................................ [lun4 block/vgext01:pvc-8ee3888e-9fe1-11e8-8a9c-5254004dd200 (rw)]
  | o- iqn.2005-03.org.open-iscsi:b35b34784dd ..................................................................... [Mapped LUNs: 4]
  |   o- mapped_lun0 ............................................ [lun0 block/vgext01:pvc-c94d3e5f-9fe2-11e8-8a9c-5254004dd200 (rw)]
  |   o- mapped_lun2 ............................................ [lun5 block/vgext01:pvc-c35141dc-9fe2-11e8-8a9c-5254004dd200 (rw)]
  |   o- mapped_lun3 ............................................ [lun3 block/vgext01:pvc-81fcf3d0-9fe1-11e8-b5fc-5254004dd202 (rw)]
  |   o- mapped_lun4 ............................................ [lun4 block/vgext01:pvc-8ee3888e-9fe1-11e8-8a9c-5254004dd200 (rw)]
  o- luns ................................................................................................................ [LUNs: 4]
  | o- lun0  [block/vgext01:pvc-c94d3e5f-9fe2-11e8-8a9c-5254004dd200 (/dev/vgext01/pvc-c94d3e5f-9fe2-11e8-8a9c-5254004dd200) (default_tg_pt_gp)]
  | o- lun3  [block/vgext01:pvc-81fcf3d0-9fe1-11e8-b5fc-5254004dd202 (/dev/vgext01/pvc-81fcf3d0-9fe1-11e8-b5fc-5254004dd202) (default_tg_pt_gp)]
  | o- lun4  [block/vgext01:pvc-8ee3888e-9fe1-11e8-8a9c-5254004dd200 (/dev/vgext01/pvc-8ee3888e-9fe1-11e8-8a9c-5254004dd200) (default_tg_pt_gp)]
  | o- lun5  [block/vgext01:pvc-c35141dc-9fe2-11e8-8a9c-5254004dd200 (/dev/vgext01/pvc-c35141dc-9fe2-11e8-8a9c-5254004dd200) (default_tg_pt_gp)]
  o- portals .......................................................................................................... [Portals: 1]
    o- 0.0.0.0:3260 ........................................................................................................... [OK]
/iscsi/iqn.20...:targetd/tpg1> 
```

To setup the ACLs, I use `ros` to get the initiator name so that I could add an ACL and then added the ACL to the iSCSI configuration. Example:

```
[root@kw01 ~]# ros s logs open-iscsi 2>&1 | grep Initiator
open-iscsi_1 | 	echo "InitiatorName=`/sbin/iscsi-iname`" > /etc/iscsi/initiatorname.iscsi ; \
open-iscsi_1 | 	echo "Setting InitiatorName to `cat /etc/iscsi/initiatorname.iscsi`" ; \
open-iscsi_1 | Setting InitiatorName to InitiatorName=iqn.2005-03.org.open-iscsi:6ee68d42f46f
open-iscsi_1 | 	echo "InitiatorName=`/dist/arch/sbin/iscsi-iname`" > /dist/arch/etc/iscsi/initiatorname.iscsi ; \
open-iscsi_1 | 	echo "Setting InitiatorName to `cat /dist/arch/etc/iscsi/initiatorname.iscsi`" ; \
```
So in the above, I would assume that the initiator name is *iqn.2005-03.org.open-iscsi:6ee68d42f46f*.

I also made sure that my Kubernetes StorageClass is set to add the correct ACLs when new luns are created:
```
[ justin@thespies.org / thespies ] 14:25 $ cat iscsi-storageclass.yaml 
kind: StorageClass
apiVersion: storage.k8s.io/v1beta1
metadata:
  name: iscsi-external
provisioner: iscsi-targetd
parameters:
# this id where the iscsi server is running
  targetPortal: 192.168.86.28:3260

# if you are using multipath, you can specify additional IPs here, default empty
# portals: 192.168.99.101:3260,192.168.99.102:3260

# this is the iscsi server iqn  
#  iqn: iqn.2003-01.org.linux-iscsi.minishift:targetd
  # iqn: iqn.1988-12.com.oracle:614230c1a758
  iqn: iqn.2018-01.org.thespies.home.kvm-01:targetd
  
# this is the iscsi interface to be used, the default is default
# iscsiInterface: default

# this must be on eof the volume groups condifgured in targed.yaml, the default is vg-targetd
# volumeGroup: vg-targetd
  volumeGroup: vgext01

# this is a comma separated list of initiators that will be give access to the created volumes, they must correspond to what you have configured in your nodes.
  initiators: iqn.2005-03.org.open-iscsi:b35b34784dd,iqn.2005-03.org.open-iscsi:6ee68d42f46f,iqn.2005-03.org.open-iscsi:123ab0f85a90

#  initiatorName: iqn.2005-03.org.open-iscsi:999951c77f9
  
# whether or not to use chap authentication for discovery operations  
  chapAuthDiscovery: "false"
 
# whether or not to use chap authentication for session operations  
  chapAuthSession: "false"  

# This is the filesystem you want your volume to be formatted with, default xfs
  fsType: "ext4"

# Whether the volume should be mounted in readonly mode, default false
  readOnly: "false"
```

So everything should work fine. And generally it does - the volumes get created, they get attached, and they get mounted properly. But I get a LOT of those error messages.

So I searched the file system for any file called 'initiator*' and I get this:
```
[root@kw01 ~]# find / -name '*initiator*'
/sys/devices/platform/host2/session1/iscsi_session/session1/initiatorname
/sys/devices/platform/host2/iscsi_host/host2/initiatorname
/var/lib/docker/overlay2/195b02d411c550044bf077ba49c0ca5f23fef2419cdc9547cf67121a728f86a4/merged/etc/iscsi/initiatorname.iscsi
/var/lib/docker/overlay2/575bf55d88060e834625bca028db9cbbf58a51072837cb4743913edffa8f18e5/merged/etc/iscsi/initiatorname.iscsi
/var/lib/docker/overlay2/c46f27a40d58771c99799f6dd920ca6d6348fe3f5d15b92aaed594c5668f6a62/diff/etc/iscsi/initiatorname.iscsi
/var/lib/docker/overlay2/4cbfdeec4cbb146b548893af1e550f571beba284d4104c3266525503ad340c68/merged/etc/iscsi/initiatorname.iscsi
/var/lib/docker/overlay2/ad4d9bbd557ac38d25b9edf6b5eb88399ea4fd7194ec2e4c5c2e863d6d3209ec/merged/etc/iscsi/initiatorname.iscsi
/var/lib/docker/overlay2/bbcb175db0081beb1887be035d546c51039a30f0bbb3fec5cd8a3f88855c1cc8/merged/etc/iscsi/initiatorname.iscsi
/usr/lib/modules/4.14.32-rancher2/build/include/config/scsi/osd/initiator.h
/usr/lib/modules/4.14.32-rancher2/build/include/scsi/osd_initiator.h
```

When I check all the *initiatorname* files, I found that they share the same initiator name (good) but it is NOT what is output in the `ros s logs ...` command from above. Instead I get:
```
[root@kw01 ~]# cat /sys/devices/platform/host2/session1/iscsi_session/session1/initiatorname
iqn.1993-08.org.debian:01:43b33c8355d0
[root@kw01 ~]# cat /var/lib/docker/overlay2/4cbfdeec4cbb146b548893af1e550f571beba284d4104c3266525503ad340c68/merged/etc/iscsi/initiatorname.iscsi
## DO NOT EDIT OR REMOVE THIS FILE!
## If you remove this file, the iSCSI daemon will not start.
## If you change the InitiatorName, existing access control lists
## may reject this initiator.  The InitiatorName must be unique
## for each iSCSI initiator.  Do NOT duplicate iSCSI InitiatorNames.
InitiatorName=iqn.1993-08.org.debian:01:43b33c8355d0
```

This initiator name is the same in all the files _AND it is the same on all my Rancher OS hosts_. Searching the web for the error string `1020 - ISCSI_ERR_TCP_CONN_CLOSE: TCP connection closed` I came across https://support.hpe.com/hpsc/doc/public/display?docId=mmr_kc-0118122 which states  that all initiators must have unique names:

```
CAUSE:In an environment where iSCSI LUNs are shared by multiple servers (for example, in a cluster), log files such as /var/log/messages become flooded with errors such as the following:
```
This is echoed in the official external iSCSI provisioner documentation from https://github.com/kubernetes-incubator/external-storage/tree/master/iscsi/targetd which states:

```
A note about names
In various places, iSCSI Qualified Names (IQNs) need to be created. These need to be unique. So every target must have it's own unique IQN, and every client (initiator) must have its own IQN.

IF NON-UNIQUE IQNs ARE USED, THEN THERE IS A POTENTIAL FOR DATA LOSS AND BAD PERFORMANCE!
```

Is there a step I am missing to properly configure the initiator name for iSCSI on ROS?
