### ISSUE TITLE
How to disable system suspend when closing laptop lid?

### ISSUE THREAD

**Issue by MichalMichalak** [rancher/os#2457]
**RancherOS Version: (ros os version)**
1.4.0
**Where are you running RancherOS? (docker-machine, AWS, GCE, baremetal, etc.)**
Sony VAIO laptop

I saw old closed ticket #1388 and there is a suggestion there to write_file `/etc/acpi/suspend.sh` with content `exit 0`. This doesn't seem to work anymore. File doesn't exist in the first place and creating new one doesn't change a thing.

I've also tried to switch console to centos and write_file `/etc/systemd/logind.conf` with content `HandleLidSwitch=ignore`. This also didn't help.

In both cases I changed config with `ros` command, then reboot and in the end checked if the file has been created as it should be. In both cases after closing the lid, laptop suspended.

**Comment by Jason-ZW** [comment]
@MichalMichalak 
Could you please paste your write_files content？
I try write_files on ROS-v1.4.0 acpid system-docker container, the result not like you said.
```
#cloud-config
write_files:
  - container: acpid
    path: /etc/acpid/suspend.sh
    permissions: "0644"
    owner: root
    content: |
      exit 0
```

```
$ system-docker exec -it acpid cat /etc/acpid/suspend.sh
> exit 0
```
