### ISSUE TITLE
Fully automate setup from os-config.tpl.yml

### ISSUE THREAD

**Issue by axi92** [rancher/os#2464]
**RancherOS Version: (ros os version)** 4.14.65-rancher

**Where are you running RancherOS? (docker-machine, AWS, GCE, baremetal, etc.)**
Virtualbox on Ubuntu 18

Hello, my I try the following process:
- Boot from custom iso
- run the cloud-config from url
- ros install to /dev/sda (maybe from cloud-config if possible)
- preload some docker images
- shutdown machine

This is my cloud-config that is on http://192.168.3.77:8080
```
#cloud-config
ssh_authorized_keys:
  - ssh-rsa AAAAB.......Bw== admin@C6015
# runcmd:
# - [ sudo, ros, install, -d, /dev/sda, -c, http://192.168.3.77:8080 ] #not working
# - [ sudo, touch, /var/log/test ] #not working
# - sudo touch /var/log/test #not working
power_state:
 mode: poweroff
 timeout: 60
 condition: True
```
I tried a lot in the cloud-config but nothing worked. The only thing that was working when I boot up rancheros then execute "sudo ros install -d /dev/sda -c http://192.168.3.77:88" after the reboot I could login via ssh with the key. But I can't login into every system, we maybe will set up 100 per day. So I need a fully automate setup.

I made also a change on [os-config.tpl.yml ](https://github.com/rancher/os/blob/master/os-config.tpl.yml#L77)
```
  ....
  console: default
  cloud_init:
    datasources:
     - http://192.168.3.77:8080 #<- changed
  repositories:
    core:
      url: {{.OS_SERVICES_REPO}}/{{.REPO_VERSION}}
  state:
  ....

```
