### ISSUE TITLE
write_files in cloud-config.d/ to service container blocks booting for 5 mins.

### ISSUE THREAD

**Issue by Magicloud** [rancher/os#2470]
**RancherOS Version: (ros os version)** v1.4

**Where are you running RancherOS? (docker-machine, AWS, GCE, baremetal, etc.)** RaspberryPi 3

If I did not specify the container, it wrote to console as expected. But if did, the booting hangs after following message for 303 secs, then continue booting. And, the file was not written.
```
init:info: [0/1] [cloud-init]: Starting
cgroup: system-docker-r (270) created nested cgroup for controller "memory" which has incomplete hierarchy support. Nested cgroups may change behavior in the future.
cgroup: "memory" requires setting use_hierarchy to 1 on the root
```

The write_files part:
```
write_files:
  - container: net_auth
    path: /etc/net_auth.info
    content: |
      # this is classified.
```
