### ISSUE TITLE
CPU usage is much higher than CoreOS, but I have no clue why. 

### ISSUE THREAD

**Issue by vroad** [rancher/os#2471]
**RancherOS Version: (ros os version)**
v1.2.0

**Where are you running RancherOS? (docker-machine, AWS, GCE, baremetal, etc.)**
AWS

I've switched to CoreOS some time ago, and CPU usage on AWS management console dropped from 8% to 3%. The number of running container apparently had to do with CPU usage. Running a docker container seems to have some overhead and increases CPU usage of EC2 instance even when container is almost always idle, but I don't know why.

I was running multiple Wordpress sites on Amazon ECS. (php-fpm+nginx, database was on RDS.)

**Comment by kingsd041** [comment]
I created a CoreOS-stable-1855.4.0-hvm(t2.small) instance and a rancheros-v1.4.1(t2.small) instance on aws, and then created 7 WordPress using the following docker-compose.
```
version: '3.1'

services:
  wordpress:
    image: wordpress
    restart: always
    ports:
      - 8080:80
    environment:
      WORDPRESS_DB_PASSWORD: example

  mysql:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: example
```
At this time I observe the CPU utilization of the two instances.
```
CoreOS: 0.93
RancherOS: 1.29
```
Then increase to 8 wordpress+mysql containers
```
CoreOS: 1.13
RancherOS: 1.76
```
There is almost no difference in CPU utilization between coreos and rancheros when there is no load.

@vroad I did not reproduce this issue in v1.4.1, I am not sure if my steps are the same as you.
