### ISSUE TITLE
network.interfaces: "mac=..." doesn't work; dhcp: false is ignored

### ISSUE THREAD

**Issue by michael-brade** [rancher/os#2521]
**RancherOS Version: v1.4.2-rc1**

**Where are you running RancherOS? qemu/kvm using virt-manager**

## Preparation:

I am currently trying to install RancherOS in a virtual machine using virt-manager. Booting the ISO works without any problems. I then partition the disk and install RancherOS it using
```
ros install -d /dev/sda -p /dev/sda1 -c /mnt/cloud-config.yml -t generic --append "rancher.password=secret"
```
My `cloud-config.yml`:
```
hostname: server
rancher:
    environment:
    console: debian
    docker:
        tls: false
    network:
        interfaces:
            "mac=52:54:00:BC:CF:40":
                address: 172.17.0.91
                gateway: 172.17.0.1
                dhcp: false
        dns:
            nameservers:
                - 10.124.0.254
    services:
        zfs:
            restart: always
```

Installation works, no issues. Reboot.

## Problems

When booting from the IDE harddisk in qemu, I have the following problems:

- even though dhcp is disabled, my dnsmasq logs DHCP requests from the virtual machine.
- when the booting is finished, the interface has no IP address
- `dmesg` logs `system-dockerd[1216]: segfault at 8 ip 00000000000542436 sp 000000 c420d1d308 error 4 in system-dockerd[400000+1485000]`. I am not sure if this line is relevant, but it doesn't look good.
