### ISSUE TITLE
ZFS service doesn't work if in cloud-config.yml

### ISSUE THREAD

**Issue by michael-brade** [rancher/os#2527]
**RancherOS Version: v1.4.2**

**Where are you running RancherOS? baremetal, qemu**

Now that networking is doing fine, I can move on to the next issues: ZFS can be manually installed using `ros service enable zfs`:
```
ERRO[0000] Missing the image: Error: No such image: docker.io/rancher/os-zfs:v1.4.2 
Pulling zfs (docker.io/rancher/os-zfs:v1.4.2)...
```
But if I add it to `cloud-config.yml`:
```
rancher:
    network:
        interfaces:
            eth0:
                dhcp: true
    services:
        zfs:
            restart: always
```
then I get the following:
```
ros-sysinit:fatal: Error: No such image: os_zfs
```
Note the underscore instead of the dash: `os_zfs` instead of `os-zfs`.
