### ISSUE TITLE
Mounting file turns it into a directory

### ISSUE THREAD

**Issue by M0rfic** [rancher/os#2557]
**RancherOS Version: (ros os version)**
 - rancher/os:v1.4.2
- docker-18.03.1-ce

**Where are you running RancherOS? (docker-machine, AWS, GCE, baremetal, etc.)**
 - [Proxmox VE](https://www.proxmox.com/en/proxmox-ve)

I'm trying to run an application called [Ignition as a container](https://hub.docker.com/r/kcollins/ignition/) which allows for a backup file to be mounted as `-v /path/to/gateway.gwbk:/restore.gwbk`. However, with the below config, upon startup the file is _"converted"_ to a folder, just like docker would create it when using a non existent directory:

```
        ignition:
            image: kcollins/ignition:7.9.9
            name: ignition
            restart: unless-stopped
            privileged: true
            ports:
               - 8088:8088
            volumes:
               - /var/lib/ignition/ignition.gwbk:/restore.gwbk
```
On the other hand, manually starting a container with `-v` works just fine. I've searched the docs and forums to figure out if there's something I'm doing wrong but came out empty handed. Thus I'm kindly asking if this is a feature, bug, or what it is that I'm missing.

Kind regards
