### ISSUE TITLE
Boot from cloud-config cannot get DNS when the interface is set to DHCP

### ISSUE THREAD

**Issue by rootwuj** [rancher/os#2562]
**RancherOS Version: (ros os version)**
rancher/os: f6ee304
Linux rancher 4.14.79-rancher2

**Where are you running RancherOS? (docker-machine, AWS, GCE, baremetal, etc.)**
Boot from U disk

**Steps to reproduce :**
1. Start RancherOS via U disk.
2. Configure `cloud-config.yaml` :
    Add wifi to the interface, and set DHCP true in wifi_networks.
``` yaml
#cloud-config
rancher:
  network:
    interfaces:
      wlan0:
        wifi_network: network1
    wifi_networks:
      network1:
        ssid: xxxxxxxxxx
        psk: xxxxxxxxxxx
        scan_ssid: 1
```
3. via cloud-config on boot
```
$ ros install -c cloud-config.yml -d /dev/sdd --append “rancher.password=rancher”
```

**Result:**

RancherOS started successfully but could not get DNS.
```
$ cat etc/resolv.conf
$
```
**Other details that may be helpful:**
Can be obtained to DNS when set to static IP.
