### ISSUE TITLE
Both set eth0 and wlan0, wlan0 can not get ip from dhcp

### ISSUE THREAD

**Issue by Jason-ZW** [rancher/os#2572]
**RancherOS Version: (ros os version)**
4cb0f462bddf2d6345d6b06ac87ce30437788aa5

Both set eth0 and wlan0, wlan0 can not get ip from dhcp, such like:
```
rancher:
  network:
    interfaces:
      eth0:
        dhcp: true
      wlan0:
         wifi_network: network1
    wifi_networks:
      network1:
        ssid: xxxx
        psk: xxx
```
Maybe this because other dhcp request can not be handled by the master dhcpcd process: 
```
If any interface reports a working carrier then dhcpcd will try and obtain a lease before forking to the background, otherwise it will fork right away. 
```
