### ISSUE TITLE
Not picking up network config from configdrive2

### ISSUE THREAD

**Issue by arnarg** [rancher/os#2575]
**RancherOS Version: (ros os version)**
v1.4.2

**Where are you running RancherOS? (docker-machine, AWS, GCE, baremetal, etc.)**
Proxmox/KVM

Proxmox supports cloud-init as of version 5.2. By default it uses NoCloud which doesn't seem to be supported by RancherOS but can be set to configdrive2. When I change my VM to configdrive2 RancherOS picks up everything from cloud-init except networking, it uses dhcp instead.

When I mount the configdrive it has the following.
```
openstack
  |-- content
  |   `-- 0000
  `-- latest
      |-- meta_data.json
      `-- user_data
```

openstack/latest/user_data:
```
#cloud-config
hostname: hostname_set_in_proxmox
manage_etc_hosts: true
fqdn: hostname_set_in_proxmox_with_fqdn
user: rancher
ssh_authorized_keys:
  - ssh-rsa key_set_in_proxmox
chpasswd:
  expire: False
users:
  - default
package_upgrade: true
```

openstack/latest/meta_data.json:
```
{
     "uuid": "c7e51b981c9df5019a45ccbf66c3b5e2c2ef71bb",
     "network_config": { "content_path": "/content/0000" }
}
```

openstack/content/0000:
```
auto lo
iface lo inet loopback

        dns_nameservers x.x.x.2
        dns_search domain.com
auto eth0
iface eth0 inet static
        address x.x.x.10
        netmask 255.255.255.0
        gateway x.x.x.1
```

`/var/lib/rancher/conf/cloud-config.yml` only includes:
```
rancher:
  console: fedora
```

**Comment by arnarg** [comment]
I see. Unfortunately the format of the data isn't configurable, just the values.
Is there any cloud-init data source that uses the rancher style?

**Comment by discordier** [comment]
I ran into the same problem and solved it for me by doing the following.

Create VM (id 1001 in this example)

`vi /mnt/pve/cephfs/snippets/user-1001.yml` (swap `mnt/pve/cephfs` with the desired snippets storage).
Put in the following:
```
#cloud-config
hostname: rancheros
manage_etc_hosts: true
ssh_authorized_keys:
  - ssh-rsa YOUR-PUBLIC-KEY
  - ssh-rsa ANOTHER-PUBLIC-KEY
chpasswd:
  expire: False
users:
  - default
package_upgrade: true
rancher:
  network:
    interfaces:
      eth0:
        address: 192.168.100.222/24
        mtu: 9000
        dhcp: false
```
Register the config in the machine: `qm set 1001 --cicustom user=cephfs:snippets/user-1001.yml`
