### ISSUE TITLE
Cannot set multiple gateways

### ISSUE THREAD

**Issue by kingsd041** [rancher/os#2587]
**RancherOS Version: (ros os version)**
1.5.0-rc1
**Where are you running RancherOS? (docker-machine, AWS, GCE, baremetal, etc.)**
KVM and virtualbox

My rancheros has multiple NICs, I have set up gateways for `eth1` and 'eth2'. After the setup is successful, I can't find the default gateway of eth2 on rancheros.

```
[root@rancher ~]# ros c export
rancher:
  environment:
    EXTRA_CMDLINE: /init
  network:
    interfaces:
      eth0:
        dhcp: true
      eth1:
        address: 10.1.0.41/24
        dhcp: false
        gateway: 10.1.0.1
        mtu: 1500
      eth2:
        address: 10.31.168.85/24
        dhcp: false
        gateway: 10.31.168.1
        mtu: 1500
  state:
    dev: LABEL=RANCHER_STATE
    wait: true
ssh_authorized_keys:
- ssh-rsa ......
```

```
[root@rancher ~]# ip route
default via 10.1.0.1 dev eth1
default via 192.168.122.1 dev eth0 src 192.168.122.39 metric 202
10.1.0.0/24 dev eth1 proto kernel scope link src 10.1.0.41
10.31.168.0/24 dev eth2 proto kernel scope link src 10.31.168.85
172.17.0.0/16 dev docker0 proto kernel scope link src 172.17.0.1 linkdown
172.18.0.0/16 dev docker-sys proto kernel scope link src 172.18.42.1 linkdown
192.168.122.0/24 dev eth0 proto kernel scope link src 192.168.122.39 metric 202
```

**Expected results**
`default via 10.31.168.1 dev eth2`
