### ISSUE TITLE
Rancher shows "ServerFaultCode: A specified parameter was not correct" when setting console in cloud config

### ISSUE THREAD

**Issue by akkie** [rancher/os#2590]
**RancherOS Version: (ros os version)**
v1.4.2

**Where are you running RancherOS? (docker-machine, AWS, GCE, baremetal, etc.)**
vSphere 5.5

If I set the console in the cloud config as described in the [documentation](https://rancher.com/docs/os/v1.2/en/configuration/switching-consoles/), then the node will start successfully and installs the console. But Rancher shows: "Error creating machine: Error in driver during machine creation: ServerFaultCode: A specified parameter was not correct.". Rancher then tries to provision the node again and again. I have tried to set the console to centos and ubuntu.

My current config:
```yaml
#cloud-config
rancher:
  console: ubuntu
  registry_auths:
    https://registry.domain.com/:
      username: "user"
      password: "***"

ssh_authorized_keys:
  - ssh-rsa *** rancher@domain.com

write_files:
  - path: /etc/docker/certs.d/registry.diacc.local/ca.crt
    permissions: "0644"
    owner: root
    content: |
      -----BEGIN CERTIFICATE-----
      ***
      -----END CERTIFICATE-----
```
