### ISSUE TITLE
WifiNetworks invalid PSK when contains only numbers

### ISSUE THREAD

**Issue by TheAifam5** [rancher/os#2597]
**RancherOS Version: (ros os version)**: 1.5.0-rc1

**Where are you running RancherOS? (docker-machine, AWS, GCE, baremetal, etc.)**
Raspberry Pi 3B+

Hey,
my PSK is just simple long number. After setting the PSK value with `ros config set rancher.network.wifi_network.home.psk "123456789123456789123456789"` and then using the export parameter like `ros config export` the structure looks like this:
```
rancher:
  network:
    wifi_networks:
      home:
        psk: 1.23456789123456e+30
```

PS. That's not my *actual* PSK :D 

Regards,
TheAifam5
