### ISSUE TITLE
Boot with ubuntu console in v1.5.0 stuck

### ISSUE THREAD

**Issue by Sebisnow** [rancher/os#2628]
**RancherOS Version: 1.5.0*

On baremetal, when I upgrade to 1.5.0 or install to 1.5.0 and boot with the ubuntu console everything dies and the servers are unreachable. We suppose it gets stuck starting the ubuntu console. We also observed that directly after the upgrade the console was not ubuntu even though specified in cloud-config.yml but default. All previously running containers and data were consequently lost.

To fix the issues we temporarily "upgraded" to v1.4.2 again as here everything works as expected.

Unfortunately I cannot provide much more information as I cannot observe what exactly happens after rebooting as I cannot yet connect to the server.

**Comment by niusmallnan** [comment]
@Sebisnow How did you enable the ubuntu console? Can you show me your steps?

**Comment by niusmallnan** [comment]
@Sebisnow You should use `ros console switch` or `ros console enable` to preload the console images.
If you just configure it in cloud-config, ROS also needs the network to download the console image。

**Comment by Sebisnow** [comment]
Thank you for your quick reply @niusmallnan. You suggest a command in the cloud-config like:
```
runcmd:
  - ros console enable ubuntu
```
Right?

Since RancherOS versions 1.1.0 we use a very similar cloud-config.yml that worked perfectly for all version upgrades so far. After the 1.5.0 upgrade including a reboot all our previously running docker containers and their data in volumes was lost. 

Here is the cloud-config:
```
write_files:
  - container: network
    path: /var/lib/iptables/rules.sh
    permissions: "0755"
    owner: root:root
    content: |
      #!/bin/bash
      set -ex
      echo prod >> /var/log/net.log
      iptables -A INPUT -i lo -j ACCEPT # Loopback
      iptables -A INPUT -m conntrack --ctstate RELATED,ESTABLISHED -j ACCEPT # Outgoing
      iptables -A INPUT -p icmp --icmp-type echo-request -j ACCEPT # PING
      iptables -A INPUT -s <ip> -j ACCEPT # PROD_Monitoring
      .
      .
      .
      iptables -A INPUT -j LOG
      iptables -P INPUT DROP
      iptables -P FORWARD ACCEPT
      # the last line of the file needs to be a blank line or a comment
rancher:
  console: ubuntu
  environment:
    EXTRA_CMDLINE: /init
  services_include:
    kvm-vm-tools: true
  state:
    dev: LABEL=RANCHER_STATE
    wait: true
  docker:
    engine: docker-17.12.1-ce
  network:
    post_cmds:
    - /var/lib/iptables/rules.sh post_cmds
runcmd:
  - echo deadline > /sys/block/sda/queue/scheduler # use deadline scheduler as it is faster on SSDs
  - swapoff -a # turn the swap off
  - sysctl -w vm.max_map_count=524288 # increase mmap counts to optimize for elasticsearch 
  - sysctl -w net.core.somaxconn=8192 # increase the network connection count
  - ulimit -n 65536 # icrease maximum of open files
  - apt update
  - echo 1 | apt install cron postfix -y
  - cp /usr/share/postfix/main.cf.debian /etc/postfix/main.cf
  - /etc/init.d/postfix start
  - ifconfig eth0 mtu 9000 up # Allow Network packages to bit jumbo frames
  - service cron start
  - echo '*/5 * * * * rancher sudo iptables -P INPUT DROP' > /etc/cron.d/iptables # Rancher sets INPUT to ACCEPT
ssh_authorized_keys:
  - ssh-rsa <ssh-key>
  .
  .
  .
```
