### ISSUE TITLE
DHCP + cloud-config

### ISSUE THREAD

**Issue by kinolaev** [rancher/os#2691]
**RancherOS Version: (ros os version)** 1.5.1

**Where are you running RancherOS? (docker-machine, AWS, GCE, baremetal, etc.)** docker-machine vmwarevsphere

Hello!
I use this cloud-config to provision nodes on vsphere with rancher 
```yml
#cloud-config
rancher:
  docker:
    engine: docker-17.03.2-ce
  network:
    interfaces:
      eth0:
        addresses:
        - 10.0.0.0/24
        gateway: 10.0.0.1
```
When network has dhcp server rancheros doesn't switch docker engine:
`Get https://raw.githubusercontent.com/rancher/os-services/v1.5.1/d/docker-17.03.2-ce.yml: dial tcp: lookup raw.githubusercontent.com on [::1]:53: read udp [::1]:47930->[::1]:53: read: connection refused`

If I remove `rancher.network` from cloud-config or stop dhcp server rancheros switch docker engine correctly. So problem only appears when dhcp server enabled AND static network config provided via cloud-config.

Related:
https://github.com/rancher/os/issues/2653
https://github.com/rancher/os/issues/1904
