### ISSUE TITLE
Support wildcard matching on MAC addresses

### ISSUE THREAD

**Issue by niusmallnan** [rancher/os#2707]
From @mmriis :

It would be a nice feature to be able to wildcard match on mac adresses for interfaces. This is eg. useful for bonding where you would like all nics of a certain make or model to be added to the bond.

Using this feature you could do the following:

```
#cloud-config
rancher:
  network:
    interfaces:
      bond0:
        dhcp: true
        bond_opts:
          mode: 802.3ad
          lacp_rate: fast
          miimon: 100
        post_up:
          - ip route add 0.0.0.0/0 via 1.2.3.4
      # Add all Mellanox adapters to bond
      "mac=98:03:9b*":
        bond: bond0
```
