### ISSUE TITLE
RANCHER_STATE not mounting

### ISSUE THREAD

**Issue by alexskysilk** [rancher/os#2729]
**RancherOS Version: (ros os version)**
1.5.1
**Where are you running RancherOS? (docker-machine, AWS, GCE, baremetal, etc.)**
PXE on Proxmox KVM

I'm trying to deploy the rancher state partition on a pxe POC, but for the life of me I cant seem to either understand HOW its supposed to work or IF its working at all. First, data:

my kernel line:
`kernel ${base-url}/vmlinuz rancher.password=password rancher.cloud_init.datasources=[url:${base-url-local}/cloudconfig.yml]`

my cloudconfig.yml
```
#cloud-config
rancher:
  state:
    fstype: auto
    dev: LABEL=RANCHER_STATE
    autoformat:
    - /dev/sda
    - /dev/vda
mounts:
- - /dev/sdb1
  - /mnt/data
  - ext4
  - ""
ssh_authorized_keys:
  - ssh-rsa foo
```

```
[rancher@rancher ~]$ sudo df
Filesystem           1K-blocks      Used Available Use% Mounted on
overlay                2021244    434340   1586904  21% /
tmpfs                  1956984         0   1956984   0% /dev
tmpfs                  2021244         0   2021244   0% /sys/fs/cgroup
none                   2021244       796   2020448   0% /run
tmpfs                  2021244         0   2021244   0% /mnt
tmpfs                  2021244         0   2021244   0% /media
devtmpfs               1956984         0   1956984   0% /host/dev
shm                      65536         0     65536   0% /host/dev/shm
none                   2021244       796   2020448   0% /var/run
tmpfs                  2021244    434340   1586904  21% /etc/hostname
shm                      65536         0     65536   0% /dev/shm
devtmpfs               1956984         0   1956984   0% /dev
shm                      65536         0     65536   0% /dev/shm
/dev/sdb1             32895760     49176  31152532   0% /mnt/data

[rancher@rancher ~]$ sudo blkid
/dev/sda: LABEL="RANCHER_STATE" UUID="93b9e913-2cb8-4d7a-9745-dfe66faa9580" TYPE="ext4"
/dev/sdb1: UUID="d53b132f-400c-491a-8a44-a15d22c97bb9" TYPE="ext4" PARTUUID="0c3e512c-01"
```

No matter what I thought to do, the RANCHER_STATE volume does not mount, nor does it appear to be used in any way. Is it SUPPOSED TO mount? if so, where and how?
