### ISSUE TITLE
cloudconfig directive not processing

### ISSUE THREAD

**Issue by alexskysilk** [rancher/os#2730]
**RancherOS Version: (ros os version)**
1.5.1
**Where are you running RancherOS? (docker-machine, AWS, GCE, baremetal, etc.)**
iPXE

My aim is to have a pxe booted instance auto connect to a rancher cluster, but the join directive does not seem to want to work when placed into the cloudconfig, resulting in 

`ros-sysinit:error: Failed to pull image rancher/agent:v2.2.0: Error response from daemon: manifest for rancher/agent:v2.2.0 not found`

Here is my cloudconfig:
```
#cloud-config
rancher:
  state:
    fstype: auto
    dev: LABEL=RANCHER_STATE
    autoformat:
    - /dev/sda
    - /dev/vda
  services:
    rancher-agent1:
      labels:
        io.rancher.os.before: wait-for-network #Added in case its a network not ready issue
      image: rancher/agent:v2.2.0
      server: https://10.1.1.12
      net: host
      token: xxx
      ca-checksum: xxx
      privileged: true
      volumes:
        - /etc/kubernetes:/etc/kubernetes
        - /var/run:/var/run
      worker: true
      etcd: true
      controlplane: true

mounts:
- - /dev/sdb1
  - /mnt/data
  - ext4
  - ""
ssh_authorized_keys:
  - ssh-rsa foo
```

running the command:

sudo docker run -d --privileged --restart=unless-stopped --net=host -v /etc/kubernetes:/etc/kubernetes -v /var/run:/var/run rancher/rancher-agent:v2.2.0 --server https://10.1.1.12 --token xxx --ca-checksum xxx --etcd --controlplane --worker

after boot works fine, but the cloudconfig rancher-agent1 directive fails even on subsequent reboot which implies the cloudconfig is malformed since the docker image is already present. help?

**Comment by niusmallnan** [comment]
You can try this way:
```
#cloud-config
rancher:
write_files:
  - path: /etc/rc.local
    permissions: "0755"
    owner: root
    content: |
      #!/bin/bash
      # wait for network
      while ! curl -o /dev/null -sf https://hub.docker.com/; do
        echo "wait network up"
      done
      wait-for-docker
      # run rancher-agent
      # docker run xxxxx
```

**Comment by alexskysilk** [comment]
I tried to implement as suggested:
```
#cloud-config
rancher:
  state:
    fstype: auto
    dev: LABEL=RANCHER_STATE
    autoformat:
    - /dev/sda
    - /dev/vda
write_files:
  - path: /etc/rc.local
    permissions: "0755"
    owner: root
    content: |
      #!/bin/bash
      # wait for network
      while ! curl -o /dev/null -sf https://hub.docker.com/; do
        echo "wait network up"
      done
      wait-for-docker
      # run rancher-agent
      docker run -d --privileged --restart=unless-stopped --net=host -v /etc/kubernetes:/etc/kubernetes -v /var/run:/var/run rancher/rancher-agent:v2.2.1 --server https://10.1.1.15 --token k9cc76pczhr5zw74ktlxnmm6j9cc72w2vfg67gqz6bh6nt4bx9mwqc --ca-checksum 9d963e3c09eececa80aaa54e27796c6217c902acee619e47842852c69462d97a --etcd --controlplane --worker

mounts:
- - /dev/sdb1
  - /mnt/data
  - ext4
  - ""
ssh_authorized_keys:
  - ssh-rsa ...
```
But this causes the client to hang during boot; it gets this far:
![image](https://user-images.githubusercontent.com/31548164/55429493-7fafb400-5540-11e9-9532-b2a17217dae0.png)
