### ISSUE TITLE
Container gets started when its data volume dependencies are not satisfied

### ISSUE THREAD

**Issue by imikushin** [rancher/os#274]
Given we have this in our compose file:
```yml
rancher-state:
  image: rancher/server:latest
  labels:
  - io.rancher.os.createonly=true
  - io.rancher.os.remove=false
  volumes:
  - /var/lib/cattle
  - /var/lib/mysql
rancherserver:
  image: rancher/server:latest
  restart: always
  volumes_from:
  - rancher-state
  ports:
  - 8080:8080
```

current os master boots with the following messages:
```
INFO[0005] [16/17] [rancherserver]: Started             
ERRO[0005] Failed to start: rancher-state : API error (500): Invalid volume specification: 
/var/lib/cattle
 
ERRO[0005] Failed [2/5] 40%                             
FATA[0005] API error (500): Invalid volume specification: /var/lib/cattle
```

`rancherserver` shouldn't have even been attempted to start: because a hard (! - its data volumes) dependency wasn't satisfied

**Comment by imikushin** [comment]
`rancher-state` container still gets created, never minding the nasty "fatal" error

**Comment by imikushin** [comment]
Here's a snippet of `docker inspect rancher-state`:
```
    "Volumes": {},
    "VolumesRW": {}
```

**Comment by ibuildthecloud** [comment]
@imikushin What's not clear to me is how does this setup differ from anything else in RancherOS.  We do the exact same thing with our data containers and system container.  It seems there is something about `rancher-state` that is off.  Do you have issue if you create that container by itself.  Don't have rancher-server also.

**Comment by imikushin** [comment]
System data containers bind host dirs into container volumes (e.g. like `/home:/home`), here we have `/var/lib/cattle` (no `:`). I think that's it. Nothing special about rancher-state in itself.

**Comment by ibuildthecloud** [comment]
Does the following fail?

```yaml
foo:
  image: busybox
  labels:
  - io.rancher.os.createonly=true
  - io.rancher.os.remove=false
  volumes:
  - /foo
```
