### ISSUE TITLE
RancherOS boot failed with RancherOS started status.

### ISSUE THREAD

**Issue by laoshancun** [rancher/os#2746]
**RancherOS Version: (ros os version)**
v1.5.1
**Where are you running RancherOS? (docker-machine, AWS, GCE, baremetal, etc.)**
VMWare Esxi 6.7.0,also happened on hyper-v 2012.

![image](https://user-images.githubusercontent.com/4952748/56856995-c9ea5080-6999-11e9-80f0-b046f315b3be.png)

**Comment by niusmallnan** [comment]
@laoshancun Is that a fresh install? or upgrade from the previous version?

**Comment by laoshancun** [comment]
Fresh install.

**Comment by niusmallnan** [comment]
@laoshancun Can you provide more details? How did you boot on ESXi? 
Which artifact did you use? ISO or vmdk image?

**Comment by laoshancun** [comment]
OS was installed on disk by ISO `rancheros-vmware-autoformat.iso`.

**Comment by niusmallnan** [comment]
`rancheros-vmware-autoformat.iso` is used for docker-machine.
`rancheros-vmware.iso` can be used for booting from ISO.
`rancheros-vmware.vmdk` can be used for booting from disk.

Please provide more steps, we need to reproduce so that we can help you.

**Comment by laoshancun** [comment]
1. install RancherOS using `cloud-config.yml`.
```yaml
write_files:
  - path: /etc/rc.local
    permissions: "0755"
    owner: root
    content: |
      #!/bin/bash
      wait-for-docker
      # docker run -d nginx
runcmd:
  - sudo sed -i 's/SELINUX=enforcing/SELINUX=disabled/g' /etc/selinux/config
  - ln -sf /usr/share/zoneinfo/Asia/Shanghai /etc/localtime
  - sudo echo 'LANG="en_US.UTF-8"' >> /etc/profile

#cloud-config
rancher:
  # environment:
  #   ETCD_DISCOVERY: https://discovery.etcd.io/d1cd18f5ee1c1e2223aed6a1734719f7
  # resize_device: /dev/sda
  network:
    dns:
      nameservers:
      - 10.2.1.1
      - 223.5.5.5
    interfaces:
      eth0:
        address: "192.168.10.10/16"
        gateway: 192.168.15.1
        # mtu: 1500
        # dhcp: false        
  console: centos
  docker:
    # engine: docker-17.03.2-ce
    registry_mirror:  https://private_mirror
  system_docker:
    # engine: docker-17.03.2-ce
    registry_mirror: https://private_mirror
  bootstrap_docker:
    registry_mirror: https://private_mirror
  sysctl:
    net.ipv4.conf.default.rp_filter: 1
    net.bridge.bridge-nf-call-ip6tables: 1
    net.bridge.bridge-nf-call-iptables: 1
    net.bridge.bridge-nf-call-arptables: 1
    net.ipv6.conf.all.disable_ipv6: 1
    net.ipv6.conf.default.disable_ipv6: 1
    net.ipv6.conf.lo.disable_ipv6: 1
    net.ipv4.ip_nonlocal_bind: 1
    net.ipv4.neigh.default.gc_thresh1: 4096
    net.ipv4.neigh.default.gc_thresh2: 6144
    net.ipv4.neigh.default.gc_thresh3: 8192
#mounts:
#  - ["/dev/sdb1", "/var/lib/docker", "ext4", ""]
hostname: hostname
ssh_authorized_keys:
  - ssh-rsa ssh public key
```
2. install latest rancher server with single mode on it.
3. reboot after few days running.
