### ISSUE TITLE
logrotate config files will be overwritten every hour

### ISSUE THREAD

**Issue by niusmallnan** [rancher/os#2773]
**RancherOS Version: (ros os version)**
v1.5.1
**Where are you running RancherOS? (docker-machine, AWS, GCE, baremetal, etc.)**
All

The logrotate service runs every hour by cron service, you can check its service label.
https://github.com/rancher/os/blob/master/os-config.tpl.yml#L249-L256
```
    logrotate:
      image: {{.OS_REPO}}/os-logrotate:{{.VERSION}}{{.SUFFIX}}
      command: /usr/sbin/logrotate -v /etc/logrotate.conf
      labels:
        io.rancher.os.createonly: "true"
        io.rancher.os.scope: system
        io.rancher.os.before: system-cron
        cron.schedule: "@hourly"
```

The logrotate has en entrypoint script, https://github.com/rancher/os/blob/master/images/02-logrotate/usr/bin/entrypoint.sh:
```
#!/bin/bash

cp /usr/share/logrotate/logrotate.d/* /etc/logrotate.d

exec /usr/bin/ros entrypoint "$@"
```

If the `/etc/logrotate.d/docker` file is modified, it will be overwritten each time, as the `/usr/share/logrotate/logrotate.d/docker` file is in the logrotate container.
