### ISSUE TITLE
RancherOS default password?

### ISSUE THREAD

**Issue by ThePfaffanater** [rancher/os#2842]
**RancherOS Version:1.53**

**Where are you running RancherOS? Proxmox**

So I installed RancherOS to disk from ISO. This iso previously had auto-login set up by default. I proceeded to then remove the ISO and boot to the disk. The problem I ran into is that there is no way to login. For some reason they did not find reason to document this but according to issues on RancherOS's public repo they say that just using rancher and then entering nothing will work. It doesnt. The password I set during install from ISO does not work either. What am I supposed to do here? No default password is mentioned anywhere but github issues. The only thing I keep hearing is to set it up to autlogin by default when you instal it from the ISO but that I can not believe that would be best practice. They also recomend setting SSH private keys so you can get back in but that still would not help because setting the password of a user requires the user's previous password. And both of these definitely do not help me now anyway since I am already installed.

**Comment by niusmallnan** [comment]
ROS doesn't have a default password, we recommend using the ssh key.

If you still want to use a password, you can set it via kernel boot param:
https://rancher.com/docs/os/v1.x/en/installation/configuration/adding-kernel-parameters/#user-password

**Comment by ThePfaffanater** [comment]
So then why does it ask for a password? Even using the kernel parameters it still does not log in. Why does ROS ask for a password to a user that does not exist? How is that even possible in linux? How can you set a user to have no password and cant even be logged in?

**Comment by ThePfaffanater** [comment]
This is the entirety of my clould-config.yml
```
#cloud-config

hostname: compute1_rancheros

rancher: 
  network:
    interfaces:
      eth0:
	address: 10.0.0.121/24
	gateway: 10.0.0.1
	mtu: 1500
	dhcp: false
    dns:
      nameservers:
      - 1.1.1.1
      - 8.8.4.4

ssh_authorized_keys:
  - ssh-rsa <redacted>== RancherOSKey
```

The device is also now unreachable by that IP address after my multiple reinstalls becuase of this problem. So I can not SSH into it. What am I supposed to do? If I set the ip address when isntalling from ISO the ip address works. When I install and remove the iso media the ip doesnt. How does this make any sense. The config has not syntax errors and the hostname is applied correctly so i know it is reading the cloud-config.yml .  All of this could be avoided by not creating a user that is impossible to log into.
