### ISSUE TITLE
container-cron / crontab system service cannot connect to the Docker daemon when enabled in cloud-config.yml

### ISSUE THREAD

**Issue by zarkdav** [rancher/os#2846]
**RancherOS Version: v1.5.3**

**Where are you running RancherOS? docker-machine over VMware**

My cloud-config.yml automatically enables the user container crontab service (which is disabled by default). The goal is to schedule user containers by applying the proper `cron.schedule` labels.
Redacted cloud-config.yml:
```
#cloud-config
hostname: ...
ssh_authorized_keys:
  - ssh-rsa ...
write_files:
  - container: ntp
    path: /etc/ntp.conf
    permissions: "0644"
    owner: root
    contents: |
      server ...
      server ...
      server ...
      restrict default nomodify nopeer noquery limited kod
      restrict 127.0.0.1
      restrict [::1]
rancher:
  console: ubuntu
  network:
    dns:
      nameservers:
        - ...
      search:
        - ...
    interfaces:
      eth0:
        address: ...
        gateway: ...
        mtu: 1500
        dhcp: false
  services_include:
    crontab: true
    open-vm-tools: true
```

However, it looks like it is unable to connect to the user Docker socket:

```
docker@ic-services:~$ sudo system-docker logs container-cron 2>&1 | tail
time="2019-07-25T08:54:11Z" level=error msg="Cannot connect to the Docker daemon at unix:///var/run/docker.sock. Is the docker daemon running?" 
time="2019-07-25T08:54:11Z" level=error msg="Cannot connect to the Docker daemon at unix:///var/run/docker.sock. Is the docker daemon running?" 
time="2019-07-25T08:54:11Z" level=error msg="Cannot connect to the Docker daemon at unix:///var/run/docker.sock. Is the docker daemon running?" 
time="2019-07-25T08:54:11Z" level=error msg="Cannot connect to the Docker daemon at unix:///var/run/docker.sock. Is the docker daemon running?" 
time="2019-07-25T08:54:11Z" level=error msg="Cannot connect to the Docker daemon at unix:///var/run/docker.sock. Is the docker daemon running?" 
time="2019-07-25T08:54:11Z" level=error msg="Cannot connect to the Docker daemon at unix:///var/run/docker.sock. Is the docker daemon running?" 
time="2019-07-25T08:54:11Z" level=error msg="Cannot connect to the Docker daemon at unix:///var/run/docker.sock. Is the docker daemon running?" 
time="2019-07-25T08:54:11Z" level=error msg="Cannot connect to the Docker daemon at unix:///var/run/docker.sock. Is the docker daemon running?" 
time="2019-07-25T08:54:11Z" level=error msg="Cannot connect to the Docker daemon at unix:///var/run/docker.sock. Is the docker daemon running?" 
time="2019-07-25T08:54:11Z" level=error msg="Cannot connect to the Docker daemon at unix:///var/run/docker.sock. Is the docker daemon running?" 
```

Of course, this creates a busy loop.

It looks like container-cron is started earlier than the user Docker and the bind fails as a result. Stopping and restarting it breaks the loop and everything looks fine:

```
docker@ic-services:~$ sudo ros service stop container-cron 
docker@ic-services:~$ sudo ros service up container-cron
INFO[0000] Project [os]: Starting project               
INFO[0000] [0/21] [container-cron]: Starting            
INFO[0000] [1/21] [container-cron]: Started             
docker@ic-services:~$ sudo system-docker logs container-cron 2>&1 | tail 
time="2019-07-25T08:54:11Z" level=error msg="Cannot connect to the Docker daemon at unix:///var/run/docker.sock. Is the docker daemon running?" 
time="2019-07-25T08:54:11Z" level=error msg="Cannot connect to the Docker daemon at unix:///var/run/docker.sock. Is the docker daemon running?" 
time="2019-07-25T08:54:11Z" level=error msg="Cannot connect to the Docker daemon at unix:///var/run/docker.sock. Is the docker daemon running?" 
time="2019-07-25T08:54:11Z" level=error msg="Cannot connect to the Docker daemon at unix:///var/run/docker.sock. Is the docker daemon running?" 
time="2019-07-25T08:54:11Z" level=error msg="Cannot connect to the Docker daemon at unix:///var/run/docker.sock. Is the docker daemon running?" 
time="2019-07-25T08:54:11Z" level=error msg="Cannot connect to the Docker daemon at unix:///var/run/docker.sock. Is the docker daemon running?" 
time="2019-07-25T08:54:11Z" level=error msg="Cannot connect to the Docker daemon at unix:///var/run/docker.sock. Is the docker daemon running?" 
time="2019-07-25T08:54:11Z" level=error msg="Cannot connect to the Docker daemon at unix:///var/run/docker.sock. Is the docker daemon running?" 
time="2019-07-25T09:07:14Z" level=info msg="Starting Cron" 
time="2019-07-25T09:07:14Z" level=info msg="Scanning for container cron entries" 
```

Is there anyway to start container-cron after user Docker is started?

**Comment by niusmallnan** [comment]
Can you try this:
```
#cloud-config
rancher:
write_files:
  - path: /etc/rc.local
    permissions: "0755"
    owner: root
    content: |
      #!/bin/bash
      wait-for-docker
      ros s enable crontab
      ros s up crontab
```
