### ISSUE TITLE
Frustrations with cloud-init

### ISSUE THREAD

**Issue by reubenavery** [rancher/os#2851]
RancherOS v1.5.3 (AWS AMI), running on EC2

I've been really banging up against something trying to get a RancherOS node to fire off the Rancher 'docker run' command to join a cluster.

But first, why does the following cloud-config user data --
```
#cloud-config
final_message: "REUBEN AVERY WAS HERE"
```
result in no trace of this message being found in /var/log/boot?  Is RancherOS cloud-init not the same as https://cloudinit.readthedocs.io/en/latest/?

To expand now on the problem I'm wrestling with, I first tried to fire off the docker run command in user data like this:
```
#!/bin/sh
sudo docker run [rancher cluster join command]
```
and nothing.  so then I went to cloud-init first trying
```
#cloud-config
bootcmd: 
  - sudo docker run [rancher cluster join command]
```
..and nothing still in those darn logs that this even was attempted!

so then:
```
#cloud-config
runcmd: 
  - sudo docker run [rancher cluster join command]
```
nothing!

My final approach was then this:
```
#cloud-config
write_files:
  - path: /etc/rc.local
    permissions: "0755"
    owner: root
    content: |
      #!/bin/sh
      sudo docker [...] > /var/log/boot/node-join.log 2>&1
```

and this does result in /var/log/boot/node-join.log which contains perplexingly only `/etc/rc.local: line 2: docker: No such file or directory`

```
$ which docker
/bin/docker
```

grrr why are u fighting me

**Comment by niusmallnan** [comment]
You can try `wait-for-docker`:
```
#cloud-config
rancher:
write_files:
  - path: /etc/rc.local
    permissions: "0755"
    owner: root
    content: |
      #!/bin/bash
      wait-for-docker
      docker run xxxxx
```
https://rancher.com/docs/os/v1.x/en/installation/configuration/running-commands/#running-docker-commands
