### ISSUE TITLE
ros install V.S wget "certificate signed by unknown authority"

### ISSUE THREAD

**Issue by axi92** [rancher/os#2864]
**RancherOS Version: 1.5.3**

**Where are you running RancherOS: baremetal, vmware

When I do:
`sudo ros install -c https://domain.cloud/cloud-config.yml -d /dev/sda -f`
I get an error with the certificate.
That is ok because it is a self signed one.
But how do I overrule this and ignore the certificate check?

I also make my rancher-vmware.iso with some changes in the `os-config.tpl.yml`
I add rancher.cloud_init.datasources: - url:https://domaincloud/cloud-config.yml

Maybe there is also the problem that at first boot from the iso this cloud-config.yml can not be properly loaded. Because rancher do not trust the cert.

On the other side wget works.
So I tried this in my `os-config.tpl.yml`
```
rancher:
  write_files:
    - path: /etc/rc.local
      permissions: "0777"
      owner: root
      content: |
        #!/bin/bash
        if ! blkid | grep -q "RANCHER_STATE"; then wget https://domain.cloud/cloud-config.yml; sudo ros install -c cloud-config.yml -d /dev/sda -f; fi
```
That should be only run on first boot from iso to write in on the disk.

The purpose of this is to change the cloud-config.yml but just only need to make the iso not every time I need changes.
