### ISSUE TITLE
pxe and network bonding

### ISSUE THREAD

**Issue by justinrush** [rancher/os#2879]
**RancherOS Version: v1.5.3**

**Where are you running RancherOS? baremetal**

Background:
We're using poweredge C series nodes from Dell as our baremetal hosts.  We have 4 interfaces on each box and want to have them bonded together for increased availability.  We are PXE booting them and our PXE image is pulling the cloud config from artifactory on boot.  We're really hoping to have this be a generic cloud config per model/build rather than having one for each host.  Struggling to build the cloud config because we have a DHCP reservation for each server based on the MAC address for the NIC that is being used for PXE booting.  When writing the cloud config, I can't specify either hostname or IP address since we want to use this generically across all servers.  So I can't just build the config with all the interfaces slaved to bond0 because I need the DHCP request to come from eth0's MAC, so it hits a specific DHCP reservation to get the hostname.  I tried something jenky like the below just  to see if it would work, but the file fails validation due to one of the special characters I'm using.

My questions:
1. If you using a single cloud config file, how do you customize the IP address and hostname?
2. Any idea what special character I need to omit or how to escape it?

```yaml
rancher:
  network:
    interfaces:
      bond0:
        dhcp: false
      eth0:
        dhcp: true
      eth1:
        dhcp: false
        bond: bond0
      eth2:
        dhcp: false
        bond: bond0
      eth3:
        dhcp: false
        bond: bond0
runcmd:
- IP="`ifconfig eth0 |grep -o "inet addr:[0-9\.]\+" |awk -F: '{print $2;}'`" 
- MASK="`ifconfig eth0 |grep -o "Mask:[0-9\.]\+" |awk -F: '{print $2;}'`" 
- GW="`route |grep ^default |awk '{print $2;}'`"
- ip link set eth0 down
- etho "+eth0" >/sys/class/net/bond0/bonding/slaves
- ifconfig bond0 ${IP} netmask ${MASK}
- route add default gw ${GW}
```

FWIW, we're setting options 1, 12, 66, and 67 in the DHCP reservation.
```
