### ISSUE TITLE
autoinstall RancherOS on Proxmox with Cloud-init

### ISSUE THREAD

**Issue by mizbanpaytakht** [rancher/os#2899]
Hi,

I tried to autoinstall RancherOS inside a VM in Proxmox but I have problem.
Can you help me on this issue ?

I create a VM and mount rancheros-proxmox-ve iso in CDRom
and via Cloud-init I create this file:

```
#cloud-config
rancher:
 network:
  interfaces:
   eth0:
    address: 10.10.10.5/24
    gateway: 10.10.10.1
    mtu: 1500
    dhcp: false
  dns:
   nameservers:
   - 178.22.122.100
   - 185.51.200.2
write_files:
  - path: /opt/rancher/bin/install.yml
    permissions: "0700"
    content: |
      #cloud-config
      rancher:
       network:
        interfaces:
         eth0:
          address: 10.10.10.5/24
          gateway: 10.10.10.1
          mtu: 1500
          dhcp: false
        dns:
         nameservers:
         - 8.8.8.8
      ssh_authorized_keys:
       - ssh-rsa AAAAB3NzaC1yc2EAAAABJQAAAQEAu+cJj5HKIb7P9tTM9KE+9Zj5L+jWBh4KcCovonJvv9NwUPykEp4iSzATwrPr/8QtQEnsSuoZiQldt+XuAs7gOhMksrhPFNmS7C3efxwWLJvPqbXrSIBGkDFNss64bL+lhyDZvZ6jkihS+QuI9D4gKhKfcdjrgyWSe7OwAgrfsw5thZ9l2i/tG6yTjqhrPIsyUzPYtfn5QUcLuCd1+vO5J0TX0a8JZtob0bzHX4kJcCh44LWO7aA0wL7ti6BPNOEGISRk2VhyFuhCTCNZTznMplPcpqdTDEd1T0YAvS2nQNXcFGVgb0m04Abj61FRKUBBHXFZS6X5wEC98B5e5CtTvDlw== rsa-key-20190921
  - path: /opt/rancher/bin/start.sh
    permissions: "0700"
    content: |
      #!/bin/bash
      echo Y | sudo ros install -f -c /opt/rancher/bin/install.yml -d /dev/sda
```

qm set 1001 --cicustom user=cephfs:snippets/config-1001.yml

When I boot the machine its not used the config file.
