### ISSUE TITLE
Cannot set DNS with 'ros config set' when dns set to null

### ISSUE THREAD

**Issue by mgigante** [rancher/os#2913]
**RancherOS Version: v1.5.4**

**Where are you running RancherOS? VirtualBox v6.0.12**

If I set the RancherOS DNS to null by editing `/var/lib/rancher/conf/cloud-config.yml`, all successive sets fail to set an actual nameserver with `ros config set`.

```
[rancher@rancheros ~]$ sudo head /var/lib/rancher/conf/cloud-config.yml
rancher:
  dns: null
  network:
    interfaces:
      eth0:
        address: 10.1.2.3/24
        dhcp: false
        gateway: 10.1.2.1
[rancher@rancheros ~]$ sudo ros config get rancher.network.dns.nameservers
[]
```
In such a condition setting the nameserver has no effect:

```
[rancher@rancheros ~]$ sudo ros config set rancher.network.dns.nameservers "['8.8.8.8']"
[rancher@rancheros ~]$ sudo ros config get rancher.network.dns.nameservers
[]

[rancher@rancheros ~]$ sudo head /var/lib/rancher/conf/cloud-config.yml
rancher:
  network:
    dns: null
    interfaces:
      eth0:
        address: 10.1.2.3/24
        dhcp: false
        gateway: 10.1.2.1
  services_include:
    kernel-extras: true
```

As a note, I reached the `dns: null` condition by remotely running `ros config set` via ssh in a way I cannot reproduce at the moment; so for the sack of describing the problem I manually edited the cloud-config.yml.
