### ISSUE TITLE
Ability to send ROS logs to syslog endpoint with TLS

### ISSUE THREAD

**Issue by axeal** [rancher/os#2949]
**RancherOS Version: (ros os version)**

v1.5.5

**Where are you running RancherOS? (docker-machine, AWS, GCE, baremetal, etc.)**

User would like the ability to send RancherOS logs via syslog to a TLS protected endpoint, with the ability to specify their own CA for the endpoint also.

**Comment by ryansch** [comment]
If it's helpful, I used the following pattern to replace the syslog container to stream logs to papertrail:
```
  services:
    syslog:
      image: outstand/syslog-ng-papertrail:latest
      labels:
        io.rancher.os.scope: system
      log_driver: json-file
      net: host
      uts: host
      privileged: true
      restart: always
      volumes_from:
        - command-volumes
        - system-volumes
      environment:
        - LOG_DESTINATION=${log_destination}
```
