### ISSUE TITLE
Air Gap: document private registry for system-docker (cloud-config mode)

### ISSUE THREAD

**Issue by finkr** [rancher/os#2951]
**RancherOS Version: (ros os version)**
1.5.4

**Where are you running RancherOS?**

Baremetal

The [air-gap](https://rancher.com/docs/os/v1.x/en/installation/configuration/airgap-configuration/#configuring-private-docker-registry) installation page should document how to configure the private registry for cloud-config mode

As explained by [janeczku](https://gist.github.com/janeczku/02302dae3fbfa011f4f7a60df2b5f24e), I have set:

```yaml
rancher:
  # some stuff here...
  # Configure private registry
  bootstrap_docker:
    registry_mirror: "https://private-mirror.internal"
  docker:
    registry_mirror: "https://private-mirror.internal"
  system_docker:
     registry_mirror: "https://private-mirror.internal"
```
