### ISSUE TITLE
Make udev rules trigger after reboot

### ISSUE THREAD

**Issue by manutenfruits** [rancher/os#2952]
**RancherOS Version: v1.5.4**

**Where are you running RancherOS? Proxmox VM**

I have a USB stick that I want to set up udev rules for. I have created the following file:

```
# /var/lib/rancher/conf/cloud-config.d/udev_config.yml
write_files:
- path: /etc/udev/rules.d/99-z-wave-stick.rules
  container: udev
  permissions: "0644"
  owner: root
  content: |
    SUBSYSTEM=="tty", GROUP="dialout", ATTRS{interface}=="HubZ Z-Wave Com Port", SYMLINK+="zwave"
    SUBSYSTEM=="tty", GROUP="dialout", ATTRS{interface}=="HubZ ZigBee Com Port", SYMLINK+="zigbee"
```

The rules are in the udev system container, but they're not being applied. I have to manually run `system-docker exec -it udev udevadm trigger` after every reboot. 

What I have tried (no success):

```
runcmd:
- system-docker exec -it udev udevadm trigger
```

```
write_files:
- path: /etc/rc.local
  permissions: "0755"
  owner: root
  content: |
    #!/bin/bash
    wait-for-docker
    system-docker exec -it udev udevadm trigger
```
I have also tried `ros udev-settle` but I can't find any documentation on it, so I'm not sure how to use it or if it applies to this case.

Any ideas?
