### ISSUE TITLE
RancherOS Does not respect DHCP option 119 (domain-search)

### ISSUE THREAD

**Issue by AntonSmolkov** [rancher/os#2978]
**RancherOS Version: (ros os version)**
1.5.5
**Where are you running RancherOS? (docker-machine, AWS, GCE, baremetal, etc.)**
VM and docker-machine

Because of this, deployed K8s pods don't have nods's domain in a list of search domains, and, therefore can't resolve short names from outside of the cluster.

**Comment by AntonSmolkov** [comment]
BTW, cloud-config described  [here ](https://rancher.com/docs/os/v1.x/en/installation/networking/dns/)  overrides the whole resolv.conf file and leaves only "search" parameter.

So, AFAIK, the only valid workaround by this time:

```
write_files: 
  - container: network
    content: "search yourdomain.local\n"
    owner: root
    path: /etc/resolv.conf.head
    permissions: "0444"
```
