### ISSUE TITLE
Is this project still alive?

### ISSUE THREAD

**Issue by evilhamsterman** [rancher/os#3000]
There has only been 5 commits since the last release and even that release was running a fair amount of older software. 
* Kernel: 4.14 (2017 LTS but sad that it is still being used #2750 #2728 #2972 )
* SSH: 7.9 (2018)
* Docker: 19.03.5 (this is reasonable updated but there are several point releases since then that aren't available despite every previous version being available)

There are several major issues that don't appear to being addressed.
* UEFI boot #2251 
* IPv6 #2593 
* RaspberryPi 4 support #2875

There have been lots of commits to k3os so it appears that is where Rancher is putting its efforts now. If that is the case it would be nice to know and know if there is a migration plan?

**Comment by rouing** [comment]
I am going with a fat NO right now. While there is plenty of options out there, I personally love RancherOS' way of handling things. The next best option has been SmartOS. I have forked RancherOS and started my own personal build. Seems like this is the only option.

**Comment by nathanweeks** [comment]
https://support.rancher.com/hc/en-us/articles/360041771072#development-status-0-0

**Comment by evilhamsterman** [comment]
Thank you @nathanweeks. Unfortunately that is a blurb behind a login so it isn't indexed on search engines and groups using the Open Source version with support may not find it. It would be nice if that information was posted on the RancherOS docs and on this Repo.

For those of you who can't don't want to login this is what the above article states 

> RancherOS 1.x is currently in a maintain-only-as-essential mode.  That is to say, it is no longer being actively maintained at a code level other than addressing critical or security fixes.  There are two significant reasons behind this product decision:
>
> 1. Docker.  The current industry requirements for a container runtime is very much evolving.  Container runtimes like containerd and CRIO are now being actively considered as the default choice.  RancherOS 1.x, which was specifically designed around using Docker engine only, unfortunately does not lend itself, in its current design, to this new evolving requirement.  To address this situation, at Rancher Labs, we are currently working on new technologies such as K3OS that leverages k3s constructs built on containerd.  When done, it is a desired outcome for us to be able to offer K3OS as a RancherOS 2.0 alternate. 
> 2. ISV Support.  RancherOS was specifically designed as a minimalistic OS to support purpose-built containerized applications.  It was not designed to be used as a general purpose OS (such as CentOS or Ubuntu).  As such, most ISVs have not certified their software to run on RancherOS, nor does RancherOS even contain the necessary components for many of these applications to run.  For the K3OS project, our outlook is to investigate the viability of technologies like AWS Bottlerocket that can be used as the default general purpose OS and leverage its ecosystem of compatible ISVs.

I'm fine with the reasoning but it needs to be made clear so people don't start using RancherOS

**Comment by infinytum** [comment]
+1 for this issue. Just as I was finished setting up rancher os for a cluster, I got to see this.

**Comment by mfld** [comment]
agreed. +1

**Comment by mathieubodin** [comment]
+1 

Just like @infinytum ... It's sad it's been abandoned  because I liked how RancherOS worked. I will now move to Debian as it lives like forever ! See U

**Comment by askawu** [comment]
+1
Thanks @evilhamsterman for the information.

**Comment by olljanat** [comment]
Based on https://rancher.com/support-maintenance-terms/ Rancher OS will hit end of maintenance on 29th of December and end of life 29th of June 2021. 

I assume that here is also others who are not planning to use Kubernetes which why k3os is not option for them but are you:
a) planning to migrate some other OS?
b) interested to contribute if we create community maintained fork of Rancher OS and its main repositories?

IMO, minimum level to keep project going is to have enough people who will participate to create/review pull requests of updated kernel + docker versions. Based their needs we probably can simplify that work by minimizing number of supported configurations and increasing level of automation.

because Github is not optimal solution for this kind of voting I created simple poll of it: http://www.rkursem.com/poll/view.php?id=00ada0fcb862bb1ad

**Comment by olljanat** [comment]
Looks that there might be enough couple who are willing to participate so I created https://github.com/rancher-os-community project, forked all needed repositories to there and started to setup build automation.

Please look readme and issues on https://github.com/rancher-os-community/os and let's continue discussion on there.

**Comment by x-jokay** [comment]
I would migrate to [Fedora CoreOS](https://getfedora.org/en/coreos?stream=stable) :wink:

**Comment by olljanat** [comment]
@x-jokay yea that looks to be valid option. I have ignored FCOS earlier as its documentation is quite terrible from getting stated point of view but this one looks to be better for that purpose https://computingforgeeks.com/install-fedora-coreos-fcos-on-kvm-openstack/

Some comments/tips for others who are considering to which to FCOS:
* If you want use swarm you need override /etc/sysconfig/docker file with version which does not include `--live-restore` switch.
* FCOS looks to be prefer [Podman](https://podman.io/) instead of Docker but both of those are installed. [Here](https://docs.fedoraproject.org/en-US/fedora-coreos/faq/#_can_i_run_containers_via_docker_and_podman_at_the_same_time) is also guide how to disable Docker but not how to disable Podman.
* Afaik it is not possible to force specific Docker version on FCOS like it is on Rancher OS.

So here is my version getting started `fcos.fcc` file for Rancher OS users:
```yaml
variant: fcos
version: 1.0.0
passwd:
  users:

  # To simplify migration from Rancher OS
  # we are still using "rancher" as username
  - name: rancher
    groups:
    - sudo
    - docker
    ssh_authorized_keys:
    - ssh-rsa <ssh-pub-key>

storage:
  files:
  # Override default Docker config because:
  # --live-restore is not supported with Swarm mode
  - path: /etc/sysconfig/docker
    overwrite: true
    contents:
      inline: |
        OPTIONS="--selinux-enabled \
        --log-driver=journald \
        --storage-driver=overlay2 \
        --default-ulimit nofile=1024:1024 \
        --init-path /usr/libexec/docker/docker-init \
        --userland-proxy-path /usr/libexec/docker/docker-proxy \
        "
```

Just update public key to it and convert to Ignition format using command:
```bash
docker run -i --rm quay.io/coreos/fcct --strict < fcos.fcc > fcos.ign
```
And then you are able to deploy FCOS where you can still login with rancher user and use docker commands and Docker Swarm features with it 😄

PS. I did not yet decided switch to FCOS and I will most probably play with that Rancher OS community fork still at least because of Raspberry Pi when if we decide migrate production workloads to FCOS.
