### ISSUE TITLE
Renewing ros ca-certificates

### ISSUE THREAD

**Issue by ibox4real** [rancher/os#3062]
**RancherOS Version: (ros os version)** 
v1.5.4, v1.5.6, v1.5.7

**Where are you running RancherOS? (docker-machine, AWS, GCE, baremetal, etc.)**
AWS

Yesterday Lets Encrypts DST Root CA X3 expired. Because of that `docker pull my-custom-regsitry` now gives `x509: certificate has expired or is not yet valid`. 

How do i force renew the ca-certificates on ros?

**Comment by stove-panini** [comment]
We just ran into this yesterday.

1. Grab the R3 cert here: https://letsencrypt.org/certs/lets-encrypt-r3.pem
2. Copy it to `/etc/docker/certs.d/your.registry.com:4567/ca.crt`

It will get picked up automatically with no need to restart any services.

I'm trying to find a way to get this into User Data for new nodes but I can't see a way to do that in Rancher's Node Templates.

**Comment by ibox4real** [comment]
> We just ran into this yesterday.
> 
> 1. Grab the R3 cert here: https://letsencrypt.org/certs/lets-encrypt-r3.pem
> 2. Copy it to `/etc/docker/certs.d/your.registry.com:4567/ca.crt`
> 
> It will get picked up automatically with no need to restart any services.
> 
> I'm trying to find a way to get this into User Data for new nodes but I can't see a way to do that in Rancher's Node Templates.

Thank you for the response! I figured the manual cert upload thing would work as a quick solution but hoped for an easier solution.

 For now i just decided to drop ros alltogether and use amazon linux with docker instead. 
 
 If it is any help, i used this cloud-config in the user data  with ros. Maybe you can customize it to add the cert, but i believe the user data is executed only on first boot.
 ```
 #cloud-config
write_files:
  - path: /etc/rc.local
    permissions: "0755"
    owner: root
    content: |
      #!/bin/bash
      wait-for-docker
      sudo docker run rancher-agent ...
 ```
