### ISSUE TITLE
start.sh not starting "busydash" container

### ISSUE THREAD

**Issue by DJviolin** [rancher/os#393]
I placed start.sh in:
opt/rancher/bin
it should automatically restart the services after reboot, but it simply not restarting busydash, which is called by system-docker.

```
#!/bin/sh

sudo system-docker start busydash
docker start ecstatic_kirch
docker start rancher-agent
docker start nginx
```

Permission of the file:
```
-rwxr-xr-x    1 rancher  rancher        119 Jun 19 13:32 start.sh*
```
Another problems are nginx always exiting after 3-5 minutes, plus after restarts I have multiple duplicates of the "rancher" host under Infrastructure tab. Only one of them having the Docker containers, the others are empty. If I turn off one of them, it will turn off all of them. Same to deletion. Why is that?

![fireshot screen capture 005 - rancher - 172_19_8_101_8080_static_infrastructure_hosts](https://cloud.githubusercontent.com/assets/5021728/8258075/6d7c2226-16b2-11e5-935a-d4f04b36d209.png)

**Comment by DJviolin** [comment]
I found vi in the directories, know I can edit files. The question is though I still need to edit .dockerinit and place start.sh's location there to keep alive the docker container after restarts?

**Comment by deniseschannon** [comment]
The multiple containers in Rancher is due to this issue: https://github.com/rancherio/rancher/issues/936

We've made the fix in Rancher, but the we need a release to make the fix in RancherOS. 

@imikushin would you be able to help answer the restart issue?

**Comment by imikushin** [comment]
I'd recommend moving service start logic from `start.sh` to a [compose template](https://docs.docker.com/compose/yml/), as it's now the primary mechanism of running services in RancherOS. For documentation how to run services off compose templates, see http://os.docs.rancher.com/docs/configuration/system-services/ 

Your example in compose syntax would look similar to this:
```yml
busydash:
  image: my-images-prefix/busydash-image:latest
  labels:
  - io.rancher.os.scope=system  # use this label if you want to run the container with system-docker
  restart: always               # use this if this container is a daemon

ecstatic_kirch:
  image: my-images-prefix/whatever-it-is:v0.1.0
  restart: always

nginx:
  image: nginx
  ports:
  - "80:80"
  restart: always
```

Also, you don't need to start `rancher-agent` using any start script or compose template, as it is started automatically by docker on system boot (because it has `--restart=always`).
