### ISSUE TITLE
Pre-login to private repo

### ISSUE THREAD

**Issue by colebrumley** [rancher/os#423]
I am trying to enable a service that runs an image from a private repo, but adding the repo's auth to `~/.dockercfg` and/or `/root/.docker/config.json` does not apply the authentication until after boot.  Similarly, if I manually run `docker login my.repo.com`, the creds are saved appropriately, but on reboot the service still fails, presumably because the login info hasn't been applied yet.  If I wait until after boot and login normally, the image pulls fine. The console logs show:

![image](https://cloud.githubusercontent.com/assets/5015139/8479020/b63d8bac-209a-11e5-914c-ded33cb45856.png)

Is there a way to pre-login to a private repo that persists and is applied pre-boot?

In case it helps, I tried adding links to network and cloud-init in the service file thinking that may delay the service starting long enough for the creds to be applied, but no luck.  Here's what the service looks like now:

```
yolk:
  image: docker-repo.gonkulator.io/gonkulator/yolk:latest
  links: 
    - network
    - cloud-init
  ports:
    - "8000:8000"
  restart: always
  tty: true
  stdin_open: true
  volumes:
    - "/var/lib/rancher/conf:/var/lib/rancher/conf"
    - "/usr/bin/ros:/usr/bin/ros"
    - "/sbin/reboot:/sbin/reboot"
```

I have tried on RancherOS v0.3.1 and v0.3.2rc4.  Neither works, but I only saw the auth message on v0.3.2rc4
