### ISSUE TITLE
Using ros from inside a system-docker container

### ISSUE THREAD

**Issue by colebrumley** [rancher/os#453]
How do I map the `ros` binary into a `system-docker` container so that I can enable services from inside it?  I have a 'bootstrap' container that runs on system-docker and is supposed to take user input via a web GUI, generate a Rancher service file, enable it, and reboot the box.  The service file is generated and the reboot command works, but ros is not in `$PATH` so the `ros s enable` command fails.

Here's the bootstrap service file so you can see the config I'm using.  I've tried several permutations of mapping `/usr/bin/ros`, `all-volumes`, and links with no luck.  I have the sneaking suspicion that I am missing something obvious...
```
yolk:
  image: yolk:test
  privileged: true
  links:
    - cloud-init
  ports:
    - "8000:8000"
  restart: always
  environment:
    - "URL=https://192.168.1.113:8443/rest/ova"
    - "TLS_NO_VERIFY=1"
    - "MTIAAS_LOGDIR=/var/log"
  labels:
    - io.rancher.os.scope=system
  volumes:
    - /var/lib:/var/lib
    - /var/run/docker.sock:/var/run/docker.sock
  volumes-from:
    - all-volumes
  ipc: host
  pid: host
```
What am I missing?
