### ISSUE TITLE
Streamline adding SSL intermediate CA certs

### ISSUE THREAD

**Issue by itzg** [rancher/os#470]
Our corporate network is using a transparent proxy at the internet gateway, so SSL connections to pull images from the public registry fail (i.e. get hijacked with an SSL cert switch-out) with errors like:

```
level=error msg="Error from V2 registry: Get https://dseasb33sr
nrn.cloudfront.net/registry-v2/docker/registry/v2/blobs/sha256/e9/e9c5e611068deac3cdd6ddc72a7df7329ac
06dcdb8b864ca8f54cd8ddd4ab435/data?Expires=1438891455&Signature=EArIeoglPpT0qPGrJujNdGC6aTJxde10~2Yq5
FVKppEXIfQGi7uotBMCoVSahzNTNv~~RCObzmPieel-RPN5ogZadBb4sYpRbIFhE7g56ZcGxAGMhtm6ARBDu20U~dOJn6tsM~ASrb
uZZKsQqsFY~jlRa7MNRXkh1l-KEluxf3E_&Key-Pair-Id=APKAJECH5M7VWIS5YZ6Q: x509: certificate signed by unknown authority"
```

To solve this I am using the `write_files` cloud config directive to place the PEM files into `/etc/ssl/certs` (with the extension `.pem`). I also use `write_files` to create the script `/opt/rancher/bin/start.sh` with the content:

      #!/bin/bash
      for p in /etc/ssl/certs/*.pem; do
        cat $p >> /etc/ssl/certs/ca-certificates.crt
      done

It would be really nice if the RancherOS init sequence could automatically update the `ca-certificates.crt` file when individual PEM files are present. Or better yet, introduce a section in the rancher cloud-config (and `rancher.yml`) to convey intermediate CA certs to install.

**Comment by imikushin** [comment]
@itzg Your solution looks pretty nice, actually. I'd use a system service container started with cloud-config, e.g.:
```
#cloud-config
rancher:
  services:
    cert-munger:
      image: my/cert-munger
      volumes:
      - /etc/ssl/certs:/etc/ssl/certs
      labels:
        io.rancher.os.detach: false
        io.rancher.os.scope: system        
        io.rancher.os.after: network
``` 
How are you doing the same on a "normal" Linux (like Ubuntu)? Asking, because in an upcoming release, the console containers will become persistent by default (it's ephemeral now), so it's going to be easier to do stuff "the usual way".
