### ISSUE TITLE
v0.4.0 - unable to use ros config import for rancher key.

### ISSUE THREAD

**Issue by deniseschannon** [rancher/os#493]
`sudo ros config import -i cc.yml`

`cc.yml` file
```
#cloud-config
ssh_authorized_keys:
  - SSH KEY
```

cloud-config-local.yml
```
ssh_authorized_keys:
- SSH KEY
```

white spacing in yaml file import was dropped.

**Comment by deniseschannon** [comment]
Whitespacing for arrays is okay. but i'm having issues importing information under the rancher key.

Importtest.yml File:
```
rancher:
  network:
    dns:
      domain: myexample.com
```

Nothing is saved in cloud-config-local.yml if I run a `sudo ros config import -i importtest.yml`

**Comment by imikushin** [comment]
Nothing should be saved, because your config is invalid :stuck_out_tongue_winking_eye:
`domain` isn't recognized as a valid subkey under `rancher.network.dns` key, so the imported config ends up being empty. 

I tried this input instead, and it worked perfectly:
```
#cloud-config
rancher:
  network:
    dns:
      nameservers: [208.67.222.222, 208.67.220.220]
```
