### ISSUE TITLE
v0.4.0-rc1: ros config export prints out information in rancher key on fresh install

### ISSUE THREAD

**Issue by deniseschannon** [rancher/os#498]
I'd expect that `ros config export` to print out only what is in the cloud-config-local.yml.

With a fresh iso install and no changes, if i run the command, it shows in the rancher key.

```
rancher:
  state:
    autoformat: 
      - /dev/sda
      - /dev/vda
```

I would expect that it would be blank like the cloud-config-local.yml file is 
```
sudo cat /var/lib/rancher/conf/cloud-config-local.yml
{}
```
