### ISSUE TITLE
list of which folders are persistent across reboot?  

### ISSUE THREAD

**Issue by gregory** [rancher/os#499]
Would be nice to have some doc on which folders are persistants and which are not. 
i booted from ipxe, and i've setup this in my cloud-config.yml 
```yml
state:
    fstype: auto
    dev: LABEL=RANCHER_STATE
    autoformat:
      - /dev/vda
```
looks like the home/rancher is persisted across reboots where not all the folders in the /var/ are...
