### ISSUE TITLE
Weave DNS to manage DNS within RancherOS?

### ISSUE THREAD

**Issue by miztiik** [rancher/os#500]
Does weave work within RancherOS? or does Rancher OS has its own DNS setup to allow inter-container n/w setup?

**Comment by ibuildthecloud** [comment]
Weave should work fine.  RancherOS purposely doesn't have a cross networking solution.  It is designed to just be the Docker daemon really.  Once Docker has full cross host networking then RancherOS will support that too.  You might look at our other (completely separate) product Rancher (http://github.com/rancher/rancher).  That product provides cross host networking, service management, DNS, load balancing, service discovery, and more.

**Comment by colebrumley** [comment]
I'm late to the party but FYI Weave is perfectly happy on ROS, I've been running it with no issues for weeks.

**Comment by voobscout** [comment]
@colebrumley Mind sharing how you got weave to launch on start-up? /opt/rancher/bin/start.sh executes before docker, so a "weave launch" doesn't work from there. I couldn't find any docu on what runs after docker starts or if there is infact such a thing.

**Comment by colebrumley** [comment]
@voobscout Sure, I just made a system service with an `-io.rancher.os.after: docker` [label](http://docs.rancher.com/os/configuration/system-services/#labels) so that it'd wait to start until after user-docker is up.  The container is nothing special, it's just running the Weave script from their [releases](https://github.com/weaveworks/weave/releases) page.

Here's the service file I dug up from my lib folder. I'm _pretty_ sure this was the working version ;)

```yaml
weave:
  image: your-weave-container
  container_name: weave
  privileged: true
  labels:
    io.rancher.os.scope: system
    io.rancher.os.after: docker,console
  volumes_from:
    - all-volumes
  net: host
```
