### ISSUE TITLE
Support Amazon ECS

### ISSUE THREAD

**Issue by deniseschannon** [rancher/os#603]
Add http://docs.aws.amazon.com/AmazonECS/latest/developerguide/ECS_agent.html so that RancherOS supports ECS

**Comment by imikushin** [comment]
RancherOS is easy to use as ECS Container Instances. Start RancherOS EC2 instances with the following user-data: 

```yml
#cloud-config
rancher:
  environment:
    ECS_CLUSTER: your-ecs-cluster-name
  services_include:
    amazon-ecs-agent: true
```

Don't forget to choose the ECS Instance Role (e.g. `ecsInstanceRole`) in the **IAM Role** dropdown in the instance creation form.
