### ISSUE TITLE
ECS is unable to pull from private Docker repositories

### ISSUE THREAD

**Issue by schuylr** [rancher/os#632]
Consider the following cloud-config as per [the documentation on accessing private repos for ECS agent](http://docs.aws.amazon.com/AmazonECS/latest/developerguide/private-auth.html):

```
rancher:
  environment:
    ECS_CLUSTER: jewlr-uk
    ECS_ENGINE_AUTH_TYPE: dockercfg
    ECS_ENGINE_AUTH_DATA: '{...}' # Credentials here
# If you have selected a RancherOS AMI that does not have ECS enabled by default,
# you'll need to enable the system-service for the ECS agent.
  services_include:
    amazon-ecs-agent: true
ssh_authorized_keys:
  - ssh-rsa AAA... schuyler@...
```

All configuration works as desired - however the task for a private repository fails with:

>CannotPullContainerError: Error: Status 403 trying to pull repository foo/bar: "{\"error\": \"Permission Denied\"}"

Since the ECS agent seems to work when passing the `ECS_CLUSTER` environment argument through the cloud-config, one would think that `ECS_ENGINE_*` variables would also work. This doesn't seem to be the case.

The `ECS_ENGINE_*` configuration has been tested on the agent directly and works as desired - so the issue doesn't lie with the credentials themselves.

**Comment by wonderslug** [comment]
Im seeing the same thing.  It appears does appear that only the ECS_CLUSTER environment is being applied to the container.

This is what is being applied via the cloud config:
```
#cloud-config
rancher:
  environment:
    ECS_CLUSTER: eng-dashboard
    ECS_ENGINE_AUTH_TYPE: dockercfg
    ECS_ENGINE_AUTH_DATA: '{}'
```

And this is the resulting docker inspect on the ecs-agent:
```
"Config": {
        "Hostname": "e06af9cc720d",
        "Domainname": "",
        "User": "",
        "AttachStdin": false,
        "AttachStdout": false,
        "AttachStderr": false,
        "ExposedPorts": {
            "51678/tcp": {}
        },
        "Tty": false,
        "OpenStdin": false,
        "StdinOnce": false,
        "Env": [
            "ECS_LOGFILE=/log/ecs-agent.log",
            "ECS_LOGLEVEL=info",
            "ECS_DATADIR=/data",
            "ECS_CLUSTER=eng-dashboard",
            "PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin"
        ],
        "Cmd": null,
        "Image": "amazon/amazon-ecs-agent:v1.5.0",
        "Volumes": null,
        "WorkingDir": "",
        "Entrypoint": [
            "/agent"
        ],
        "OnBuild": null,
        "Labels": {
            "io.docker.compose.config-hash": "5763cc96eeb8208e8c47ee5563f415224cb19e82",
            "io.docker.compose.name": "os_ecs-agent_1",
            "io.docker.compose.project": "os",
            "io.docker.compose.service": "ecs-agent",
            "io.rancher.os.after": "docker",
            "io.rancher.os.scope": "system"
        }
    }
```
