### ISSUE TITLE
Add cloud-config, reboot breaks system-docker returning FATA[0000] no such file or directory

### ISSUE THREAD

**Issue by flaccid** [rancher/os#641]
In v0.4.0 (did not occur in earlier releases) I add the following to `/var/lib/rancher/conf/cloud-config.d/nfs.yml`.

```
#cloud-config

# /var/lib/rancher/conf/cloud-config.d/nfs.yml

rancher:
  docker:
    # This must be the name of the service that provides the storage.  Docker will run this container.
    storage_context: nfs

  services:
    nfs:
      # no longer required in v0.4.0
      # log_driver: json-file

      # Your custom image
      image: flaccid/nfs-client

      # Everything below is required to be set so that Docker can run properly
      labels:
        io.rancher.os.after: console
        io.rancher.os.scope: system
      net: host
      pid: host
      uts: host
      ipc: host
      privileged: true
      restart: always
      volumes_from:
      - all-volumes
      volumes:
      - /usr/bin/iptables:/sbin/iptables:ro
      - /mnt/nfs-1
      environment:
        SERVER: 192.168.0.9
        SHARE: movies
```

After reboot the `system-docker` command returns `FATA[0000] no such file or directory`.

**Comment by imikushin** [comment]
On master branch we're using the bundled docker binary (`/usr/bin/docker.dist`), so `system-docker` actually works, but `docker` doesn't. The odd thing about it is:
```
[root@rancher-dev ~]# ls -lAh /usr/bin/docker
ls: /usr/bin/docker: No such file or directory
```
That explains why system-docker in v0.4.0 doesn't work in this setup (because in v0.4.0 it uses `/usr/bin/docker`). But this leaves an open question: where the heck is the symlink that is normally there? 

Continuing w/ investigation.

**Comment by imikushin** [comment]
This happens because `dockerlaunch` looks for docker binary in the storage context container (in this case, "nfs"). 

@ibuildthecloud: I wonder if this is the designed behaviour? If yes, then we should document this in the requirements for docker storage context containers. 

If not, let's discuss how to fix. I'm not exactly sure if we can (or at all should!) launch docker from within console to work in the context of yet another container.

**Comment by ibuildthecloud** [comment]
Here's what's going on.  We bind mount docker to `/usr/bin/docker.dist` and not `/usr/bin/docker`.  On boot when user docker starts we symlink `/usr/bin/docker -> /usr/bin/docker.dist`.  The reason for this is that I didn't want to bind mount our packaged docker to `/usr/bin/docker` because then a user can't change that binary due to the bind mount.

@flaccid In your case what is happening is that since user docker is running in the `nfs` container and not the `console` container, we don't setup the symlink in the console.  The `system-docker` command just does an exec of `/usr/bin/docker`.  The simple work around is to add

```yaml
#cloud-config
write_files:
  - path: /etc/rc.local
    permissions: "0755"
    content: |
      #!/bin/bash
      [ ! -e /usr/bin/docker ] && ln -s /usr/bin/docker.dist /usr/bin/docker
 ```

@imikushin This should be a simple fix on our side.  We should just add this symlink to the images (console, ubuntu/debian console) and not rely on the symlink being created on startup.
