### ISSUE TITLE
Cloud config not applied

### ISSUE THREAD

**Issue by shakefu** [rancher/os#657]
It seems that RancherOS is not applying the cloud-config when applied using terraform user_data.

I've been trying to get RancherOS (`v0.4.0`, `ami-0f1fdc4b`) to start rancher/server as a system service (mostly for entertainment).

Here's the relevant bit of the .tf: 

```tf
# plex.tf
resource "aws_instance" "plex" {
    ami = "ami-0f1fdc4b"
    availability_zone = "us-west-1b"
    instance_type = "m2.xlarge"
    security_groups = [ "allow_all" ]
    key_name = "plex"

    user_data = "${file("plex.yml")}"

    tags {
        Name = "plex"
    }
}
```

And the user data:
```yml
# plex.yml
hostname: plex
rancher:
  services_include:
    debian-console: true
write_files:
  - path: "/var/lib/rancher/conf/rancher_server.yml"
    permissions: "0644"
    owner: "root"
    content: |
      rancher_server:
        image: rancher/server
        restart: always
        privileged: true
        ports:
          - "8080:8080"
```

On the host itself, the boot.yml is empty, and the cloud-config.yml just the ssh_authorized_keys entry, with the same key repeated several times. It's also readily apparent that the debian-console setting isn't applied, which I can verify with `sudo ros config dump --full`.

Here's the repo I've been fooling around in, which hopefully can be used to replicate: https://github.com/shakefu/plex

Edit: Also, the rancher_server.yml doesn't get written.
