### ISSUE TITLE
Define ip routes in cloud-config.yml

### ISSUE THREAD

**Issue by Mrono** [rancher/os#660]

**Comment by prologic** [comment]
+1

**Comment by ibuildthecloud** [comment]
This is supported in the next release through "post run" commands.  So just add the `ip route add` in the cloud config.  I'll update the issue as we add documentation.

**Comment by prologic** [comment]
:+1:


James Mills / prologic

E: prologic@shortcircuit.net.au
W: prologic.shortcircuit.net.au

**Comment by CBR09** [comment]
+1 for this

**Comment by pwFoo** [comment]
Great "post run" commands should fix my problem with static routes and additional ip addresses from #400. So ip route, ip addr and other commands should work?

Is there a planned date for the new release? Maybe I could delay my new setup until RancherOS 0.4.3 is released ;)

**Comment by deniseschannon** [comment]
In v0.4.3-rc4, you can add this in the cloud-config and it will add in iproute. 

```
rancher:
  network:
    interfaces:
      eth0:
        dhcp: true
        post_up: 
        - ip route add 10.0.0.1/24 dev eth0
```
