### ISSUE TITLE
cloud-config fails to honor "link:" key on v0.4.1

### ISSUE THREAD

**Issue by sundeer** [rancher/os#683]
This user-data worked on v0.4.0
EC2 -  ami-95c09ff0
```
#cloud-config
rancher:
  services:
    rancher-server:
      image: rancher/server
      restart: always
      name: rancher-server
      ports:
        - 8080:8080

    rancher-tls-proxy:
      image: sundeer/rancher-tls-proxy
      restart: always
      name: rancher-tls-proxy
      link: rancher-server
      ports:
        - 443:443
        - 80:80
```
after switching to v0.4.1 (ami-95c09ff0), the link to rancher-server is not set-up, i.e. - no routes added to rancher-tls-proxy hosts file. I can verify that after switching back to v0.4.0 (ami-95c09ff0), this link works as expected.

**Comment by deniseschannon** [comment]
Just want to confirm that you used the `links` in your config and not `link`.  Since you tested it in v0.4.0 and it's just not working v0.4.1, I'm wondering if it's something with Docker 1.9.x as we didn't make too many changes between the releases except start using Docker 1.9.x.

**Comment by sundeer** [comment]
I'm using ```link``` as shown in my example ```cloud-config``` file and this works as expected with v0.4.0 but fails in v0.4.1.

**Comment by sundeer** [comment]
Using ```links``` with v.0.4.2 works
```
#cloud-config
rancher:
  services:
    rancher-server:
      image: rancher/server
      restart: always
      name: rancher-server
      ports:
        - 8080:8080

    rancher-tls-proxy:
      image: sundeer/rancher-tls-proxy
      restart: always
      name: rancher-tls-proxy
      links:
        - rancher-server
      ports:
        - 443:443
        - 80:80
```
