### ISSUE TITLE
AMI instances aren't configured with Amazon DNS servers

### ISSUE THREAD

**Issue by schuylr** [rancher/os#697]
Using any ros AMI instance, my `/etc/resolv.conf` looks like this:

```
nameserver 8.8.8.8
nameserver 8.8.4.4
```

where it should ideally be more like this (as with many Amazon AMIs):

```
nameserver 172.16.0.23 # Depends on the locale
search ec2.internal
```

These values are rather persistent so I can use the cloud-config, but I wouldn't want it to break if Amazon changed their addressing for whatever reason.

**Comment by ibuildthecloud** [comment]
What version are you running?  This should have been addressed in the latest release

**Comment by schuylr** [comment]
I'm running `ami-11740e7b` which is `rancheros-v0.4.1-hvm-0`

**Comment by schuylr** [comment]
Spoke too soon, this cloud-config doesn't do anything either:

```
rancher:
  network:
    dns:
      search:
        - ec2.internal
      nameservers:
        - 172.16.0.23
```

I could have a mistake in there so please correct me if so. My `/etc/resolv.conf` is still:

```
nameserver 8.8.8.8
nameserver 8.8.4.4
```
