### ISSUE TITLE
Fix resizefs to work again for AMIs

### ISSUE THREAD

**Issue by deniseschannon** [rancher/os#698]
In v0.4.2, the `resizefs` is broken for the AMIs.

**Comment by ryansch** [comment]
Any updates on this?

**Comment by deniseschannon** [comment]
We are looking to cut a new release of RancherOS in the next week or two, but I"m not sure if we'll be able to get this fix into that release. There are some higher priority issues that we're addressing.

**Comment by johnrengelman** [comment]
Is there a workaround for this? If not, I don't see how this isn't high priority itself.

**Comment by ryansch** [comment]
Agreed.  I'm going to have to fix this myself here soon...

**Comment by johnrengelman** [comment]
This just totally bit us. Crashed a bunch of server b/c of disk space.

**Comment by wonderslug** [comment]
You can work around this on a system once its up by running 

`docker run --privileged -i --rm ubuntu bash << EOF
apt-get update
apt-get install -y cloud-guest-utils parted
growpart /dev/xvda 1
partprobe
resize2fs /dev/xvda1
EOF`

But i agree this needs to be fixed in the initial install cause its killing me for auto scaleing groups

**Comment by wonderslug** [comment]
So this got me thinking that this could be added to the cloud-config as a service and it seems to work.

Im dropping this in the user-data and it resizes the volume on initial startup
```
#cloud-config
rancher:
  services:
    update_filesystem_size:
      image: ubuntu
      privileged: true
      command: bash -c 'eval "apt-get update && apt-get install -y cloud-guest-utils parted && growpart /dev/xvda 1 && partprobe && resize2fs /dev/xvda1"' update_filesystem_size
```

It does run everytime there is a reboot but i dont think thats a bad thing because you might resize a volume at some time.
