### ISSUE TITLE
Ignore DNS nameservers configured by DHCP

### ISSUE THREAD

**Issue by quantverse** [rancher/os#720]
Hi,

is is somehow possible to use DHCP for address/gateway configuration, but ignore nameservers coming with it?

I would like to use DHCP, but local nameservers of my cloud provider (Vultr) are quite unreliable. I would prefer to use Google's.

Part of my cloud config:
```yaml
rancher:
  cloud_init:
    datasources:
      - ec2
  network:
    dns:
      nameservers:
        - 8.8.4.4
        - 4.2.2.3
    interfaces:
      eth0:
        dhcp: true
```

But if DHCP is enabled, my nameservers are not used:
```
[rancher@ptl-www-rancher /]$ cat /etc/resolv.conf 
# Generated by dhcpcd from eth0.dhcp
# /etc/resolv.conf.head can replace this line
nameserver 108.61.10.10
# /etc/resolv.conf.tail can replace this line
```

If I disable the DHCP, it starts to work.

I would expect that manually configured DNS servers in cloud-config should have priority over the DHCP. Or there should be some way to force my configuration.

**Comment by ibuildthecloud** [comment]
Try setting 
```yaml
rancher:
  dns:
      override: true
```

**Comment by quantverse** [comment]
I will try, thanks.

**Comment by voobscout** [comment]
I can confirm, that the override option has no effect

**Comment by qrpike** [comment]
Having this same issue as well

**Comment by janeczku** [comment]
Hi @deniseschannon, this is actually not an enhancement but a bug. Overriding the DNS nameservers with values from cloud-config was landed in https://github.com/rancher/os/pull/669. But apparently it does not work as expected.

To reproduce:

```YAML
#cloud-config
(...)
rancher:
  network:
    dns:
      nameservers:
        - 8.8.4.4
        - 4.2.2.3
      override: true
    interfaces:
      eth0:
        dhcp: true
```

> $ sudo netconf

```BASH
(...)
> INFO[0000] Override nameservers                          nameservers=[8.8.8.8 8.8.4.4]
```

But it fails to rewrite /etc/resolv.conf:

> $ cat /etc/resolv.conf

```BASH
# Generated by dhcpcd from eth0.dhcp
# /etc/resolv.conf.head can replace this line
nameserver 108.61.10.10
```
