### ISSUE TITLE
Unable to login to ubuntu-console

### ISSUE THREAD

**Issue by quantverse** [rancher/os#721]
Hello,

while installing via iPXE and using ubuntu-console (configured in cloud-config), I am not able to login via SSH and neither from console.

My SSH keys are not accepted, tried to login as *rancher/rancher* or *rancher/password* too and nothing works.

What is the default password? Or how can I login?

Tested with RancherOS 0.4.2. SSH keys work fine if I disable the ubuntu-console.

**Comment by deniseschannon** [comment]
Note: I've never used iPXE. :)

Can you share your cloud-config? Have you confirmed your cloud-config works fine when booting from another source (not iPXE?)? I just wnat to check that how you're enabling ubuntu console in the cloud-config is set up right. 

Can you try booting RancherOS using iPXE with a cloud-config and no ssh keys? If so, you should be able to login as `rancher/rancher`.

After you use a cloud-config with a SSH key the default username/password (i.e. rancher/rancher) is no longer valid.

**Comment by quantverse** [comment]
Hi,

I've tried to remove SSH keys, but it did not help. This is the cloud-config tested:

```yaml
#cloud-config
hostname: ubuntu-test
rancher:
  services_include:
    ubuntu-console: true
  cloud_init:
    datasources:
      - ec2
  network:
    dns:
      nameserver:
        - 8.8.4.4
        - 4.2.2.3
    interfaces:
      eth0:
        dhcp: true
  state:
   fstype: auto
   dev: LABEL=RANCHER_STATE
   autoformat:
     - /dev/vda
```

This is the iPXE script:
```
#!ipxe
# Boot a persistent RancherOS to RAM

# Location of Kernel/Initrd images
set base-url http://releases.rancher.com/os/latest

kernel ${base-url}/vmlinuz rancher.state.autoformat=[/dev/vda] rancher.state.formatzero=true rancher.cloud_init.datasources=[ec2]
initrd ${base-url}/initrd
boot
```
From the virtual console I can see the ubuntu console is pulled and started successfully.
