### ISSUE TITLE
rancher.state.autoformat fails or improperly documented!?

### ISSUE THREAD

**Issue by voobscout** [rancher/os#723]
cloud-config.yml:
```yml
#cloud-config
rancher:
  state:
    required: true
    fstype: auto
    dev: /dev/sda
    # LABEL=RANCHER_STATE
    autoformat:
      - /dev/sda
      - /dev/vda
```
ipxe script:
```shell
#!ipxe
dhcp
set base-url http://releases.rancher.com/os/latest
kernel ${base-url}/vmlinuz rancher.state.autoformat=[/dev/sda,/dev/vda] rancher.cloud_init.datasources=[url:http://my-cloud-config/yaml.file.txt]
initrd ${base-url}/initrd
boot
```

In the above configuration, the STATE partition never gets created or used.
My requirement is to boot from ipxe and use local /dev/sda for storage/state.
Currently it seems to be unachievable.
Please help!

Thanks.
