### ISSUE TITLE
Support Vault Dynamic OTP ssh Authentication for RancherOS

### ISSUE THREAD

**Issue by blaggacao** [rancher/os#724]
I would like to do something like this:

```yaml
rancher:
  ...
  security:
    ssh:
      vault: 
        enable: true
        mode: otp
        api: <https://api-adress>
```
With the effect to ssh into the OS with a dynamically created (and audited) one time password provided by a vault server. Please have a look at this magnificent feature here:
https://www.vaultproject.io/docs/secrets/ssh/index.html
In short, it solves:
- gone away the hassle of ssh private key management for your rancher instances
- clear request and access auditing included (into vault)
- enabling clear and handy "break glass" emergency strategies if architecture or parts of it are compromised.

If needed, quickly build a mental model of the vault architecture: https://www.vaultproject.io/docs/internals/architecture.html

Basically, the configuration changes invoked by the above config lines would be somewhat like exposed here: 
Agent: https://github.com/hashicorp/vault-ssh-helper#agent-configuration
PAM: https://github.com/hashicorp/vault-ssh-helper#pam-configuration
SSHD: https://github.com/hashicorp/vault-ssh-helper#sshd-configuration

Opinions? Possible Alternative Conses?
