### ISSUE TITLE
Amazon ECS Agent - Support other than ":latest"

### ISSUE THREAD

**Issue by JasonSwindle** [rancher/os#777]
Howdy,

Currently, only ":latest" is used with the ECS Agent and RancherOS. Something like this:

```yaml
#cloud-config
rancher:
  environment:
    ECS_CLUSTER: your-ecs-cluster-name
# If you have selected a RancherOS AMI that does not have ECS enabled by default,
# you'll need to enable the system-service for the ECS agent.
  services_include:
    amazon-ecs-agent: true
      image: v1.7.1
```

would be really helpful.

**Comment by deniseschannon** [comment]
Officially, we will only support the latest Amazon ECS agent in our AMI, but you could use the same code for the [service](https://github.com/rancher/os-services/blob/v0.4.3/a/amazon-ecs-agent.yml) and [create your own service](http://docs.rancher.com/os/configuration/system-services/#adding-custom-system-services) to enable.

**Comment by JasonSwindle** [comment]
Howdy,

Thank you for your feedback. If there is ever a issue that impacts your usage of ECS because of the Agent, and you need to say use v1.7.1 vs latest, you now cannot use the ECS enabled RancherOS. This seems a bit counter-intuitive as sometimes you do need to peg to a know version vs "latest".

**Comment by deniseschannon** [comment]
The ECS enabled RancherOS is an AMI that just has the `amazon-ecs-agent` system-service enabled. 

So if you want a specific version, use the non-ECS enabled RancherOS (hvm) version. In the cloud-config, you can pass in to start the ecs agent for your specific version.


```
#cloud-config
rancher:
  services:
    ecs-agent-171:
       #Only change from the amazon-ecs-agent system-service is adding the version
       image: amazon/amazon-ecs-agent:v1.7.1
       labels:
          io.rancher.os.scope: system
          io.rancher.os.after: docker
       restart: always
       volumes:
         - /var/run/docker.sock:/var/run/docker.sock
         - /var/log/ecs/:/log
         - /var/lib/ecs/data:/data
         - /sys/fs/cgroup:/sys/fs/cgroup:ro
         - /var/run/docker/execdriver/native:/var/lib/docker/execdriver/native:ro
       ports:
         - "127.0.0.1:51678:51678"
       environment:
         - ECS_LOGFILE=/log/ecs-agent.log
         - ECS_LOGLEVEL=info
         - ECS_DATADIR=/data
         - ECS_*
         - AWS_*
```

After you add that, you would essentially have an ECS enabled version of RancherOS with the version that you want.
