### ISSUE TITLE
How to create a new service just like rancher/os-udev? 

### ISSUE THREAD

**Issue by zhaohb** [rancher/os#804]
Now I want to know how to create a images for the service images in rancheros ,who can help me?

**Comment by MhdAli** [comment]
I'm doing this right now, you simply need to edit rancher services to add a new service, you could also add it in your cloud-config.

Keep in mind that you need to add label to let start after network at least or maybe console service.

```
rancher
  services:
    nginx:
      image: nginx
      restart: always
      labels:
        - io.rancher.os.scope=system                                                                                   
        - io.rancher.os.after=console
```
