### ISSUE TITLE
environment variables from cloud-init not passed to system service

### ISSUE THREAD

**Issue by Slamper** [rancher/os#831]
Using RancherOS v0.4.3 I set a environment variable using cloud init
```
#cloud-config
rancher:
  environment:
    RESIZE_DEV: /dev/vda
  services_include:
    https://gist.githubusercontent.com/Slamper/620a661aa382e00ee5db/raw/eae347e1910e07f55144cdc1e8eebaecdf7e932e/rservice.yml: true
 ```

service:
```
rservice:
  image: slamper/disk_resizer:latest
  environment:
  - RESIZE_DEV
  privileged: true
  labels:
    io.rancher.os.detach: false
    io.rancher.os.scope: system
    io.rancher.os.before: console
  volumes:
  - /var/log:/var/log
```
The custom service uses the RESIZE_DEV variable but when I check the logs after the start it signals that RESIZE_DEV wasn't populated when the system container/service was started.

When I check 
``` 
[rancher@rancher ~]$ sudo ros config get rancher.environment
RESIZE_DEV: /dev/vda
```
everything looks fine but the service doesn't get the variable.

Issue:
Environment variable specified in the cloud-init isn't populated in a system container that requires it in the compose file.

**Comment by deniseschannon** [comment]
Verified with v0.4.4-rc4 that this is fixed

Used this cloud config at start

```
#cloud-config
rancher:
  environment:
    MYSQL_ROOT_PASSWORD: my-secret-pw
```

Started a system-service:
```
testsql:
  image: mysql
  environment:
    - MYSQL_ROOT_PASSWORD
```

Enabled system-service, rebooted and mysql image was up and running with no complaints about no password being set.
