### ISSUE TITLE
cloud-config not being applied even after reboot

### ISSUE THREAD

**Issue by linxit** [rancher/os#846]
I'm using terraform to provision RancherOS 0.4.3 in AWS, and trying to get the host to register with our Rancher server automatically. I'm passing various configs via cloud-config which aren't being set, even after a reboot.

The config goes into /var/lib/rancher/conf/cloud-config.d/boot.yml, exactly as provided. But very little of it is being applied - just hostname, ssh_authorized_keys and proxy settings are working.

The DNS and route settings are just ignored. If I then copy these into /var/lib/rancher/conf/cloud-config.yml (or run ros config set ...) and reboot, then it starts working.

I've seen https://github.com/rancher/os/issues/339, but at the moment I can't even get it working after a reboot without some manual tweaking.

```
#cloud-config
hostname: <my_hostname>
ssh_authorized_keys:
- ssh-rsa 
  <pubkey>
rancher:
  network:
    dns:
      search:
        - <domain1>
        - <domain2>
      nameservers:
        - <ns>
    interfaces:
      eth0:
        dhcp: true
        gateway: <gateway>
system_docker:                    
    environment:                    
    - HTTP_PROXY=<proxy:port>  
    - HTTPS_PROXY=<proxy:port>   
    - NO_PROXY=<.domain>
  docker:                           
    environment:                 
    - HTTP_PROXY=<proxy:port>
    - HTTPS_PROXY=<proxy:port>
    - NO_PROXY=<.domain>
  services:
    rancher-agent1:
      image: rancher/agent:v0.11.0
      command: sudo docker run -d --privileged -v /var/run/docker.sock:/var/run/docker.sock -v /var/lib/rancher:/var/lib/rancher rancher/agent:v0.11.0 <rancher_url> 
  services_include:
    ubuntu-console: true
    debian-console: false
```

**Comment by deniseschannon** [comment]
This is due to the fact that we can't download the user-data until networking is setup, but we don't reload the networking (i.e. dns/routes) with any changes from the user-data cloud-config.

**Comment by linxit** [comment]
I've been trying to work around this by adding a custom /etc/dhcpcd.conf with the user-data, but although this is loaded it's ignored by the system even after a reboot. 

So my custom dhcpcd.conf has static settings for routers, domain_name_servers and domain_search (with the relevant option settings from the default removed).

I didn't expect it to "just work" due to the current open bug, but surely it should be read and applied on boot?

**Comment by deniseschannon** [comment]
Verified this is working in v0.4.4-rc3.

Note: You will need to set `rancher.network.dns.override` to `true` in the cloud-config to be able override the default dns settings.

```
rancher:
  network:
    dns:
      override: true
```

In order to see the changes that you passed in during boot, you can use `sudo ros config export --boot`.
