### ISSUE TITLE
RancherOS using wrong mtu in OpenStack

### ISSUE THREAD

**Issue by hwaastad** [rancher/os#900]
Ref discussion:
https://forums.rancher.com/t/rancheros-wrong-mtu-in-openstack/2489/11

In addition, docker daemon need --mtu settings

/hw

**Comment by arno01** [comment]
In case if someone is looking for a workaround, here is a cloud-config script:

```
#cloud-config
write_files:
  - path: /etc/rc.local
	permissions: "0755"
	owner: root
	content: |
	  #!/bin/sh
	  /sbin/ip link set mtu 1450 dev eth0

rancher:
  docker:
	extra_args: [--mtu=1450]
```
