### ISSUE TITLE
System Services Error : no command specified 

### ISSUE THREAD

**Issue by will835559313** [rancher/os#912]
when I run a container on boot use system serives  there has a error on boot
this is my config file

#####/var/lib/rancher/conf/rancher-nginx.yml######
```
#cloud-config
rancher:
    services: 
        nginxapp:
        image: nginx
        restart: always
```
############################################

then I run this command
ros service enable var/lib/rancher/conf/rancher-nginx.yml

and then reboot 

the error come 
 API error (500) : No command specified

please help me 
thank you

**Comment by deniseschannon** [comment]
What version of RancherOS are you running? 

I added in the triple backticks to make the codeblock work, but is that white spacing matching your file? The `image` and `restart` need to be further indented.

It should look more like this:

```
#cloud-config
rancher:
  services: 
    nginxapp:
        image: nginx
        restart: always
```
