### ISSUE TITLE
Unable to enable a custom service or system-service

### ISSUE THREAD

**Issue by deniseschannon** [rancher/os#930]
**RancherOS Version: (ros os version)**
v0.4.5-rc2

Following the docs: http://docs.rancher.com/os/configuration/system-services/

I am unable to enable the example service.

File saved at `/var/lib/rancher/conf/example.yml`
```
#cloud-config
rancher:
  services: 
    nginxapp:
      image: nginx
      restart: always
```

```
sudo ros service enable /var/lib/rancher/conf/example.yml
```

Sometimes in the console I get this error message:

```
 "Waiting for Docker at unix:///var/run/docker.sock"
```
